const $=id=>document.getElementById(id),ctx=$('scene').getContext('2d');ctx.imageSmoothingEnabled=false;
const TEXT={ko:{title:'한 칸 상회 · 거리 아트 시험판',buy:'음료 구매',restock:'재고 보충',pause:'일시정지',resume:'계속',reset:'초기화','scale-label':'배율',layers:'개별 그림 보기','scene-label':'골목 상점 앞','stock-label':'자판기 재고','warehouse-label':'창고 재고','sales-label':'판매액','scale-info-label':'표시 배율','sheet-title':'개별 도트 자산',note:'구매 또는 보충을 눌러 동작을 확인하세요. 본편 저장과 별도로 실행됩니다.',foot:'480 × 300 · 공통 24색 · 정수 배율',idle:'영업 대기',walk:'손님이 자판기로 이동 중',use:'음료 구매 중',leave:'구매 완료',delivery:'배송 직원 이동 중',fill:'재고 보충 중',done:'보충 완료'},ja:{title:'一マス商店 · 街のアート試作',buy:'飲料を購入',restock:'在庫補充',pause:'一時停止',resume:'続行',reset:'リセット','scale-label':'倍率',layers:'個別画像を見る','scene-label':'路地の商店前','stock-label':'自販機在庫','warehouse-label':'倉庫在庫','sales-label':'売上','scale-info-label':'表示倍率','sheet-title':'個別ドット素材',note:'購入または補充で動作を確認できます。本編のセーブとは独立しています。',foot:'480 × 300 · 共通24色 · 整数倍率',idle:'営業待機',walk:'お客様が移動中',use:'飲料を購入中',leave:'購入完了',delivery:'配送員が移動中',fill:'補充作業中',done:'補充完了'}};
let lang=navigator.language.startsWith('ja')?'ja':'ko',stock=4,warehouse=24,sales=0,paused=false,action=null,elapsed=0,phase='idle';
function ui(){const t=TEXT[lang];for(const id of ['title','buy','restock','reset','scale-label','layers','scene-label','stock-label','warehouse-label','sales-label','scale-info-label','sheet-title','note','foot'])$(id).textContent=t[id];$('pause').textContent=t[paused?'resume':'pause'];$('pause').setAttribute('aria-pressed',String(paused));$('status').textContent=t[phase];$('stock').textContent=stock+' / 12';$('warehouse').textContent=warehouse;$('sales').textContent='$'+sales.toFixed(2);$('buy').disabled=!!action||stock===0;$('restock').disabled=!!action||stock===12||warehouse===0;document.documentElement.lang=lang;$('scene').setAttribute('aria-label',t['scene-label']);}
function scale(){const n=$('scale').value==='auto'?Math.max(1,Math.min(3,Math.floor(($('viewport').clientWidth-4)/480),Math.floor((innerHeight-150)/300))):Number($('scale').value);$('scene').style.width=480*n+'px';$('scene').style.height=300*n+'px';$('scale-info').textContent=n+'×';}
function draw(name,x,y){const s=SPRITES[name];ctx.drawImage(s.canvas,Math.round(x-s.ax),Math.round(y-s.ay));}
function iso(x,y){return [240+(x-y)*24,44+(x+y)*12];}
function start(type){if(action||(type==='buy'&&!stock)||(type==='restock'&&(stock===12||!warehouse)))return;action=type;elapsed=0;phase=type==='buy'?'walk':'delivery';ui();}
function tick(dt){if(!action||paused)return;elapsed+=dt;const next=elapsed<3?(action==='buy'?'walk':'delivery'):elapsed<4.5?(action==='buy'?'use':'fill'):(action==='buy'?'leave':'done');if(next!==phase){if(next==='leave'){stock--;sales+=1.5;}if(next==='done'){const n=Math.min(12-stock,warehouse);stock+=n;warehouse-=n;}phase=next;ui();}if(elapsed>=7.5){action=null;phase='idle';ui();}}
function paint(){ctx.fillStyle=PAL.grass;ctx.fillRect(0,0,480,300);for(let sum=-25;sum<40;sum++)for(let x=-20;x<25;x++){let y=sum-x;if(y<-20||y>25)continue;const p=iso(x,y);draw(y>=7&&y<=9?'road':y>=3&&y<=10?'paving':'lawn',...p);}
 const p=new Pixel(ctx);for(let x=-14;x<20;x+=2){const a=iso(x,8.5),b=iso(x+.8,8.5);p.line(...a,...b,'yellow');}for(const y of [6.5,9.5]){const a=iso(-20,y),b=iso(25,y);p.line(...a,...b,'mist');}
 const objects=[['store',277,166],['machine'+(stock?'':'-empty'),235,174],['bin',267,189],['bench',336,204],['lamp',170,147],['tree',377,126],['tree',418,167],['tree',114,98],['tree',65,77],['bench',81,253],['lamp',131,278]];
 if(!action){objects.push(['customer-se-0',70,108],['worker-nw-0',393,250],['cart',406,256]);}if(action){const buy=action==='buy',from=buy?[70,108]:[393,250],to=buy?[228,187]:[249,185],progress=elapsed<3?elapsed/3:elapsed<4.5?1:Math.max(0,1-(elapsed-4.5)/3),x=from[0]+(to[0]-from[0])*progress,y=from[1]+(to[1]-from[1])*progress;const using=elapsed>=3&&elapsed<4.5,dir=buy?(elapsed<4.5?'se':'nw'):(elapsed<4.5?'nw':'se');objects.push([(buy?'customer':'worker')+(using?'-use':'-'+dir+'-'+(Math.floor(elapsed*7)%4)),x,y]);if(!buy)objects.push(['cart',x+13,y+6]);if(buy&&elapsed>=4.5)objects.push(['can',x-6,y-11]);}
 objects.sort((a,b)=>a[2]-b[2]);for(const o of objects)draw(...o);
}
$('buy').onclick=()=>start('buy');$('restock').onclick=()=>start('restock');$('pause').onclick=()=>{paused=!paused;ui();};$('reset').onclick=()=>{stock=4;warehouse=24;sales=0;paused=false;action=null;elapsed=0;phase='idle';ui();paint();};$('language').value=lang;$('language').onchange=e=>{lang=e.target.value;ui();};$('scale').onchange=scale;new ResizeObserver(scale).observe($('viewport'));
$('layers').onclick=()=>{const hidden=!$('sheet-panel').hidden;$('sheet-panel').hidden=hidden;$('layers').setAttribute('aria-pressed',String(!hidden));};
for(const color of Object.values(PAL)){const e=document.createElement('i');e.style.background=color;e.title=color;$('palette').append(e);}for(const name of ['paving','road','lawn','store','machine','tree','lamp','bench','bin','cart',...['customer','worker'].flatMap(a=>[0,1,2,3].map(i=>a+'-ne-'+i))]){const s=SPRITES[name],box=document.createElement('div'),c=document.createElement('canvas'),label=document.createElement('span');box.className='asset';c.width=s.w;c.height=s.h;c.getContext('2d').drawImage(s.canvas,0,0);c.style.width=s.w*2+'px';c.style.height=s.h*2+'px';label.textContent=name+' · '+s.w+'×'+s.h;box.append(c,label);$('sheet').append(box);}
let last=0;document.addEventListener('visibilitychange',()=>{last=0;});function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(!document.hidden)tick(dt);paint();requestAnimationFrame(frame);}ui();scale();paint();requestAnimationFrame(frame);
window.artLab={state:()=>({stock,warehouse,sales,paused,action,elapsed,phase}),palette:PAL,sprites:SPRITES};


