const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(process.env.GAME_URL||'http://127.0.0.1:8765/');assert.equal(await page.locator('#game-menu-close').count(),0);
 await page.locator('#menu-new').click();await page.locator('#launch-new').click();await page.evaluate(()=>{if(modalView)closeModal();livePaused=true;render();window.originalMap=document.querySelector('.map-wrap');});
 const cityVisible=async()=>assert.ok(await page.evaluate(()=>{const n=document.querySelector('.map-wrap'),r=n.getBoundingClientRect();return n===originalMap&&!deskMap.hidden&&r.width>100&&r.height>50&&n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),'city remains visible and unobstructed');
 for(const language of ['ko','ja']){await page.locator('#language').selectOption(language);for(const tab of await page.evaluate(()=>visibleDeskTabs().map(t=>t[0]))){await page.locator(`#desk-nav [data-desk="${tab}"]`).click();await cityVisible();assert.ok(await page.locator('#desk-side').isVisible());assert.equal(await page.locator('#desktop-title').innerText(),await page.locator(`#desk-nav [data-desk="${tab}"]`).innerText());}}
 await page.locator('#desk-nav [data-desk="finance"]').click();await page.locator('#ref-mg-amount').fill('37');
 await page.locator('#desktop-minimize').click();assert.equal(await page.locator('#desk-side').isVisible(),false);await cityVisible();await page.locator('#desktop-task').click();assert.equal(await page.locator('#ref-mg-amount').inputValue(),'37');
 await page.locator('#desktop-close').click();assert.equal(await page.locator('#desktop-task').isVisible(),false);await cityVisible();await page.locator('#desk-nav [data-desk="finance"]').click();assert.ok(await page.locator('#desk-side').isVisible());
 await page.locator('#desktop-minimize').focus();await page.keyboard.press('Escape');assert.equal(await page.locator('#desk-side').isVisible(),false);await page.keyboard.press('Enter');assert.ok(await page.locator('#desk-side').isVisible());
 for(const [width,height] of [[1440,900],[800,600],[390,844],[720,450]]){await page.setViewportSize({width,height});await cityVisible();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(os.tmpdir(),`hankan-desktop-${width}.png`)});}
 await page.setViewportSize({width:1440,height:900});await page.locator('#game-menu').click();assert.ok(await page.locator('#game-menu-close').isVisible());await page.locator('#game-menu-close').click();assert.ok(await page.locator('#desk-side').isVisible());assert.deepEqual(errors,[]);
 console.log('PASS desktop: every KO/JA route retains unobstructed city, window minimize/restore/close, form preservation, keyboard, distinct menus and four viewports');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
