// Regression coverage for explicitly retained pre-supply-chain saves.
const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require('node:path').join(__dirname,'../dist/index.html'),'utf8');
function setup(raw,url='https://hankan.test'){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{runScripts:'dangerously',url,virtualConsole:vc,beforeParse(w){w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.Math.random=()=>.5;if(raw)w.localStorage.setItem('hankan-tycoon-v1',raw);}});return {dom,errors,ev:s=>dom.window.eval(s)};}
const run=setup(),{ev,dom,errors}=run;
ev('profile.tutorialSeen=true;setupRules={...STANDARD_RULES,events:0,supply:0};chosenDuration=36500;launchBeforeSupplyChain();state.cash=30000000;');
assert.ok(ev('valid(state)'));assert.equal(ev('state.saveVersion'),7);
// Investment consumes cash; work in progress becomes physical inventory without creating book value.
assert.ok(ev('buildFactory(playerFirm(),"drink")'));assert.ok(ev('buildFactory(playerFirm(),"machine")'));
const eq=ev('companyEquity(playerFirm())');assert.ok(ev('produce(playerFirm(),"drink",0,100)'));assert.equal(ev('companyEquity(playerFirm())'),eq);
assert.equal(ev('produce(playerFirm(),"drink",0,100)'),false,'one job per line');assert.ok(ev('produce(playerFirm(),"machine",0,1)'));
const raw=ev('JSON.stringify(state)'),resume=setup(raw);assert.ok(resume.ev('valid(state)'));ev('companyReceive(playerFirm(),DAY_MS)');resume.ev('companyReceive(playerFirm(),DAY_MS)');assert.equal(ev('JSON.stringify(state.enterprise.expansion)'),resume.ev('JSON.stringify(state.enterprise.expansion)'));resume.dom.window.close();
assert.equal(ev('state.enterprise.warehouse[0].qty'),100);assert.equal(ev('companyEquity(playerFirm())'),eq);ev('companyReceive(playerFirm(),DAY_MS*2)');assert.equal(ev('expansionFirm(playerFirm()).kits.length'),1);
const beforeInstall=ev('companyEquity(playerFirm())');assert.ok(ev('installKit(playerFirm(),1)'));assert.equal(ev('expansionFirm(playerFirm()).kits.length'),0);assert.ok(ev('companyEquity(playerFirm())')<beforeInstall);assert.equal(ev('installKit(playerFirm(),1)'),false);
// Conservative expiry survives transfers, charges book loss once, and cannot be reset by mixing.
ev('const pf=playerFirm();pf.ops.warehouse[0].expiresDay=state.day+2;machine(1).slots.forEach(s=>{s.stock=0;s.value=0;s.expiresDay=0});syncMachine(machine(1));companyRestock(pf,machine(1));');
assert.ok(ev('machine(1).slots.every(s=>!s.stock||s.expiresDay===state.day+2)'));
ev('state.day+=2;state.live=null;expireInventory(playerFirm())');const wasted=ev('expansionFirm(playerFirm()).waste');assert.ok(wasted>=100);ev('expireInventory(playerFirm())');assert.equal(ev('expansionFirm(playerFirm()).waste'),wasted);
// Shares conserve cash with a finite counterparty; a round trip loses the spread.
const cash=ev('state.cash'),allCash=ev('state.cash+state.enterprise.expansion.exchange.cash');assert.ok(ev('tradeStock(playerFirm(),"maker:1",100)'));assert.equal(ev('state.cash+state.enterprise.expansion.exchange.cash'),allCash);assert.ok(ev('tradeStock(playerFirm(),"maker:1",-100)'));assert.ok(ev('state.cash')<cash);assert.equal(ev('tradeStock(playerFirm(),"maker:1",-1)'),false);
ev('tradeStock(playerFirm(),"maker:1",100)');const dividendCash=ev('state.cash'),makerCash=ev('state.enterprise.expansion.maker.cash');ev('payDividend(state.enterprise.expansion.exchange.listings.find(l=>l.firm==="maker"),100000)');assert.equal(ev('state.cash'),dividendCash+10000);assert.equal(ev('state.enterprise.expansion.maker.cash'),makerCash-100000);
// City opens actual map locations; escrow refunds outbids, settles once and survives loading.
assert.ok(ev('openNewCity()'));assert.equal(ev('MAPS.length'),5);assert.equal(ev('LOCATIONS.length'),30);assert.ok(ev('valid(state)'));
const bid=ev('state.enterprise.expansion.auctions[0].id'),beforeBid=ev('state.cash');assert.ok(ev(`bidLand(playerFirm(),${bid},400000)`));assert.equal(ev('state.cash'),beforeBid-400000);ev('rivalById("atlas").account.cash=2000000');assert.ok(ev(`bidLand(rivalById("atlas"),${bid},410000)`));assert.equal(ev('state.cash'),beforeBid);assert.ok(ev(`bidLand(playerFirm(),${bid},420000)`));
const citySave=setup(ev('JSON.stringify(state)'));assert.equal(citySave.ev('MAPS.length'),5);assert.ok(citySave.ev('valid(state)'));citySave.dom.window.close();
ev('state.day+=3;state.live=null;settleAuctions()');assert.ok(ev('machine(24)'));const count=ev('state.machines.length');ev('settleAuctions()');assert.equal(ev('state.machines.length'),count);assert.ok(ev('valid(state)'));
// Future choices are saved, due only on their scheduled day, and applied once.
ev('state.pending={id:"regulation-review",loc:0};openModal("event");resolveEvent(1)');assert.equal(ev('state.enterprise.expansion.queue.length'),1);const future=setup(ev('JSON.stringify(state)'));assert.equal(future.ev('state.enterprise.expansion.queue.length'),1);future.dom.window.close();
const costBefore=ev('state.cash');ev('applyOutcomes()');assert.equal(ev('state.cash'),costBefore);ev('state.day+=3;state.live=null;applyOutcomes()');assert.equal(ev('state.cash'),costBefore-25000);ev('applyOutcomes()');assert.equal(ev('state.cash'),costBefore-25000);
// Whole-company merger carries production, portfolio, machines and debt, delists the target once.
ev('const af=rivalById("atlas"),nf=rivalById("nova");af.account.cash=30000000;nf.account.cash=3000000;buildFactory(nf,"drink");produce(nf,"drink",0,100);tradeStock(nf,"maker:1",20);nf.bank.principal=50000;tradeStock(playerFirm(),listingKey(nf),100);');
const machines=ev('rivalById("atlas").machines.length+rivalById("nova").machines.length');assert.ok(ev('mergeCompanies(rivalById("atlas"),rivalById("nova"))'));assert.equal(ev('rivalById("atlas").machines.length'),machines);assert.equal(ev('rivalById("atlas").bank.principal'),50000);assert.equal(ev('expansionFirm(rivalById("atlas")).jobs.length'),1);assert.equal(ev('expansionFirm(rivalById("atlas")).holdings["maker:1"].qty'),20);assert.equal(ev('mergeCompanies(rivalById("atlas"),rivalById("nova"))'),false);assert.ok(ev('valid(state)'));
ev('state.cash=100000000;quoteCompany("atlas")');assert.ok(ev('completeCompanyBuyout()'));assert.ok(ev('expansionFirm(playerFirm()).plants.drink===2'));assert.ok(ev('valid(state)'));assert.ok(ev('liquidateProduction(playerFirm())'));const book=ev('expansionFirm(playerFirm()).plantValue');assert.ok(ev('liquidatePlant(playerFirm(),"drink")'));assert.equal(ev('expansionFirm(playerFirm()).plantValue'),book-600000);
// Collateral blocks negotiated sale; paying arrears cancels enforcement. Recovery inventory is actionable.
ev('state.bank.principal=0;state.bank.arrears=0;playerFirm().meta.credit=65;');assert.ok(ev('collateralLoan(playerFirm(),0)'));ev('state.bank.arrears=1000;state.bank.missed=3;creditorReview(playerFirm())');assert.ok(ev('expansionFirm(playerFirm()).foreclosure>state.day'));ev('repayCompany(playerFirm(),1000)');assert.equal(ev('expansionFirm(playerFirm()).foreclosure'),0);
ev('state.enterprise.warehouse[0]={qty:10,value:5000,expiresDay:state.day+20}');const recoveryCash=ev('state.cash');assert.ok(ev('liquidateWarehouse(playerFirm(),0)'));assert.equal(ev('state.cash'),recoveryCash+2500);assert.equal(ev('liquidateWarehouse(playerFirm(),0)'),false);
// Every expansion panel is localized and re-rendering does not mutate time controls.
ev('changeLanguage("ja")');for(const tab of ['manufacture','securities','development','policies']){ev(`selectDesk('${tab}')`);assert.ok(!/[가-힣]/.test(dom.window.document.querySelector('#expansion-panel').textContent),tab);}
const control=dom.window.document.getElementById('scene-pause'),mutations=new dom.window.MutationObserver(()=>{});mutations.observe(control,{childList:true,subtree:true,characterData:true});ev('for(let n=0;n<20;n++){updateDesk();syncScene()}');assert.equal(mutations.takeRecords().length,0);mutations.disconnect();
assert.ok(!dom.window.document.querySelector('[data-desk="simulation"]'));
// Malformed persistent resources and duplicated shares are rejected, not silently reset.
ev('state.enterprise.expansion.firms.player.holdings["maker:1"].qty+=1000');assert.equal(ev('valid(state)'),false);ev('state.enterprise.expansion.firms.player.holdings["maker:1"].qty-=1000');assert.ok(ev('valid(state)'));
ev('retireCompany()');assert.equal(ev('state.ending.reason'),'retired');assert.ok(ev('valid(state)'));ev('continueGame()');assert.equal(ev('state.ended'),false);
assert.deepEqual(errors,[]);dom.window.close();
const debug=setup(undefined,'https://hankan.test/?debug=1');assert.ok(debug.dom.window.document.querySelector('[data-desk="simulation"]'));debug.dom.window.close();
const ai=setup();ai.ev('profile.tutorialSeen=true;setupRules={...STANDARD_RULES,events:0};chosenDuration=36500;launchBeforeSupplyChain();state.day=30;state.live=null;rivalById("mono").account.cash=10000000;rivalById("atlas").account.cash=100000;rivalById("atlas").meta.distress=3;rivalById("atlas").ops.lastProfit=-50000;expansionAI()');assert.ok(ai.ev('state.enterprise.expansion.mergers>=1'),'funded AI actually executes eligible company mergers');assert.ok(ai.ev('valid(state)'));assert.deepEqual(ai.errors,[]);ai.dom.window.close();
const ending=setup();ending.ev('profile.tutorialSeen=true;setupRules={...STANDARD_RULES,events:0};chosenDuration=180;launchBeforeSupplyChain();state.cash=100000000;state.reputation=100;buildFactory(playerFirm(),"drink");buildFactory(playerFirm(),"machine");for(const l of LOCATIONS){if(state.machines.length>=10)break;if(!machine(l.id)&&!rivalLocations().includes(l.id)){selected=l.id;act("buy");}}expansionFirm(playerFirm()).produced=3000;state.enterprise.expansion.dominanceDays=29;state.profit=10000;checkEnding(true)');assert.equal(ending.ev('state.ending.reason'),'industry');assert.equal(ending.ev('state.enterprise.expansion.dominanceDays'),30);ending.ev('checkEnding(true)');assert.equal(ending.ev('state.enterprise.expansion.dominanceDays'),30);assert.ok(ending.ev('valid(state)'));assert.deepEqual(ending.errors,[]);ending.dom.window.close();
console.log('PASS: production and book value, expiry, finite stock trading and cash-backed dividends, city escrow/load, delayed outcomes, corporate mergers/assets, collateral/recovery, KO/JA stable UI and save validation.');


