const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync(require('node:path').join(__dirname,'../dist/index.html'),'utf8'),{runScripts:'dangerously',url:'https://hankan.test',virtualConsole:vc,beforeParse(w){w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.Math.random=()=>.5;}}),ev=s=>dom.window.eval(s);
ev('profile.tutorialSeen=true;setupRules={...STANDARD_RULES,events:0,supply:0};launchReference();state.cash=30000000;selectDesk("business");');
assert.deepEqual(errors,[]);assert.ok(ev('refEnabled()'));assert.ok(ev('valid(state)'));assert.ok(ev('refCheckConservation(playerFirm())'));
for(const desk of ['sites','logistics','people','supply','products','production','research','equipment','contracts','finance','group','reports'])ev(`refDesk='${desk}';renderReference()`);
ev('window.f=playerFirm();window.hub=refHome(f).id;window.equity=companyEquity(f);window.cash=state.cash;');
assert.ok(ev('refOrder(f,"sun:0",100,hub)'));
assert.equal(ev('companyEquity(f)'),ev('equity'),'purchase remains an inventory asset');
ev('companyReceive(f,DAY_MS*2)');assert.ok(ev('refCheckConservation(f)'));
assert.equal(ev('f.ops.warehouse[0].qty'),100);
ev('machine(0).slots.forEach(s=>{s.batches=[];refSyncBucket(s,true)});syncMachine(machine(0));companyRestock(f,machine(0));');
assert.ok(ev('refCheckConservation(f)'));assert.ok(ev('machine(0).stock>0'));
assert.ok(ev('refHireEmployee(f,"restock",hub,2)'));assert.ok(ev('refHireEmployee(f,"restock",hub,2)'));
assert.equal(ev('refStaffPower(f,"restock",hub)'),4);
ev('refTake(machine(0).slots[0],10);refSyncBucket(machine(0).slots[0],true);syncMachine(machine(0));window.route=refRoute(f,hub,refFirm(f).vehicles[0].id,[0]);window.eq=companyEquity(f)');
assert.ok(ev('refDispatchRoute(f,route)'));assert.equal(ev('companyEquity(f)'),ev('eq-200'),'route cargo stays on balance sheet');
ev('companyReceive(f,DAY_MS)');assert.ok(ev('refCheckConservation(f)'));
assert.ok(ev('refTerms(f,"aqua",50,7)'));ev('window.cash=state.cash;window.eq=companyEquity(f)');
assert.ok(ev('refOrder(f,"aqua:0",50,hub)'));assert.equal(ev('state.cash'),ev('cash'));assert.equal(ev('companyEquity(f)'),ev('eq'));
assert.ok(ev('refResearch(f,"quality","aqua")'));assert.equal(ev('chainFirm(f).licenses.quality'),0);
ev('for(let k=0;k<3;k++){companyReceive(f,DAY_MS*4);for(const p of refFirm(f).projects){if(p.paused)refResearchTopUp(f,p.id);if(p.review)refResearchReview(f,p.id,"continue");}}');assert.equal(ev('chainFirm(f).licenses.quality'),1);
ev('window.factory=refBuildSite(f,"drink",0);companyReceive(f,DAY_MS*5)');assert.ok(ev('factory'));
assert.ok(ev('refHireEmployee(f,"drink",factory,1)'));
ev('window.sku=refLaunchProduct(f,0,"house",false)');assert.ok(ev('sku'));
assert.equal(ev('refProduce(f,factory,sku,100)'),false);
for(const raw of ['water','concentrate','package'])assert.ok(ev(`refRawOrder(f,'${raw}',100,1,factory)`));
ev('companyReceive(f,DAY_MS*2);window.eq=companyEquity(f)');assert.ok(ev('refProduce(f,factory,sku,100)'));assert.equal(ev('companyEquity(f)'),ev('eq'));
ev('companyReceive(f,DAY_MS*3)');assert.ok(ev('refCheckConservation(f)'));assert.equal(ev('refFirm(f).stats.manufactured'),100);
ev('window.eq=companyEquity(f)');assert.ok(ev('refBorrow(f,100000)'));assert.equal(ev('companyEquity(f)'),ev('eq'));assert.ok(ev('refRepay(f,refFirm(f).notes[0].id)'));assert.equal(ev('companyEquity(f)'),ev('eq'));
ev('window.eq=companyEquity(f)');assert.ok(ev('refContract(f,0,"share")'));assert.equal(ev('companyEquity(f)'),ev('eq'));
assert.ok(ev('valid(state)'));assert.ok(ev('validReference(state.enterprise.reference,state)'));
ev('changeLanguage("ja")');for(const desk of ['sites','logistics','people','supply','products','production','research','equipment','contracts','finance','group','reports']){ev(`refDesk='${desk}';renderReference()`);assert.ok(!/[가-힣]/.test(dom.window.document.querySelector('#reference-panel').textContent),desk);}
assert.deepEqual(errors,[]);dom.window.close();console.log('PASS reference bootstrap, purchase/credit/cargo conservation, staff capacity, staged research, factory materials, finance, contracts and Japanese ledgers');
