const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require('node:path').join(__dirname,'../dist/index.html'),'utf8');
function create(raw){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://hankan.test',virtualConsole:vc,beforeParse(w){w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.Math.random=()=>.5;if(raw)w.localStorage.setItem('hankan-tycoon-v1',raw);}});return {dom,errors,ev:s=>dom.window.eval(s)};}
const results=[];for(const seed of [7,19473,731293]){const {dom,errors,ev}=create();ev(`profile.tutorialSeen=true;setupRules={...STANDARD_RULES,events:3,supply:2};chosenDuration=36500;launchReference();state.enterprise.rng=${seed};render=()=>{};save=()=>{};refreshLiveNumbers=()=>{};toast=()=>{};`);
for(let n=0;n<120&&!ev('state.ended');n++){ev(`for(const c of [...state.complaints])respondComplaint(c.id);if(state.pending)resolveEvent(1);if(modalView&&!state.pending)closeModal();livePaused=false;{const f=playerFirm(),h=refHome(f),r=refFirm(f);for(const m of f.machines){if(m.vault){f.account.cash+=m.vault;m.vault=0;}companyRestock(f,m);if(m.condition<40)chainRepair(f,m.loc);}for(let p=0;p<2;p++)if(f.ops.warehouse[p].qty<50&&!r.work.some(j=>j.kind==='purchase'&&j.product===p))refOrder(f,'aqua:'+p,100,h.id);}if(!state.live)startBusiness();advanceBusiness(DAY_MS);`);
if(!ev('valid(state)&&validReference(state.enterprise.reference,state)&&allFirms().every(f=>refCheckConservation(f))')){fs.writeFileSync(require('node:path').join(require('node:os').tmpdir(),'hankan-reference-invalid.json'),ev('JSON.stringify(state)'));throw Error('Invalid reference seed '+seed+' day '+ev('state.day')+' valid '+ev('valid(state)')+' ref '+ev('validReference(state.enterprise.reference,state)')+' batches '+ev('allFirms().map(f=>[f.id,refCheckConservation(f)])'));}
assert.ok(ev('allFirms().every(f=>refFirm(f).reports.filter(r=>r.final).every(r=>Math.abs(r.assets-r.liabilities-r.equity)<.01&&Math.abs(r.operating+r.investing+r.financing+r.internal-r.cashChange)<.01))'));assert.ok(ev('!refFirm(playerFirm()).reports[0]?.final||refFirm(playerFirm()).reports[0].profit===state.enterprise.reports[0].net'));
if(n===29||n===89){const reload=create(ev('JSON.stringify(state)'));assert.equal(reload.ev('loadWarning'),false);assert.deepEqual(reload.errors,[]);reload.dom.window.close();}}
assert.deepEqual(errors,[]);results.push({seed,day:ev('state.day'),ended:ev('state.ended'),cash:ev('state.cash')});dom.window.close();}console.log('REFERENCE_STABILITY '+JSON.stringify(results));
