const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require('node:path').join(__dirname,'../dist/index.html'),'utf8'),errors=[];
function setup(languages=['ko-KR'],savedLang,query='',raw){const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));return new JSDOM(html,{runScripts:'dangerously',url:'https://hankan.test/'+query,virtualConsole:vc,beforeParse(w){Object.defineProperty(w.navigator,'languages',{value:languages});w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.Math.random=()=>.5;if(savedLang)w.localStorage.setItem('hankan-language',savedLang);if(raw)w.localStorage.setItem('hankan-tycoon-v1',raw);}});}
for(const [languages,saved,query,expected] of [[['ja-JP'],null,'','ja'],[['en-US','ja'],null,'','ja'],[['ja-JP'],'ko','','ko'],[['ko-KR'],'ko','?lang=ja','ja'],[['en-US'],null,'','ko']]){const d=setup(languages,saved,query);assert.equal(d.window.document.documentElement.lang,expected);assert.ok(d.window.document.querySelector('dialog[open] [data-entry-language="ja"]'),'language reachable in entry dialog');d.window.document.querySelector('[data-entry-language="ja"]').click();assert.equal(d.window.document.documentElement.lang,'ja');assert.equal(d.window.localStorage.getItem('hankan-language'),'ja');d.window.close();}
const d=setup(),w=d.window,doc=w.document,ev=s=>w.eval(s);
ev('state=fresh();state.started=true;state.cash=500000;state.research.products=3;menuOpen=false;closeModal();state.machines[0].loc=6;selected=6;selectedMap=1;ensureEnterprise();startBusiness();');
const profit=ev('rivalDailyProfit()'),share=ev('competitionStrength(1).share');
assert.ok(ev('startCampaign(1,"loyalty")'));assert.ok(ev('rivalDailyProfit()')<profit);assert.ok(ev('competitionStrength(1).share')>share);assert.equal(ev('state.cash'),475000);assert.equal(ev('state.enterprise.expenseToday'),25000);assert.equal(ev('startCampaign(1,"discount")'),false,'no stacking');
ev('state.enterprise.rivalry.campaigns[1]=null;startCampaign(1,"discount");');assert.equal(ev('campaignPrice(machine(6).slots[0],1)'),1275);
ev('window.r={served:0,revenue:0,cost:0,bought:[]};for(let i=0;i<20;i++)customerPurchase(machine(6),r,i)');assert.ok(ev('r.served')>0);assert.equal(ev('r.revenue'),ev('r.served')*1275,'discount reflected in actual receipts');
ev('state.enterprise.rivalry.campaigns[1]=null;state.enterprise.rivalry.mode="price";state.enterprise.rivalry.target=1;state.enterprise.rivalry.until=3;state.enterprise.rivalPrices[1]=1050;');const pressure=ev('rivalCompetition(1)');ev('startCampaign(1,"defend")');assert.ok(ev('rivalCompetition(1)')<pressure,'defense reduces attack pressure');
// Funded AI attacks overlapping markets and actually reduces customer attractiveness.
ev('state.enterprise.rivalry=rivalryFresh();state.npc.cash=500000;state.day=2;rivalTurn();');assert.equal(ev('state.enterprise.rivalry.plan.mode'),'price');assert.equal(ev('state.enterprise.rivalry.plan.start'),3);ev('state.day=3;rivalTurn()');assert.equal(ev('state.enterprise.rivalry.mode'),'price');assert.equal(ev('state.enterprise.rivalry.target'),1);assert.equal(ev('state.enterprise.rivalPrices[1]'),1050);const npcCash=ev('state.npc.cash');ev('rivalTurn()');assert.equal(ev('state.npc.cash'),npcCash,'one rival settlement per day');
// Prices and cashflow for the closed day are snapshotted before campaigns expire.
ev('state.enterprise.rivalry.pendingProfit=-12345;state.day=4;rivalTurn()');assert.equal(ev('state.enterprise.rivalry.lastProfit'),-12345);
// Cash starvation causes liquidation then final exit, not infinite free attacks.
ev('state.enterprise.rivalry=rivalryFresh();state.npc.cash=-10000000;state.day=10;rivalTurn()');assert.equal(ev('state.npc.owned.length'),1);assert.equal(ev('state.enterprise.rivalry.mode'),'retreat');
for(let day=11;day<=14;day++)ev(`state.day=${day};rivalTurn()`);
assert.equal(ev('state.enterprise.rivalry.defeated'),true);assert.equal(ev('state.npc.owned.length'),0);ev('checkEnding()');assert.equal(ev('state.ended'),false,'rival exit is a milestone, not an instant ending');ev('state.live=null;startBusiness()');
ev('save()');const raw=w.localStorage.getItem('hankan-tycoon-v1');const reload=setup(['ja'],null,'',raw);assert.equal(reload.window.eval('state.enterprise.rivalry.defeated'),true);reload.window.close();
ev('lang="ja";enterpriseTab="rivalry";renderEnterprise();');assert.ok(!/[가-힣]/.test(doc.querySelector('#enterprise').textContent));
// Campaign controls also survive live refreshes.
ev('state=fresh();state.started=true;state.machines[0].loc=6;selected=6;state.cash=500000;menuOpen=false;closeModal();ensureEnterprise();startBusiness();enterpriseTab="rivalry";renderEnterprise();');const button=doc.querySelector('[data-campaign="discount"][data-campaign-map="1"]');button.focus();ev('refreshLiveNumbers();renderEnterprise()');assert.equal(doc.activeElement,button);button.click();assert.equal(ev('activeCampaign(1).kind'),'discount');
ev('state.npc.cash=987654321;state.enterprise.rivalry.lastProfit=-123456789;renderRivalPanel();renderEnterprise()');const visible=doc.querySelector('#rival-panel').textContent+doc.querySelector('#enterprise').textContent;assert.ok(!visible.includes(ev('money(state.npc.cash)')));assert.ok(!visible.includes(ev('money(state.enterprise.rivalry.lastProfit)')));assert.equal(ev('state.npc.cash'),987654321,'internal finances retained');assert.deepEqual(errors,[]);d.window.close();console.log('PASS: first-visit Japanese, saved/link precedence, immediate language switch, shared rival profits, actual discount receipts, defense, funded AI, insolvency milestone without ending, hidden financials, save and stable campaign controls.');
