const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require('node:path').join(__dirname,'../dist/index.html'),'utf8'),errors=[];
function setup(raw){const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));return new JSDOM(html,{runScripts:'dangerously',url:'https://hankan.test',virtualConsole:vc,beforeParse(w){w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.Math.random=()=>.5;if(raw)w.localStorage.setItem('hankan-tycoon-v1',raw);}});}
const d=setup(),w=d.window,doc=w.document,ev=s=>w.eval(s),change=(id,value)=>{const el=doc.getElementById(id);assert.ok(el,id);el.value=String(value);el.dispatchEvent(new w.Event('change',{bubbles:true}));};
doc.getElementById('menu-settings').click();assert.ok(doc.getElementById('settings-close'));doc.getElementById('settings-close').click();assert.equal(ev('modalView'),'menu');doc.getElementById('menu-new').click();assert.equal(doc.querySelectorAll('[data-rule]').length,10);assert.equal(doc.getElementById('rule-inflation').disabled,true);
change('scenario-preset','extreme');assert.equal(ev('setupRules.rivalMachines'),6);assert.equal(doc.getElementById('rule-inflation').disabled,false);
change('rule-cycle',0);assert.equal(ev('setupRules.inflation'),0);assert.equal(doc.getElementById('rule-inflation').disabled,true);assert.equal(ev('setupPreset'),'custom');
change('scenario-preset','extreme');ev('profile.clears=7;profile.tutorialSeen=true');doc.getElementById('launch-new').click();assert.equal(ev('state.cash'),150000);assert.equal(ev('state.npc.cash'),3000000);assert.equal(ev('state.npc.owned.length'),6);assert.equal(ev('state.difficulty'),0);assert.ok(ev('valid(state)'));assert.equal(ev('state.live.day'),1);
ev('setupRules.playerFunds=750000');assert.equal(ev('state.scenario.rules.playerFunds'),150000,'draft cannot mutate run');
ev('save()');const raw=w.localStorage.getItem('hankan-tycoon-v1'),reload=setup(raw);assert.equal(reload.window.eval('state.scenario.rules.supply'),2);assert.equal(reload.window.eval('state.cash'),150000);reload.window.close();
// Supplier risk changes lead time once, preserving purchase value.
ev('state.cash=1000000;state.scenario.rules.supply=0;window.randomBefore=enterpriseRandom;enterpriseRandom=()=>0;');const before=ev('assets()');assert.ok(ev('orderGoods(0,100,1)'));assert.equal(ev('state.enterprise.orders[0].duration'),33600);assert.equal(ev('assets()'),before);
ev('state.scenario.rules.supply=2;orderGoods(0,100,1)');assert.equal(ev('state.enterprise.orders[1].duration'),57600);assert.equal(ev('assets()'),before);ev('enterpriseRandom=randomBefore');
// Event controls affect all random incident paths, without suppressing rival strategy.
ev('state.scenario.rules.events=0;state.pending=null;state.complaints=[];state.effects=[];Math.random=()=>0;worldEvents();');assert.equal(ev('state.pending'),null);assert.equal(ev('state.complaints.length'),0);assert.equal(ev('state.effects.length'),0);
ev('state.scenario.rules.events=3;queueEvent()');assert.ok(ev('state.pending'));
// Annual inflation affects goods, staff and site costs; cycles affect both firms through demand.
ev('state.day=366;state.scenario.rules.cycle=1;state.scenario.rules.inflation=8;state.enterprise.index=1;chainHire(playerFirm(),"collect")');assert.ok(Math.abs(ev('inflationFactor()')-1.08)<1e-10);assert.equal(ev('procurementPrice(0,0)'),513);assert.equal(ev('staffSalary()'),2160);assert.equal(ev('dailyRent(machine(0))'),2700);
ev('state.day=12');assert.ok(ev('cycleFactor()')>1.1);ev('state.scenario.rules.cycle=0;state.scenario.rules.inflation=0');assert.equal(ev('cycleFactor()'),1);assert.equal(ev('inflationFactor()'),1);
ev('state.scenario.rules.expertise=0');const strength=ev('competitionStrength(1).rival');ev('state.scenario.rules.expertise=2');assert.ok(ev('competitionStrength(1).rival')>strength);assert.equal(ev('rivalCostFactor()'),.88);
ev('state.scenario.rules.aggression=0');assert.equal(ev('scenarioAttackDays()'),2);assert.equal(ev('scenarioExpansionInterval()'),7);ev('state.scenario.rules.aggression=2');assert.equal(ev('scenarioAttackDays()'),4);assert.equal(ev('scenarioExpansionInterval()'),3);
const invalid=JSON.parse(raw);invalid.scenario.rules.rivalMachines=30;const bad=setup(JSON.stringify(invalid));assert.equal(bad.window.eval('loadWarning'),true);bad.window.close();
const legacy=JSON.parse(raw);delete legacy.scenario;const old=setup(JSON.stringify(legacy));assert.equal(old.window.eval('state.cash'),legacy.cash);assert.equal(old.window.eval('runRules().supply'),0);old.window.close();
ev('lang="ja";openModal("newrun")');assert.ok(!/[가-힣]/.test(doc.querySelector('#scenario-setup').textContent));ev('openModal("settings")');assert.ok(doc.querySelector('.scenario-current'));assert.equal(doc.querySelectorAll('.scenario-current select').length,0);ev('livePaused=true');doc.getElementById('settings-close').click();assert.equal(ev('modalView'),null);assert.equal(ev('menuOpen'),false);assert.equal(ev('livePaused'),true,'closing settings preserves manual pause');
assert.deepEqual(errors,[]);d.window.close();console.log('PASS: ten real setup controls, presets, prerequisites, frozen save rules, funding/locations, event-off, supply delays, inflation/cycles, AI ability, legacy compatibility and Japanese setup.');
