const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require('node:path').join(__dirname,'../dist/index.html'),'utf8');
function setup(raw){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://hankan.test',virtualConsole:vc,beforeParse(w){w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.Math.random=()=>.5;if(raw)w.localStorage.setItem('hankan-tycoon-v1',raw);}});return {dom,errors,ev:s=>dom.window.eval(s)};}
const {dom,errors,ev}=setup();ev('profile.tutorialSeen=true;setupRules={...STANDARD_RULES,events:0,supply:0};chosenDuration=36500;launchNew();state.cash=30000000;');
assert.ok(ev('chainEnabled()'));assert.ok(ev('valid(state)'));
// Buying a site alone cannot spawn inventory or a machine; manufacturers receive real cash.
const before=ev('companyEquity(playerFirm())'),supplierCash=ev('chainSupplier("koyo").cash');assert.ok(ev('reserveSite(playerFirm(),1)'));assert.equal(ev('machine(1)'),undefined);assert.equal(ev('installKit(playerFirm(),1)'),false);
assert.ok(ev('chainOrderMachine(playerFirm(),"koyo",1)'));assert.equal(ev('companyEquity(playerFirm())'),before);assert.equal(ev('chainSupplier("koyo").cash'),supplierCash+260000);ev('companyReceive(playerFirm(),DAY_MS)');assert.equal(ev('expansionFirm(playerFirm()).kits.length'),0);ev('companyReceive(playerFirm(),DAY_MS)');assert.equal(ev('expansionFirm(playerFirm()).kits.length'),1);
assert.ok(ev('installKit(playerFirm(),1)'));assert.equal(ev('machine(1)'),undefined);ev('companyReceive(playerFirm(),DAY_MS)');assert.equal(ev('machine(1).stock'),0);assert.equal(ev('capacity(machine(1))'),120);assert.equal(ev('chainFirm(playerFirm()).sites.length'),0);assert.ok(ev('valid(state)'));
// Purchased quality is attached to inventory. Research cannot rewrite already purchased stock.
const allCash=ev('state.cash+supplierAccount(chainSupplier("sun")).cash');assert.ok(ev('companyOrder(playerFirm(),0,100,1)'));assert.equal(ev('state.cash+supplierAccount(chainSupplier("sun")).cash'),allCash);ev('companyReceive(playerFirm(),DAY_MS*2);companyRestock(playerFirm(),machine(1));');assert.equal(ev('machine(1).stock'),100);assert.equal(ev('machine(1).slots[0].quality'),1);
assert.equal(ev('buildFactory(playerFirm(),"drink")'),false);assert.ok(ev('chainResearch(playerFirm(),"quality","aqua",true)'));assert.equal(ev('chainResearch(rivalById("mono"),"quality","aqua")'),false);assert.equal(ev('chainFirm(playerFirm()).licenses.quality'),0);
const projectValue=ev('companyEquity(playerFirm())');ev('companyReceive(playerFirm(),DAY_MS*2)');assert.equal(ev('chainFirm(playerFirm()).licenses.quality'),0);assert.ok(ev('companyEquity(playerFirm())')<projectValue);
const resume=setup(ev('JSON.stringify(state)'));assert.equal(resume.ev('loadWarning'),false);assert.ok(resume.ev('valid(state)'));ev('companyReceive(playerFirm(),DAY_MS*6)');resume.ev('companyReceive(playerFirm(),DAY_MS*6)');assert.equal(ev('JSON.stringify(state.enterprise.chain)'),resume.ev('JSON.stringify(state.enterprise.chain)'));resume.dom.window.close();
assert.equal(ev('chainFirm(playerFirm()).licenses.quality'),1);assert.equal(ev('machine(1).slots[0].quality'),1);assert.ok(ev('chainResearch(playerFirm(),"quality","aqua",true)'),'next tier can start while prior rights remain');assert.equal(ev('chainResearch(rivalById("mono"),"quality","aqua")'),false);
// Factory construction, materials and paid workers are all required. Training pauses production.
assert.ok(ev('buildFactory(playerFirm(),"drink")'));assert.equal(ev('expansionFirm(playerFirm()).plants.drink'),0);assert.ok(ev('orderMaterials(playerFirm(),"drink",100)'));ev('companyReceive(playerFirm(),DAY_MS*5)');assert.equal(ev('expansionFirm(playerFirm()).plants.drink'),1);assert.equal(ev('produce(playerFirm(),"drink",0,100)'),false);assert.ok(ev('chainHire(playerFirm(),"drink")'));const wage=ev('staffSalary()');assert.ok(wage>0);assert.ok(ev('produce(playerFirm(),"drink",0,100)'));assert.equal(ev('chainFirm(playerFirm()).materials.drink.qty'),0);ev('window.employee=chainFirm(playerFirm()).staff.find(w=>w.role==="drink").id;chainTrain(playerFirm(),employee)');const remaining=ev('expansionFirm(playerFirm()).jobs[0].remaining');ev('companyReceive(playerFirm(),DAY_MS)');assert.equal(ev('expansionFirm(playerFirm()).jobs[0].remaining'),remaining);assert.equal(ev('staffSalary()'),wage);ev('companyReceive(playerFirm(),DAY_MS*4);companyReceive(playerFirm(),DAY_MS)');assert.equal(ev('expansionFirm(playerFirm()).jobs.length'),0);assert.equal(ev('chainFirm(playerFirm()).staff.find(w=>w.id===employee).skill'),1.5);
ev('chainHire(playerFirm(),"collect");chainHire(playerFirm(),"restock")');const employees=ev('chainFirm(playerFirm()).staff.length');assert.ok(ev('chainDismiss(playerFirm(),employee)'));assert.equal(ev('chainFirm(playerFirm()).staff.length'),employees-1);assert.ok(ev('valid(state)'));
// Japanese surfaces and stable controls, including menu/help return routing.
ev('changeLanguage("ja")');for(const tab of ['equipment','supply','staff','research','manufacture']){ev(`selectDesk('${tab}')`);assert.ok(!dom.window.document.querySelector('#chain-panel').hidden);assert.ok(!/[가-힣]/.test(dom.window.document.querySelector('#chain-panel').textContent),tab);}
ev('openModal("pause");openModal("help")');assert.ok(dom.window.document.querySelector('#menu-back'));ev('closeModal()');const control=dom.window.document.querySelector('#scene-pause'),observer=new dom.window.MutationObserver(()=>{});observer.observe(control,{childList:true,subtree:true,characterData:true});ev('for(let i=0;i<20;i++)updateDesk()');assert.equal(observer.takeRecords().length,0);observer.disconnect();
// New assets have a real liquidation route and malformed workforce data is rejected.
ev('orderMaterials(playerFirm(),"machine",1)');const recover=ev('state.cash'),book=ev('chainAssets(playerFirm())');assert.ok(ev('chainLiquidate(playerFirm())'));assert.equal(ev('state.cash'),recover+book*.5);assert.ok(ev('valid(state)'));ev('chainFirm(playerFirm()).staff[0].skill=99');assert.equal(ev('valid(state)'),false);assert.deepEqual(errors,[]);dom.window.close();
// Existing saves do not silently switch economic rules; the pause menu offers migration.
const old=setup();old.ev('profile.tutorialSeen=true;launchBeforeSupplyChain();save()');const migrated=setup(old.ev('JSON.stringify(state)'));assert.equal(migrated.ev('chainEnabled()'),false);migrated.ev('openModal("pause")');assert.ok(migrated.dom.window.document.querySelector('[data-chain="migrate"]'));migrated.dom.window.document.querySelector('[data-chain="migrate"]').click();assert.ok(migrated.ev('chainEnabled()'));assert.ok(migrated.ev('valid(state)'));assert.ok(migrated.ev('localStorage.getItem(KEY+"-backup-before-supply-chain")'));old.dom.window.close();migrated.dom.window.close();
// Staff cannot repair two machines at full individual throughput simultaneously.
const teams=setup();teams.ev('profile.tutorialSeen=true;setupRules={...STANDARD_RULES,events:0};launchNew();state.cash=30000000;chainHire(playerFirm(),"technician");reserveSite(playerFirm(),1);chainOrderMachine(playerFirm(),"koyo",0);companyReceive(playerFirm(),DAY_MS*2);installKit(playerFirm(),1);companyReceive(playerFirm(),DAY_MS);machine(0).condition=20;machine(1).condition=20;chainRepair(playerFirm(),0);chainRepair(playerFirm(),1);companyReceive(playerFirm(),DAY_MS)');assert.equal(teams.ev('chainFirm(playerFirm()).orders.filter(o=>o.kind==="repair").length'),2);teams.ev('companyReceive(playerFirm(),DAY_MS)');assert.equal(teams.ev('machine(0).condition'),100);assert.equal(teams.ev('machine(1).condition'),100);
// NPC re-entry purchases stock and installs it later, and buyout transfers pending assets and people.
teams.ev('closeCompany(rivalById("mono"),"자금조달 실패")');assert.ok(teams.ev('reviveCompany(rivalById("mono"))'));assert.equal(teams.ev('rivalById("mono").machines.length'),0);assert.equal(teams.ev('chainFirm(rivalById("mono")).orders.filter(o=>o.kind==="machine").length'),1);assert.ok(teams.ev('valid(state)'));const jobs=teams.ev('chainFirm(rivalById("mono")).orders.length'),people=teams.ev('chainFirm(playerFirm()).staff.length+chainFirm(rivalById("mono")).staff.length');teams.ev('quoteCompany("mono")');assert.ok(teams.ev('completeCompanyBuyout()'));assert.equal(teams.ev('chainFirm(playerFirm()).staff.length'),people);assert.equal(teams.ev('chainFirm(playerFirm()).orders.length'),jobs);assert.ok(teams.ev('valid(state)'));assert.deepEqual(teams.errors,[]);teams.dom.window.close();
console.log('PASS: finite supplier payment, separate site/machine/installation, physical quality, funded delayed exclusive research, factory/material/staff constraints, shared work capacity, education/payroll, NPC re-entry/buyout, save replay/migration, liquidation and Japanese UI.');
