/* Persistent expansion economy. All time advances through the existing business clock. */
function registerExpansionCity(){
 if(MAPS.length>4)return;
 MAPS.push({id:4,name:B('항만 신도시','港湾新都市'),desc:B('신규 입지 · 공개 입찰','新規立地・公開入札'),permit:0,color:'#78949a'});
 for(let n=0;n<6;n++){const name=B(['항만역','물류단지','신도시 청사','수변 공원','국제 터미널','주거 타워'][n],['港湾駅','物流団地','新都市庁舎','水辺公園','国際ターミナル','住宅タワー'][n]);LOCATIONS.push({...LOCATIONS[n],id:24+n,map:4,name,short:name,desc:MAPS[4].desc,kind:['station','office','office','park','station','home'][n],traffic:90+n*8,rent:7000+n*650,cost:300000+n*25000,auction:true});}
}
function registerExpansionEvents(){
 const data=[['supply-review','공급망 중단 예고','供給網停止予告','3일 후 미입고 주문의 배송이 2일 지연됩니다.','3日後、未着注文の配送が2日遅延します。','대체 운송 $15','代替輸送 $15',15000],['regulation-review','위생 재검사 통지','衛生再検査通知','3일 후 점검: 사전 정비를 하지 않으면 과태료 $25와 평판 -3.','3日後に検査。事前整備なしの場合、過料$25と評判−3。','사전 점검 $10','事前点検 $10',10000],['staff-review','직원 이직 통보','スタッフ退職通知','3일 후 보충 직원 1명이 퇴사합니다.','3日後に補充スタッフ1人が退職します。','유지 수당 $8','慰留手当 $8',8000],['finance-review','신용 재심사','信用再審査','3일 후 신용등급 -8. 외부 심사를 받으면 -2로 제한됩니다.','3日後に信用−8。外部審査で−2に抑制できます。','외부 심사 $6','外部審査 $6',6000]];
 for(const [id,ko,ja,dk,dj,ok,oj,fee] of data)if(!EVENTS.some(e=>e.id===id))EVENTS.push({id,icon:'',name:B(ko,ja),desc:B(dk,dj),options:[option(B(ok,oj),fee,0),option(B('예정대로 진행','予定どおり実施'),0,0)]});
}
function expansionFreshFirm(){return {plants:{drink:0,machine:0},plantValue:0,facilities:[],jobs:[],kits:[],holdings:{},memory:[],produced:0,waste:0,wasteValue:0,dividends:0,interestPaid:0,pledges:[],foreclosure:0,lastAI:0,automation:{enabled:false,min:40,target:160,markup:0,repair:0,transfer:0,reserve:100000,collectMap:-1,restockMap:-1}};}
function expansionEnabled(){return industryEconomy()&&!!state.enterprise.expansion;}
function expansionFirm(f){return state.enterprise.expansion.firms[f.id];}
function allFirms(){return [playerFirm(),...rivalFirms()];}
function expansionInitialize(){
 if(!industryEnabled())return;
 const e=state.enterprise;
 if(!e.expansion){try{const raw=localStorage.getItem(KEY);if(raw&&!localStorage.getItem(KEY+'-backup-before-expansion'))localStorage.setItem(KEY+'-backup-before-expansion',raw);}catch{}e.expansion={version:1,lastDay:0,lastAssessment:0,cityOpen:false,firms:{},queue:[],next:1,auctions:[],exchange:{cash:5000000,listings:[],lastDay:0},maker:{cash:1500000,profit:0,totalProfit:0},mergers:0,retired:false,dominanceDays:0,debug:false,peakValue:0};}
 for(const f of allFirms())if(!e.expansion.firms[f.id])e.expansion.firms[f.id]=expansionFreshFirm();
 state.saveVersion=7;
 if(e.expansion.cityOpen){registerExpansionCity();expandDistrictArrays();for(const l of LOCATIONS.filter(l=>l.map===4))l.auction=e.expansion.auctions.some(a=>a.loc===l.id);}
 if(industryEconomy())for(const f of allFirms())stampCompanyInventory(f);
 ensureListings();
}
function expandDistrictArrays(){
 const e=state.enterprise;
 for(const [array,value] of [[e.brand,15],[e.ads,0],[e.rivalPrices,1500],...allFirms().flatMap(f=>[[f.meta.brand,15],[f.meta.prices,1500],...(f.policy?[[f.policy.campaigns,null]]:[])])])while(array.length<MAPS.length)array.push(value);
 while(e.rivalry.campaigns.length<MAPS.length)e.rivalry.campaigns.push(null);
 for(const f of rivalFirms())if(f.ops.market&&!f.ops.market.legacy)while(f.ops.market.districts.length<MAPS.length)f.ops.market.districts.push({n:0,attempted:0,player:0,rival:0,none:0});
}
function expiryLife(p){return p===4?8:p===5?12:30;}
function expiryMerge(bucket,day,count){if(count>0)bucket.expiresDay=bucket.expiresDay>0?Math.min(bucket.expiresDay,day):day;}
function stampCompanyInventory(f){for(let p=0;p<6;p++){const w=f.ops.warehouse[p];if(w.qty&&!w.expiresDay)w.expiresDay=state.day+expiryLife(p);if(!w.qty)w.expiresDay=0;}for(const o of f.ops.orders)if(!o.expiresDay)o.expiresDay=state.day+expiryLife(o.product);for(const m of f.machines){ensureSlots(m);for(const s of m.slots){if(s.stock&&!s.expiresDay)s.expiresDay=state.day+expiryLife(s.product);if(!s.stock)s.expiresDay=0;}}}
function warehouseUsed(f){return f.ops.warehouse.reduce((n,w)=>n+w.qty,0)+f.ops.orders.reduce((n,o)=>n+o.qty,0)+(expansionEnabled()?expansionFirm(f).jobs.filter(j=>j.kind==='drink').reduce((n,j)=>n+j.qty,0):0);}
function factoryCost(f,kind){return (kind==='drink'?600000:1000000)*(expansionFirm(f).plants[kind]+1);}
function buildFactory(f,kind){if(!expansionEnabled()||!['drink','machine'].includes(kind)||state.ended)return false;const x=expansionFirm(f),cost=factoryCost(f,kind);if(x.plants[kind]>=3||f.account.cash<cost)return false;f.account.cash-=cost;x.plants[kind]++;x.plantValue+=cost;x.facilities.push({kind,value:cost});return true;}
function produce(f,kind,p,qty){
 if(!expansionEnabled()||state.ended||!['drink','machine'].includes(kind)||!int(p,0,5)||!int(qty,1,500))return false;
 const x=expansionFirm(f),level=x.plants[kind];if(!level||x.jobs.filter(j=>j.kind===kind).length>=level||kind==='machine'&&qty!==1||kind==='drink'&&(PRODUCTS[p].unlock>f.research.products||warehouseUsed(f)+qty>1000+f.tech.logistics*500))return false;
 const value=kind==='drink'?Math.round(PRODUCTS[p].cost*.68*state.enterprise.index*inflationFactor())*qty:180000;
 if(f.account.cash<value)return false;f.account.cash-=value;
 const duration=DAY_MS*(kind==='drink'?1:3)/(1+(level-1)*.25);x.jobs.push({id:state.enterprise.expansion.next++,kind,product:p,qty,value,remaining:duration,duration});return true;
}
function installKit(f,loc){const x=expansionFirm(f),l=LOCATIONS[loc];if(!x.kits.length||!l||l.auction||machine(loc)||rivalLocations().includes(loc)||state.ended||f.id==='player'&&!canBuild(loc))return false;const fee=Math.round(l.cost*.35);if(f.account.cash<fee)return false;const kit=x.kits.shift();f.account.cash-=fee;const m=npcMachine(loc);m.bookCost=fee+kit.value;f.machines.push(m);if(f.id!=='player')f.account.owned.push(loc);return true;}
function expansionAssets(f){if(!expansionEnabled())return 0;const x=expansionFirm(f),e=state.enterprise.expansion;return x.plantValue*.5+x.jobs.reduce((n,j)=>n+j.value,0)+x.kits.reduce((n,k)=>n+k.value,0)+Object.entries(x.holdings).reduce((n,[id,h])=>n+(e.exchange.listings.find(l=>l.id===id)?.price||0)*h.qty,0)+e.auctions.filter(a=>a.bidder===f.id).reduce((n,a)=>n+a.bid,0);}
const expansionStockAssets=companyStockAssets;companyStockAssets=function(f){return expansionStockAssets(f)+expansionAssets(f);};
const expansionOldAssets=assets;assets=function(){return expansionOldAssets()+(expansionEnabled()?expansionAssets(playerFirm()):0);};
const expansionOrder=companyOrder;
companyOrder=function(f,p,qty,supplier){if(expansionEnabled()&&warehouseUsed(f)+qty>1000+f.tech.logistics*500)return false;const ok=expansionOrder(f,p,qty,supplier);if(ok&&expansionEnabled()){const o=f.ops.orders.at(-1);o.expiresDay=state.day+expiryLife(p);const margin=Math.round(o.value*.18),maker=state.enterprise.expansion.maker;maker.cash+=margin;maker.profit+=margin;maker.totalProfit+=margin;}return ok;};
const expansionReceive=companyReceive;
companyReceive=function(f,ms){
 if(!expansionEnabled())return expansionReceive(f,ms);
 stampCompanyInventory(f);
 const incoming=f.ops.orders.filter(o=>o.remaining<=ms).map(o=>({...o}));
 expansionReceive(f,ms);
 for(const o of incoming)expiryMerge(f.ops.warehouse[o.product],o.expiresDay,o.qty);
 const x=expansionFirm(f);for(const j of x.jobs)j.remaining-=ms;
 for(const j of x.jobs.filter(j=>j.remaining<=0)){if(j.kind==='drink'){const w=f.ops.warehouse[j.product];w.qty+=j.qty;w.value+=j.value;expiryMerge(w,state.day+expiryLife(j.product),j.qty);x.produced+=j.qty;}else x.kits.push({value:j.value});}
 x.jobs=x.jobs.filter(j=>j.remaining>0);
};
const expansionRestock=companyRestock;
companyRestock=function(f,m,emergency=false){if(!expansionEnabled())return expansionRestock(f,m,emergency);stampCompanyInventory(f);const before=m.slots.map(s=>({stock:s.stock,day:s.expiresDay,warehouse:f.ops.warehouse[s.product].expiresDay,available:f.ops.warehouse[s.product].qty})),n=expansionRestock(f,m,emergency);m.slots.forEach((s,i)=>{if(s.stock>before[i].stock)expiryMerge(s,before[i].available?before[i].warehouse:state.day+expiryLife(s.product),s.stock-before[i].stock);});stampCompanyInventory(f);return n;};
const expansionSlot=enterpriseSlotProduct;
enterpriseSlotProduct=function(slot,id){const m=machine(selected),s=m?.slots?.[slot],p=s?.product,qty=s?.stock,day=s?.expiresDay;expansionSlot(slot,id);if(expansionEnabled()&&s&&s.product!==p){expiryMerge(state.enterprise.warehouse[p],day||state.day+expiryLife(p),qty);s.expiresDay=0;save();}};
function expenseBookLoss(f,amount){if(f.id==='player')f.ops.expenseToday+=amount;else if(f.ops.market&&f.ops.settledDay<state.day)f.ops.market.extra+=amount;else f.meta.pendingExpense=(f.meta.pendingExpense||0)+amount;}
function expireInventory(f){stampCompanyInventory(f);const x=expansionFirm(f);let lost=0,count=0;for(const w of f.ops.warehouse)if(w.qty&&w.expiresDay<=state.day){lost+=w.value;count+=w.qty;w.qty=0;w.value=0;w.expiresDay=0;}for(const m of f.machines){for(const s of m.slots)if(s.stock&&s.expiresDay<=state.day){lost+=s.value;count+=s.stock;s.stock=0;s.value=0;s.expiresDay=0;}syncMachine(m);}for(const o of f.ops.orders.filter(o=>o.expiresDay<=state.day)){lost+=o.value;count+=o.qty;}f.ops.orders=f.ops.orders.filter(o=>o.expiresDay>state.day);if(count){x.waste+=count;x.wasteValue+=lost;expenseBookLoss(f,lost);if(f.id==='player')log(B(`유통기한 도래 · ${count}개 폐기 · ${money(lost)}`,`期限到来・${count}本廃棄・${money(lost)}`));}}
function liquidateWarehouse(f,p){if(!int(p,0,5)||state.ended)return false;const w=f.ops.warehouse[p];if(!w.qty)return false;const value=w.value;f.account.cash+=value*.5;expenseBookLoss(f,value*.5);w.qty=0;w.value=0;w.expiresDay=0;return true;}
function liquidatePlant(f,kind){const x=expansionFirm(f);if(!['drink','machine'].includes(kind)||!x.plants[kind]||x.jobs.some(j=>j.kind===kind))return false;const index=x.facilities.findLastIndex(v=>v.kind===kind),basis=x.facilities[index].value;x.facilities.splice(index,1);f.account.cash+=basis*.5;x.plantValue-=basis;x.plants[kind]--;return true;}
function listingKey(f){return f.id+':'+f.meta.generation;}
function ensureListings(){if(!expansionEnabled())return;const e=state.enterprise.expansion;for(const f of rivalFirms())if(!f.policy.defeated&&!e.exchange.listings.some(l=>l.id===listingKey(f)))e.exchange.listings.push({id:listingKey(f),firm:f.id,generation:f.meta.generation,price:Math.max(100,Math.round(companyValue(f)/1000)),float:1000,dividend:0});if(!e.exchange.listings.some(l=>l.id==='maker:1'))e.exchange.listings.push({id:'maker:1',firm:'maker',generation:1,price:1500,float:1000,dividend:0});e.exchange.listings=e.exchange.listings.filter(l=>l.firm==='maker'||rivalFirms().some(f=>listingKey(f)===l.id&&!f.policy.defeated));}
function tradeStock(f,id,qty){
 if(!expansionEnabled()||state.ended||!int(qty,-1000,1000)||qty===0)return false;
 const e=state.enterprise.expansion,l=e.exchange.listings.find(l=>l.id===id),x=expansionFirm(f);if(!l||l.firm===f.id&&qty>0)return false;
 const h=x.holdings[id]||{qty:0,value:0},unit=Math.round(l.price*(qty>0?1.02:.98)),cost=Math.abs(qty)*unit;
 if(qty>0){if(l.float<qty||f.account.cash<cost||f.id!=='player'&&h.qty+qty>200)return false;f.account.cash-=cost;e.exchange.cash+=cost;l.float-=qty;h.qty+=qty;h.value+=cost;}
 else{if(h.qty< -qty||e.exchange.cash<cost)return false;const basis=h.value*(-qty)/h.qty;h.qty+=qty;h.value=Math.max(0,h.value-basis);f.account.cash+=cost;e.exchange.cash-=cost;l.float-=qty;expenseBookLoss(f,basis-cost);}
 if(h.qty)x.holdings[id]=h;else delete x.holdings[id];return true;
}
function payDividend(l,amount){const e=state.enterprise.expansion,f=l.firm==='maker'?null:rivalById(l.firm),account=f?.account||e.maker,total=Math.min(Math.max(0,account.cash),Math.max(0,Math.floor(amount/1000)*1000));if(!total)return;l.dividend=total/1000;account.cash-=total;for(const holder of allFirms()){const q=expansionFirm(holder).holdings[l.id]?.qty||0,payment=q*l.dividend;if(payment){holder.account.cash+=payment;expansionFirm(holder).dividends+=payment;expenseBookLoss(holder,-payment);}}e.exchange.cash+=l.float*l.dividend;}
function settleListing(id,price){const e=state.enterprise.expansion,l=e.exchange.listings.find(l=>l.id===id);if(!l)return;for(const f of allFirms()){const h=expansionFirm(f).holdings[id];if(h){const paid=price*h.qty/1000;f.account.cash+=paid;expenseBookLoss(f,h.value-paid);delete expansionFirm(f).holdings[id];}}e.exchange.cash+=price*l.float/1000;e.exchange.listings=e.exchange.listings.filter(v=>v!==l);}
function closeMarketDay(){const e=state.enterprise.expansion;if(e.exchange.lastDay>=state.day)return;e.exchange.lastDay=state.day;ensureListings();for(const l of e.exchange.listings){l.dividend=0;if(l.firm==='maker'){if(state.day%30===0){payDividend(l,e.maker.profit*.3);e.maker.profit=0;}l.price=Math.max(100,Math.round((e.maker.cash+Math.max(0,e.maker.totalProfit)*.2)/1000));}else{const f=rivalById(l.firm);if(state.day%30===0&&f.meta.distress===0&&f.account.cash>150000)payDividend(l,Math.min(f.account.cash-150000,Math.max(0,f.meta.history.slice(0,30).reduce((n,r)=>n+r.net,0))*.2));l.price=Math.max(100,Math.round(companyValue(f)/1000));}}}
function openNewCity(){const e=state.enterprise.expansion;if(!expansionEnabled()||e.cityOpen||state.cash<750000||state.ended)return false;companyExpense(playerFirm(),750000);e.cityOpen=true;registerExpansionCity();expandDistrictArrays();for(let n=24;n<30;n++)e.auctions.push({id:e.next++,loc:n,until:state.day+3+(n-24)*2,bid:0,bidder:null});log(B('항만 신도시 입찰 공고 · 6개 입지','港湾新都市の入札公告・6立地'));return true;}
function bidLand(f,id,amount){const e=state.enterprise.expansion,a=e.auctions.find(a=>a.id===id);if(!a||state.ended||a.until<state.day||!int(amount,1,1000000000)||amount<Math.max(LOCATIONS[a.loc].cost,a.bid+10000)||machine(a.loc)||rivalLocations().includes(a.loc))return false;const own=a.bidder===f.id?a.bid:0;if(f.account.cash+own<amount)return false;const prev=allFirms().find(v=>v.id===a.bidder);if(prev)prev.account.cash+=a.bid;f.account.cash-=amount;a.bid=amount;a.bidder=f.id;return true;}
function settleAuctions(){const e=state.enterprise.expansion;for(const a of [...e.auctions])if(a.until<=state.day){const f=allFirms().find(f=>f.id===a.bidder&&!f.policy?.defeated);if(!f){if(a.bidder){const holder=allFirms().find(f=>f.id===a.bidder);if(holder)holder.account.cash+=a.bid;}a.bid=0;a.bidder=null;a.until=state.day+5;continue;}const m=npcMachine(a.loc);m.bookCost=a.bid;f.machines.push(m);if(f.id!=='player')f.account.owned.push(a.loc);LOCATIONS[a.loc].auction=false;e.auctions=e.auctions.filter(x=>x!==a);log(B(`${LOCATIONS[a.loc].short[0]} 낙찰 · ${companyNameFor(f.id,0)}`,`${LOCATIONS[a.loc].short[1]}落札・${companyNameFor(f.id,1)}`));}}
function leaseTerms(f,m,term){const base=LOCATIONS[m.loc].rent*(1-f.research.efficiency*.1)*inflationFactor(),loyal=m.lease?.until>=state.day-3?1:0,trust=f.id==='player'?state.reputation:f.meta.credit,discount=term===60?.15:.08;return {until:state.day+term-1,rate:Math.round(base*(1-discount-loyal*.02-(trust>=70?.02:0)+(m.loc%3)*.015)),fee:Math.round(base*(term===60?4:2)),penalty:Math.round(base*(term===60?8:3)),term};}
function negotiateLease(f,m,term){if(![30,60].includes(term)||m.lease&&m.lease.until>state.day+5)return false;const c=leaseTerms(f,m,term);if(f.account.cash<c.fee)return false;companyExpense(f,c.fee);m.lease=c;return true;}
function endLease(f,m){if(!m.lease)return false;const fee=m.lease.until>=state.day?(m.lease.penalty||m.lease.rate*3):0;if(f.account.cash<fee)return false;companyExpense(f,fee);m.lease=null;return true;}
function collateralLoan(f,loc){const x=expansionFirm(f),m=f.machines.find(m=>m.loc===loc);if(!m||x.pledges.includes(loc)||state.ended)return false;const amount=borrowCompany(f,Math.min(companyBorrowRoom(f),Math.round(equipment(m)*.4)));if(!amount)return false;x.pledges.push(loc);return true;}
function creditorReview(f){const x=expansionFirm(f);x.pledges=x.pledges.filter(id=>f.machines.some(m=>m.loc===id));if(!f.bank.principal&&!f.bank.arrears){x.pledges=[];x.foreclosure=0;return;}if(f.bank.missed>=3&&x.pledges.length&&!x.foreclosure){x.foreclosure=state.day+3;if(f.id==='player')log(B(`담보 실행 예고 · DAY ${x.foreclosure} · 연체 해소 필요`,`担保処分予告・DAY ${x.foreclosure}・延滞解消が必要`));}if(!f.bank.missed){x.foreclosure=0;return;}if(x.foreclosure&&x.foreclosure<=state.day){const id=x.pledges.shift(),m=f.machines.find(m=>m.loc===id);if(m&&f.machines.length>1){f.account.cash+=m.vault+stockValue(m)*.5+equipment(m)*.5;if(f.id==='player')removeMachine(id);else removeRivalMachine(f,id);repayCompany(f,Math.max(0,f.account.cash));}x.foreclosure=0;}}
const expansionRepay=repayCompany;repayCompany=function(f,amount){const n=expansionRepay(f,amount);if(expansionEnabled()&&f.bank.arrears===0&&(state.day<f.meta.due||f.bank.principal===0)){f.bank.missed=0;expansionFirm(f).foreclosure=0;if(!f.bank.principal)expansionFirm(f).pledges=[];}return n;};
const expansionDebt=settleCompanyDebt;settleCompanyDebt=function(f){const n=expansionDebt(f);if(expansionEnabled())expansionFirm(f).interestPaid+=n;return n;};
const expansionSaleAvailable=saleAvailable;saleAvailable=function(){return expansionSaleAvailable()&&(!expansionEnabled()||!expansionFirm(playerFirm()).pledges.includes(state.offer.loc));};
function liquidateProduction(f){if(state.ended)return false;const x=expansionFirm(f),book=x.jobs.reduce((n,j)=>n+j.value,0)+x.kits.reduce((n,k)=>n+k.value,0);if(!book)return false;f.account.cash+=book*.5;expenseBookLoss(f,book*.5);x.jobs=[];x.kits=[];return true;}
const expansionRecovery=companyRecoverable;companyRecoverable=function(f){let n=expansionRecovery(f);if(expansionEnabled()){const x=expansionFirm(f),e=state.enterprise.expansion;n+=x.plantValue*.5+x.jobs.reduce((n,j)=>n+j.value*.5,0)+x.kits.reduce((n,k)=>n+k.value*.5,0);n+=Math.min(e.exchange.cash,Object.entries(x.holdings).reduce((n,[id,h])=>n+h.qty*Math.round((e.exchange.listings.find(l=>l.id===id)?.price||0)*.98),0));}return n;};
const expansionRate=companyRate;companyRate=function(f){return Math.max(.0015,expansionRate(f)-(expansionEnabled()&&expansionFirm(f).pledges.length?.0004:0));};
function recoverCompanyCash(f){if(f.account.cash>=0)return;for(const m of f.machines){f.account.cash+=m.vault;m.vault=0;}for(let p=0;p<6&&f.account.cash<0;p++)liquidateWarehouse(f,p);if(f.account.cash<0)liquidateProduction(f);for(const kind of ['drink','machine'])while(f.account.cash<0&&expansionFirm(f).plants[kind])if(!liquidatePlant(f,kind))break;for(const [id,h] of Object.entries(expansionFirm(f).holdings))if(f.account.cash<0)tradeStock(f,id,-h.qty);}
const expansionCashTurn=rivalTurn;rivalTurn=function(){if(expansionEnabled())for(const f of rivalFirms())if(!f.policy.defeated)recoverCompanyCash(f);return expansionCashTurn();};
function transferExpansionAssets(buyer,target){const e=state.enterprise.expansion,b=expansionFirm(buyer),t=expansionFirm(target);for(const key of ['drink','machine'])b.plants[key]+=t.plants[key];b.plantValue+=t.plantValue;b.facilities.push(...t.facilities);b.jobs.push(...t.jobs);b.kits.push(...t.kits);for(const [id,h] of Object.entries(t.holdings)){const own=b.holdings[id]||{qty:0,value:0};own.qty+=h.qty;own.value+=h.value;b.holdings[id]=own;}b.pledges.push(...t.pledges);for(const a of e.auctions)if(a.bidder===target.id)a.bidder=buyer.id;e.firms[target.id]=expansionFreshFirm();}
const expansionBuyoutError=companyBuyoutError;companyBuyoutError=function(){const error=expansionBuyoutError();if(error||!expansionEnabled())return error;const f=rivalById(state.enterprise.industry.buyout.id);return warehouseUsed(playerFirm())+warehouseUsed(f)>1000+Math.max(playerFirm().tech.logistics,f.tech.logistics)*500?T('생산 중 재고를 포함한 창고 공간 부족','生産中在庫を含む倉庫容量不足'):'';};
const expansionBuyout=completeCompanyBuyout;completeCompanyBuyout=function(){if(!expansionEnabled())return expansionBuyout();if(companyBuyoutError())return false;const f=rivalById(state.enterprise.industry.buyout.id),key=listingKey(f),price=state.enterprise.industry.buyout.price,dates=f.ops.warehouse.map(w=>w.expiresDay);const ok=expansionBuyout();if(ok){settleListing(key,price);transferExpansionAssets(playerFirm(),f);dates.forEach((d,p)=>expiryMerge(state.enterprise.warehouse[p],d||state.day+expiryLife(p),state.enterprise.warehouse[p].qty));save();render();}return ok;};
function mergeCompanies(buyer,target){
 if(!expansionEnabled()||buyer.id===target.id||buyer.id==='player'||target.id==='player'||buyer.policy.defeated||target.policy.defeated)return false;
 const price=Math.max(250000,Math.round(companyValue(target)*1.1)),fee=target.meta.contract&&target.meta.contract.until>=state.day?5000:0;
 if(buyer.account.cash<price+fee+150000||buyer.bank.principal+target.bank.principal>1000000||warehouseUsed(buyer)+warehouseUsed(target)>1000+Math.max(buyer.tech.logistics,target.tech.logistics)*500)return false;
 buyer.account.cash+=target.account.cash-price;companyExpense(buyer,fee);buyer.bank.principal+=target.bank.principal;buyer.bank.arrears+=target.bank.arrears;buyer.bank.missed=Math.max(buyer.bank.missed,target.bank.missed);if(target.bank.principal)buyer.meta.due=Math.min(buyer.meta.due,target.meta.due);
 settleListing(listingKey(target),price);
 for(let p=0;p<6;p++){const a=buyer.ops.warehouse[p],b=target.ops.warehouse[p];a.qty+=b.qty;a.value+=b.value;expiryMerge(a,b.expiresDay||state.day+expiryLife(p),b.qty);b.qty=0;b.value=0;}
 for(const o of target.ops.orders)buyer.ops.orders.push({...o,id:nextCompanyOrder(buyer)});target.ops.orders=[];
 for(const m of [...target.machines]){buyer.ops.machines.push(m);buyer.account.owned.push(m.loc);removeRivalMachine(target,m.loc);}
 for(const k of ['quality','logistics'])buyer.tech[k]=Math.max(buyer.tech[k],target.tech[k]);for(const k of ['products','logistics','efficiency'])buyer.research[k]=Math.max(buyer.research[k],target.research[k]);for(let n=0;n<MAPS.length;n++)buyer.brand[n]=Math.max(buyer.brand[n],target.brand[n]);buyer.meta.capital+=target.meta.capital;
 transferExpansionAssets(buyer,target);target.account.cash=0;target.bank.principal=0;target.bank.arrears=0;target.bank.missed=0;target.meta.capital=0;target.meta.contract=null;target.policy.defeated=true;target.policy.mode='closed';target.policy.plan=null;target.meta.exitDay=state.day;state.enterprise.expansion.mergers++;
 if((state.offer?.buyer||'mono')===target.id)state.offer=null;companyLog(buyer,`${companyNameFor(target.id,0)} 기업 합병`,`${companyNameFor(target.id,1)}を企業合併`);return true;
}
const expansionCloseCompany=closeCompany;closeCompany=function(f,reason){if(expansionEnabled()&&!f.policy.defeated){const x=expansionFirm(f),e=state.enterprise.expansion;for(const [id,h] of Object.entries(x.holdings))if(!tradeStock(f,id,-h.qty)){const l=e.exchange.listings.find(l=>l.id===id);if(l)l.float+=h.qty;delete x.holdings[id];}settleListing(listingKey(f),0);f.account.cash+=x.plantValue*.5+x.kits.reduce((n,k)=>n+k.value*.5,0)+x.jobs.reduce((n,j)=>n+j.value*.5,0);for(const a of e.auctions)if(a.bidder===f.id){f.account.cash+=a.bid;a.bid=0;a.bidder=null;}e.firms[f.id]=expansionFreshFirm();}return expansionCloseCompany(f,reason);};
const expansionRevive=reviveCompany;reviveCompany=function(f){const ok=expansionRevive(f);if(ok&&expansionEnabled()){state.enterprise.expansion.firms[f.id]=expansionFreshFirm();if(state.enterprise.expansion.cityOpen)expandDistrictArrays();stampCompanyInventory(f);ensureListings();}return ok;};
function scheduleOutcome(kind,choice,loc){const e=state.enterprise.expansion;if(e.queue.length>=100)return; e.queue.push({id:e.next++,kind,choice,loc,due:state.day+3});}
const expansionResolve=resolveEvent;resolveEvent=function(index){const p=state.pending;if(expansionEnabled()&&p?.id.endsWith('-review')){const o=EVENTS.find(e=>e.id===p.id)?.options[index];if(!o||state.cash<o.fee&&o.fee>0)return;scheduleOutcome(p.id,index,p.loc);}return expansionResolve(index);};
function applyOutcomes(){const e=state.enterprise.expansion,due=e.queue.filter(q=>q.due<=state.day);e.queue=e.queue.filter(q=>q.due>state.day);for(const q of due){if(q.kind==='supply-review'&&q.choice===1)for(const o of state.enterprise.orders){o.remaining+=DAY_MS*2;o.duration+=DAY_MS*2;}if(q.kind==='regulation-review'&&q.choice===1){companyExpense(playerFirm(),25000);state.reputation=Math.max(0,state.reputation-3);}if(q.kind==='staff-review'&&q.choice===1)state.staff.restock=Math.max(0,state.staff.restock-1);if(q.kind==='finance-review')playerFirm().meta.credit=Math.max(0,playerFirm().meta.credit-(q.choice===0?2:8));const event=EVENTS.find(e=>e.id===q.kind);log(B(`${event.name[0]} · 후속 조치 반영`,`${event.name[1]}・後続措置を反映`));}}
function runAutomation(f){const a=expansionFirm(f).automation;if(!a.enabled||f.policy?.defeated)return;for(const m of f.machines){if(a.markup)for(const s of m.slots)s.price=Math.max(800,Math.min(4000,Math.round((s.stock?s.value/s.stock:procurementPrice(s.product,f.id==='player'?f.ops.supplier:f.meta.supplier))*(1+a.markup/100)/100)*100));if(a.repair&&m.condition<a.repair&&f.account.cash>=15000+a.reserve){companyExpense(f,15000);m.condition=100;}syncMachine(m);}if(a.transfer&&f.id==='player'&&f.account.cash>a.reserve)repayCompany(f,f.account.cash-a.reserve);for(let p=0;p<6;p++){if(!f.machines.some(m=>m.slots.some(s=>s.product===p)))continue;const stock=f.ops.warehouse[p].qty+f.ops.orders.filter(o=>o.product===p).reduce((n,o)=>n+o.qty,0)+expansionFirm(f).jobs.filter(j=>j.kind==='drink'&&j.product===p).reduce((n,j)=>n+j.qty,0);if(stock<a.min){const qty=Math.min(500,a.target-stock),supplier=f.id==='player'?f.ops.supplier:f.meta.supplier;if(qty>=SUPPLIERS[supplier].min&&f.account.cash-procurementPrice(p,supplier)*qty>=a.reserve){if(expansionFirm(f).plants.drink)produce(f,'drink',p,qty);else companyOrder(f,p,qty,supplier);}}}}
const expansionDispatch=dispatch;dispatch=function(type,loc,staff=false){if(staff&&expansionEnabled()){const map=expansionFirm(playerFirm()).automation[type+'Map'];if(map>=0&&LOCATIONS[loc].map!==map)return false;}return expansionDispatch(type,loc,staff);};
function expansionAI(){const e=state.enterprise.expansion;for(const f of rivalFirms()){const x=expansionFirm(f);if(f.policy.defeated||x.lastAI>=state.day)continue;x.lastAI=state.day;const competitors=allFirms().filter(v=>v.id!==f.id&&!v.policy?.defeated),pressure=competitors.map(v=>({id:v.id,count:v.machines.filter(m=>f.machines.some(own=>LOCATIONS[own.loc].map===LOCATIONS[m.loc].map)).length,price:v.machines.reduce((n,m)=>n+m.slots.reduce((sum,slot)=>sum+(v.id==='player'?campaignPrice(slot,LOCATIONS[m.loc].map):slot.price*v.meta.prices[LOCATIONS[m.loc].map]/1500),0)/4,0)/Math.max(1,v.machines.length)})).sort((a,b)=>b.count-a.count);x.memory.unshift({day:state.day,net:f.ops.lastProfit,target:pressure[0]?.id||'player',price:pressure[0]?.price||1500,products:PRODUCTS.map((_,p)=>(f.ops.market?.rows||[]).reduce((n,row)=>n+(row.products?.[p]?.revenue||0)-(row.products?.[p]?.cost||0),0))});x.memory=x.memory.slice(0,30);
  if(state.day%7===0){const losses=x.memory.slice(0,7).filter(m=>m.net<0).length;if(losses>=4){f.policy.plan=null;f.policy.mode='retreat';f.policy.until=state.day+7;f.meta.prices.fill(1650);companyLog(f,'최근 손실 분석 · 가격 회복과 원가 절감','直近の損失分析・価格回復と原価削減');}else if(pressure[0]?.count){const target=competitors.find(v=>v.id===pressure[0].id),map=target.machines.find(m=>f.machines.some(o=>LOCATIONS[o.loc].map===LOCATIONS[m.loc].map));if(map){f.policy.plan={mode:pressure[0].price<1400?'advertise':'price',target:LOCATIONS[map.loc].map,start:state.day+1,until:state.day+7};}}for(const m of f.machines){const sales=PRODUCTS.map((_,p)=>x.memory.slice(0,7).reduce((n,h)=>n+(h.products?.[p]||0),0)),best=sales.map((margin,p)=>({p,margin})).filter(s=>PRODUCTS[s.p].unlock<=f.research.products).sort((a,b)=>b.margin-a.margin)[0];if(best?.margin>0)for(const s of m.slots)if(!s.stock)s.product=best.p;syncMachine(m);}}
  if(state.day%14===0&&f.account.cash>1500000&&!x.plants.drink)buildFactory(f,'drink');if(x.plants.drink){x.automation.enabled=true;x.automation.reserve=150000;runAutomation(f);}if(state.day%30===0&&f.account.cash>1000000)tradeStock(f,'maker:1',20);
  for(const a of e.auctions)if(a.bidder!==f.id&&a.until-state.day<=2&&f.account.cash>Math.max(LOCATIONS[a.loc].cost,a.bid+10000)+200000)bidLand(f,a.id,Math.max(LOCATIONS[a.loc].cost,a.bid+10000));
  if(state.day%30===0){const target=rivalFirms().filter(v=>v.id!==f.id&&!v.policy.defeated&&(v.meta.distress>=2||v.ops.lastProfit<0)).sort((a,b)=>companyValue(a)-companyValue(b))[0];if(target)mergeCompanies(f,target);}
 }}
function expansionDay(){const e=state.enterprise.expansion;if(!expansionEnabled()||e.lastDay>=state.day)return;e.lastDay=state.day;applyOutcomes();for(const f of allFirms()){if(f.policy?.defeated)continue;expireInventory(f);const x=expansionFirm(f);if(x.plantValue)companyExpense(f,2000*(x.plants.drink+x.plants.machine));runAutomation(f);}settleAuctions();closeMarketDay();e.peakValue=Math.max(e.peakValue,companyValue(playerFirm()));}
const expansionFinish=finishBusiness;finishBusiness=function(){if(expansionEnabled()&&state.live?.elapsed>=DAY_MS&&state.live.day===state.day&&!state.live.settled)expansionDay();return expansionFinish();};
const expansionTurn=rivalTurn;rivalTurn=function(){expansionTurn();if(expansionEnabled())expansionAI();};
const expansionEnding=checkEnding;checkEnding=function(timeCheck=false){if(expansionEnabled()&&timeCheck&&!state.ended&&state.enterprise.expansion.lastAssessment<state.day){state.enterprise.expansion.lastAssessment=state.day;for(const f of allFirms())if(!f.policy?.defeated)creditorReview(f);const e=state.enterprise.expansion,x=expansionFirm(playerFirm());e.dominanceDays=x.plants.drink>0&&x.plants.machine>0&&x.produced>=3000&&state.machines.length>=10&&state.profit>0?e.dominanceDays+1:0;if(!e.debug&&!e.retired&&!state.enterprise.industry.sandbox&&!state.continued&&e.dominanceDays>=30&&!state.ended){state.ending={type:'success',reason:'industry',day:state.day,assets:assets()};if(!state.runWinRecorded){state.runWinRecorded=true;profile.clears=Math.min(20,profile.clears+1);saveProfile();}state.ended=true;state.live=null;livePaused=true;save();render();openModal('end');return true;}}return expansionEnding(timeCheck);};
function retireCompany(){if(!expansionEnabled()||state.ended)return false;state.enterprise.expansion.retired=true;state.ending={type:'time',reason:'retired',day:state.day,assets:assets()};state.ended=true;state.live=null;livePaused=true;save();render();openModal('end');return true;}
const expansionContinue=continueGame;continueGame=function(){if(expansionEnabled())state.enterprise.expansion.retired=false;return expansionContinue();};
const expansionAct=act;act=function(action){if(expansionEnabled()&&action==='buy'&&LOCATIONS[selected]?.auction){selectDesk('development');return;}if(expansionEnabled()&&action==='sell'&&expansionFirm(playerFirm()).pledges.includes(selected)){toast(B('담보 해제 후 매각 가능','担保解除後に売却可能'));return;}return expansionAct(action);};
const expansionLaunch=launchNew;launchNew=function(){if(MAPS.length>4){MAPS.splice(4);LOCATIONS.splice(24);}expansionLaunch();expansionInitialize();save();render();};
function validExpansion(x,s){
 const nn=v=>finite(v)&&v>=0,arr=(v,n)=>Array.isArray(v)&&v.length<=n,ids=['player','mono','atlas','nova'],day=v=>int(v,0,10000000),kinds=['supply-review','regulation-review','staff-review','finance-review'];
 if(!x||x.version!==1||s.saveVersion!==7||typeof x.cityOpen!=='boolean'||!day(x.lastDay)||!day(x.lastAssessment)||!int(x.next,1,1e12)||typeof x.retired!=='boolean'||typeof x.debug!=='boolean'||!day(x.dominanceDays)||!nn(x.peakValue)||!day(x.mergers)||!x.firms||!x.exchange||!nn(x.exchange.cash)||!day(x.exchange.lastDay)||!arr(x.exchange.listings,4)||!x.maker||!['cash','profit','totalProfit'].every(k=>nn(x.maker[k])))return false;
 const required=['player','mono',...(s.enterprise.industry?.companies||[]).map(c=>c.meta.id)];if(Object.keys(x.firms).some(id=>!required.includes(id))||required.some(id=>!x.firms[id]))return false;
 for(const id of required){const f=x.firms[id],a=f.automation;if(!f.plants||!['drink','machine'].every(k=>int(f.plants[k],0,12))||!nn(f.plantValue)||!arr(f.facilities,24)||!f.facilities.every(v=>['drink','machine'].includes(v.kind)&&nn(v.value))||f.facilities.reduce((n,v)=>n+v.value,0)!==f.plantValue||!['drink','machine'].every(k=>f.facilities.filter(v=>v.kind===k).length===f.plants[k])||!arr(f.jobs,24)||!arr(f.kits,1000)||!f.kits.every(k=>nn(k.value))||!f.jobs.every(j=>int(j.id,1,x.next-1)&&['drink','machine'].includes(j.kind)&&int(j.product,0,5)&&int(j.qty,1,500)&&nn(j.value)&&finite(j.remaining)&&j.remaining>0&&finite(j.duration)&&j.duration>0)||!f.holdings||Object.keys(f.holdings).length>4||!arr(f.memory,30)||!f.memory.every(m=>day(m.day)&&finite(m.net)&&ids.includes(m.target)&&nn(m.price)&&Array.isArray(m.products)&&m.products.length===6&&m.products.every(finite))||!['produced','waste','wasteValue','dividends','interestPaid'].every(k=>nn(f[k]))||!arr(f.pledges,30)||new Set(f.pledges).size!==f.pledges.length||!f.pledges.every(loc=>int(loc,0,x.cityOpen?29:23))||!day(f.foreclosure)||!day(f.lastAI)||!a||typeof a.enabled!=='boolean'||!int(a.min,0,500)||!int(a.target,a.min,1000)||!int(a.markup,0,300)||!int(a.repair,0,100)||![0,1].includes(a.transfer)||!nn(a.reserve)||!int(a.collectMap,-1,x.cityOpen?4:3)||!int(a.restockMap,-1,x.cityOpen?4:3))return false;}
 const metas=[s.enterprise.industry.primary,...s.enterprise.industry.companies.map(c=>c.meta)];
 if(!x.exchange.listings.every(l=>l.firm==='maker'||metas.some(m=>m.id===l.firm&&m.generation===l.generation)))return false;
 if(!x.exchange.listings.every(l=>typeof l.id==='string'&&['mono','atlas','nova','maker'].includes(l.firm)&&l.id===l.firm+':'+l.generation&&int(l.generation,1,1000000)&&nn(l.price)&&int(l.float,0,1000)&&nn(l.dividend)&&l.float+required.reduce((n,id)=>n+(x.firms[id].holdings[l.id]?.qty||0),0)===1000)||new Set(x.exchange.listings.map(l=>l.id)).size!==x.exchange.listings.length)return false;
 for(const f of Object.values(x.firms))for(const [id,h] of Object.entries(f.holdings))if(!x.exchange.listings.some(l=>l.id===id)||!int(h.qty,1,1000)||!nn(h.value))return false;
 if(!arr(x.queue,100)||!x.queue.every(q=>int(q.id,1,x.next-1)&&kinds.includes(q.kind)&&int(q.choice,0,1)&&int(q.loc,0,x.cityOpen?29:23)&&day(q.due))||new Set(x.queue.map(q=>q.id)).size!==x.queue.length||!arr(x.auctions,6)||!x.auctions.every(a=>x.cityOpen&&int(a.id,1,x.next-1)&&int(a.loc,24,29)&&day(a.until)&&nn(a.bid)&&(a.bidder===null?a.bid===0:required.includes(a.bidder)&&a.bid>0))||new Set(x.auctions.map(a=>a.loc)).size!==x.auctions.length)return false;
 const companies=[{machines:s.machines,warehouse:s.enterprise.warehouse,orders:s.enterprise.orders},{...s.enterprise.operations},...(s.enterprise.industry.companies||[]).map(c=>c.operations)];
 return companies.every(c=>[...c.warehouse,...c.orders,...c.machines.flatMap(m=>m.slots||[])].every(b=>b.expiresDay===undefined||day(b.expiresDay)))&&companies.every(c=>c.machines.every(m=>(m.bookCost===undefined||nn(m.bookCost))&&!x.auctions.some(a=>a.loc===m.loc)));
}
if(state.started)expansionInitialize();
