/* Expansion work surfaces stay inside the original console, with no extra clock. */
const expansionPanel=document.createElement('section');expansionPanel.id='expansion-panel';expansionPanel.hidden=true;deskNodes.expansion=expansionPanel;deskContent.append(expansionPanel);
DESK_TABS.splice(3,0,['manufacture',B('제조','製造')]);DESK_TABS.splice(6,0,['securities',B('증권','証券')]);DESK_TABS.push(['development',B('도시·계약','都市・契約')],['policies',B('운영 규정','運営規定')]);
const expansionDebugAccess=new URLSearchParams(location.search).get('debug')==='1';if(expansionDebugAccess)DESK_TABS.push(['simulation',B('시뮬레이터','シミュレータ')]);
let factoryKind='drink',factoryProduct=0,factoryQuantity=100;
function expansionButton(action,label,param='',off=false){return `<button class="small" data-expansion="${action}" data-arg="${esc(String(param))}" ${disabled(off||state.ended)}>${label}</button>`;}
function expansionSelect(id,values,current){return `<select id="${id}">${values.map(([v,label])=>`<option value="${v}" ${String(v)===String(current)?'selected':''}>${label}</option>`).join('')}</select>`;}
function expansionInput(label,key,value,min,max){return `<label>${label} <input type="number" data-policy="${key}" value="${value}" min="${min}" max="${max}" step="1"></label>`;}
function expansionFirmName(id){return id==='maker'?T('아쿠아 제조','アクア製造'):companyName(id);}
function renderExpansion(){
 if(!expansionEnabled()||expansionPanel.hidden)return;
 if(expansionPanel.contains(document.activeElement)&&document.activeElement.matches('input,select'))return;
 const f=playerFirm(),e=state.enterprise.expansion,x=expansionFirm(f),a=x.automation;let html='';
 if(deskTab==='manufacture'){
  html=`<h3>${T('생산 설비','生産設備')}</h3>`+enterpriseTable([T('공장','工場'),T('생산 라인','生産ライン'),T('투자','投資')],['drink','machine'].map(kind=>`<tr><td>${kind==='drink'?T('음료','飲料'):T('자판기','自販機')}</td><td>${x.plants[kind]}</td><td>${expansionButton('plant',T('설비 증설','設備増設')+' '+money(factoryCost(f,kind)),kind,x.plants[kind]>=3||state.cash<factoryCost(f,kind))} ${expansionButton('plant-sell',T('설비 매각','設備売却'),kind,!x.plants[kind]||x.jobs.some(j=>j.kind===kind))}</td></tr>`));
  html+=`<p>${T('라인당 동시 생산 1건 / 유지비 $2·일. 매각 회수율 50%. 음료 원가: 기준 원가 × 68% × 매입지수. 완성 시 창고 입고.','1ライン同時生産1件／維持費$2・日。売却回収率50%。飲料原価：基準原価×68%×仕入指数。完成時に倉庫入庫。')}</p><div class="expansion-form"><label>${T('생산품','生産品')} ${expansionSelect('factory-kind',[['drink',T('음료','飲料')],['machine',T('자판기 · 원가 $180','自販機・原価$180')]],factoryKind)}</label><label>${T('상품','商品')} ${expansionSelect('factory-product',PRODUCTS.map((p,k)=>[k,tr(p.name)]).filter(([k])=>PRODUCTS[k].unlock<=f.research.products),factoryProduct)}</label><label>${T('수량','数量')} <input id="factory-qty" type="number" min="1" max="500" value="${factoryQuantity}"></label>${expansionButton('produce',T('생산 지시','生産指示'))}</div>`;
  html+=enterpriseTable([T('진행 중','進行中'),T('수량 / 원가','数量／原価'),T('남은 일수','残り日数')],x.jobs.map(j=>`<tr><td>${j.kind==='drink'?tr(PRODUCTS[j.product].name):T('자판기','自販機')}</td><td>${j.qty} / ${money(j.value)}</td><td>${(j.remaining/DAY_MS).toFixed(2)}</td></tr>`));
  html+=`<h3>${T('완성 기기','完成機械')} ${x.kits.length}</h3><p>${T('설치비: 입지 기본 가격의 35%. 재고는 별도 보충. 신규 도시 입지는 입찰로 취득.','設置費：立地基準価格の35%。在庫は別途補充。新都市の立地は入札で取得。')}</p>`+enterpriseTable([T('입지','立地'),T('설치','設置')],LOCATIONS.filter(l=>!l.auction&&!machine(l.id)&&!rivalLocations().includes(l.id)).map(l=>`<tr><td>${tr(l.short)}</td><td>${expansionButton('install',money(Math.round(l.cost*.35)),l.id,!x.kits.length||!canBuild(l.id)||state.cash<Math.round(l.cost*.35))}</td></tr>`));
  html+=expansionButton('production-liquidate',T('생산 취소·완성 기기 청산 · 원가 50%','生産取消・完成機械清算・原価50%'),'',!x.jobs.length&&!x.kits.length)+row(T('누적 음료 생산','累計飲料生産'),x.produced)+`<p>${T('제조사 지분 투자는 증권 메뉴의 아쿠아 제조에서 거래합니다. 공급 매출에서 발생한 이익이 배당 재원입니다.','製造会社への出資は証券メニューのアクア製造で取引します。供給売上の利益が配当の原資です。')}</p>`;
 }
 if(deskTab==='securities'){
  html=`<h3>${T('주식시장','株式市場')}</h3><p>${T('1사 1,000주 / 매수 +2%·매도 -2% / 일일 종가 갱신 / 30일마다 잉여 이익 배당. 재진입 회사는 새 주식 발행.','1社1,000株／買付+2%・売却−2%／日次終値更新／30日ごとに余剰利益配当。再参入会社は新株発行。')}</p>`+enterpriseTable([T('종목','銘柄'),T('가격 / 배당','株価／配当'),T('보유 / 유통','保有／流通'),T('거래','取引')],e.exchange.listings.map(l=>`<tr><td>${expansionFirmName(l.firm)}<br>${T('발행 기수','発行期')} ${l.generation}</td><td>${money(l.price)} / ${money(l.dividend)}</td><td>${x.holdings[l.id]?.qty||0} / ${l.float}</td><td>${expansionButton('stock-buy',T('10주 매수','10株購入'),l.id,l.float<10||state.cash<10*Math.round(l.price*1.02))}${expansionButton('stock-sell',T('10주 매도','10株売却'),l.id,(x.holdings[l.id]?.qty||0)<10)}${expansionButton('stock-all',T('전량 매도','全株売却'),l.id,!x.holdings[l.id])}</td></tr>`))+row(T('누적 수령 배당','累計受取配当'),money(x.dividends));
  html+=`<p>${T('기업 인수 시 기존 주주는 인수 대금을 보유 비율로 수령. 파산 철수 시 해당 주식은 소멸합니다.','企業買収時、既存株主は持株比率に応じて買収代金を受領。破産撤退時には該当株式が消滅します。')}</p>`;
 }
 if(deskTab==='development'){
  html=`<h3>${T('도시 개발','都市開発')}</h3>${e.cityOpen?row(T('항만 신도시','港湾新都市'),T('개방 · 6개 신규 입지','開放・6つの新規立地')):`<p>${T('개발 분담금 $750 / 6개 입지 개방 / 경쟁사 공동 입찰.','開発負担金$750／6立地開放／競合会社と共同入札。')}</p>${expansionButton('city',T('신도시 개발 참여 $750','新都市開発に参加 $750'),'',state.cash<750000)}`}`;
  html+=enterpriseTable([T('입지 / 마감','立地／締切'),T('최고 입찰','最高入札'),T('입찰','入札')],e.auctions.map(auction=>{const cost=Math.max(LOCATIONS[auction.loc].cost,auction.bid+10000);return `<tr><td>${tr(LOCATIONS[auction.loc].short)}<br>DAY ${auction.until}</td><td>${auction.bidder?companyName(auction.bidder)+' '+money(auction.bid):'—'}</td><td>${expansionButton('bid',money(cost),auction.id,state.cash+(auction.bidder==='player'?auction.bid:0)<cost)}</td></tr>`;}));
  html+=`<p>${chainEnabled()?T('입찰액 전액 예치. 상위 입찰 시 환급. 낙찰은 입지 계약이며 기기 조달·설치는 별도.','入札額全額を預託。上位入札時に返金。落札は立地契約。機械調達・設置は別途。'):T('입찰액 전액 예치. 상위 입찰 발생 시 즉시 환급. 낙찰액은 기기와 입지 취득 원가. 신규 기기는 다음 영업일부터 판매.','入札額全額を預託。上位入札時に即時返金。落札額は機械・立地取得原価。新規機械は翌営業日から販売。')}</p><h3>${T('임대인 협상','貸主交渉')}</h3>`+enterpriseTable([T('입지','立地'),T('계약 / 일 임대료','契約／日額賃料'),T('협상','交渉')],state.machines.map(m=>`<tr><td>${tr(LOCATIONS[m.loc].short)}</td><td>${m.lease?'DAY '+m.lease.until+' / '+money(m.lease.rate):T('변동 임대료','変動賃料')}</td><td>${[30,60].map(term=>{const c=leaseTerms(f,m,term);return expansionButton('lease',`${term}${T('일','日')} ${money(c.fee)} / ${money(c.rate)}${T('·일','・日')}`,m.loc+':'+term,m.lease?.until>state.day+5||state.cash<c.fee);}).join('')}${expansionButton('lease-end',T('해지','解約')+' '+money(m.lease?.until>=state.day?(m.lease.penalty||m.lease.rate*3):0),m.loc,!m.lease)}</td></tr>`));
  html+=`<p>${T('만료 5일 전 갱신 가능. 30/60일 계약의 위약금은 기본 임대료 3/8일분. 평판·기존 거래·임대인별 조건 반영.','満了5日前から更新可能。30／60日契約の違約金は基準賃料3／8日分。評判・取引実績・貸主条件を反映。')}</p>`;
 }
 if(deskTab==='policies'){
  html=`<h3>${T('자동 운영','自動運営')}</h3><label><input type="checkbox" data-policy="enabled" ${a.enabled?'checked':''}> ${T('운영 규정 적용','運営規定を適用')}</label><div class="expansion-form">${expansionInput(T('발주 기준 수량','発注基準数量'),'min',a.min,0,500)}${expansionInput(T('목표 재고','目標在庫'),'target',a.target,a.min,1000)}${expansionInput(T('원가 대비 가산율 % · 0=수동','原価加算率%・0=手動'),'markup',a.markup,0,300)}${expansionInput(T('정비 기준 상태 · 0=수동','整備基準状態・0=手動'),'repair',a.repair,0,100)}<label>${T('현금 유보액 $','現金留保額 $')} <input type="number" data-policy="reserveUSD" min="0" max="1000000" value="${a.reserve/1000}"></label><label><input type="checkbox" data-policy="transfer" ${a.transfer?'checked':''}> ${T('유보액 초과 현금 자동 상환','留保額を超える現金を自動返済')}</label>${['collect','restock'].map(type=>`<label>${type==='collect'?T('회수 직원 담당','回収スタッフ担当'):T('보충 직원 담당','補充スタッフ担当')} ${expansionSelect('policy-'+type,[[-1,T('전체 지역','全地域')],...MAPS.map(m=>[m.id,tr(m.name)])],a[type+'Map'])}</label>`).join('')}</div><p>${T('매일 마감 시 적용. 재고 기준은 창고·운송·생산 중 수량 합계. 제조 라인이 있으면 자체 생산 우선. 매출 회수는 직원의 실제 이동 시간 적용.','毎日決算時に適用。在庫基準は倉庫・輸送中・生産中の合計。製造ラインがあれば自社生産優先。売上回収はスタッフの実際の移動時間を適用。')}</p>`;
  html+=`<h3>${T('재고 기한·자금 회수','在庫期限・資金回収')}</h3><p>${T('아이스크림 8일 / 핫 음료 12일 / 기타 30일. 동일 상품 혼합 시 빠른 기한 적용. 폐기는 장부 원가 손실.','アイス8日／ホット12日／その他30日。同一商品混合時は早い期限を適用。廃棄は帳簿原価の損失。')}</p>`+enterpriseTable([T('상품','商品'),T('창고 / 기한','倉庫／期限'),T('회수','回収')],f.ops.warehouse.map((w,p)=>`<tr><td>${tr(PRODUCTS[p].name)}</td><td>${w.qty} / ${w.qty?'DAY '+w.expiresDay:'—'}</td><td>${expansionButton('liquidate',T('청산','清算')+' '+money(w.value*.5),p,!w.qty)}</td></tr>`))+row(T('누적 폐기 / 손실','累計廃棄／損失'),x.waste+' / '+money(x.wasteValue));
  html+=`<h3>${T('담보·채권자','担保・債権者')}</h3>`+row(T('담보 실행 예정','担保処分予定'),x.foreclosure?'DAY '+x.foreclosure:'—')+enterpriseTable([T('입지','立地'),T('담보','担保')],f.machines.map(m=>`<tr><td>${tr(LOCATIONS[m.loc].short)}</td><td>${x.pledges.includes(m.loc)?T('대출 담보 설정','融資担保設定'):expansionButton('collateral',T('담보 대출','担保融資')+' '+money(Math.min(companyBorrowRoom(f),Math.round(equipment(m)*.4))),m.loc,companyBorrowRoom(f)<=0)}</td></tr>`));
  html+=`<p>${T('연체 3일 후 담보 실행 예고, 3일 유예. 연체 해소 시 취소. 최후 1대는 보전하며 회복 여력 소진 시 파산 심사. 차입 전액 상환 시 담보 해제.','延滞3日後に担保処分予告、3日猶予。延滞解消で取消。最後の1台は保全し回復余力枯渇時に破産審査。借入全額返済で担保解除。')}</p><h3>${T('예약된 후속 조치','予定された後続措置')}</h3>`+enterpriseTable([T('예정일','予定日'),T('사건','事件')],e.queue.map(q=>`<tr><td>DAY ${q.due}</td><td>${tr(EVENTS.find(ev=>ev.id===q.kind).name)}</td></tr>`));
  html+=expansionButton('retire',T('사업 종료 검토','事業終了を検討'));
 }
 if(deskTab==='simulation'&&expansionDebugAccess){html=`<h3>${T('개발 시뮬레이터','開発シミュレータ')}</h3><p>${T('사용 시 이 저장은 시험 실행으로 표시됩니다. 자동 결산도 기존 영업 시계를 사용하며 필수 사건 선택은 건너뛰지 않습니다.','使用時、このセーブを試験実行として記録します。自動決算も既存営業時計を使用し、必須事件の選択は省略しません。')}</p>${['step','cash','event','inspect'].map(k=>expansionButton('debug',({step:T('하루 진행','一日進行'),cash:T('$10,000 투입','$10,000投入'),event:T('규제 사건','規制事件'),inspect:T('저장 검사','セーブ検査')})[k],k)).join('')}`+enterpriseTable([T('회사','会社'),T('현금 / 부채','現金／負債'),T('당기 이익','当期利益')],allFirms().map(f=>`<tr><td>${companyName(f)}</td><td>${money(f.account.cash)} / ${money(f.bank.principal)}</td><td>${money(f.id==='player'?state.profit:f.ops.lastProfit)}</td></tr>`));}
 patchPanel(expansionPanel,html);
}
const expansionUpdateDesk=updateDesk;updateDesk=function(){expansionUpdateDesk();renderExpansion();};
const expansionRender=renderWorld;renderWorld=function(){expansionRender();renderExpansion();};
const expansionOverview=renderEnterprise;renderEnterprise=function(force=true){expansionOverview(force);if(!expansionEnabled()||enterpriseTab!=='overview')return;const body=$('enterprise').querySelector('.enterprise-body');if(!body)return;let host=$('industrial-goal');if(!host){host=document.createElement('div');host.id='industrial-goal';body.append(host);}patchPanel(host,`<h3>${T('산업 지배 목표','産業支配目標')}</h3><p>${T('음료·기기 공장 모두 보유, 누적 음료 3,000개 생산, 기기 10대 이상, 흑자 30일 유지. 자유 경영에서는 실적만 기록.','飲料・機械工場を両方保有、累計飲料3,000本生産、機械10台以上、黒字30日維持。自由経営では実績のみ記録。')}</p>${row(T('조건 연속 유지','条件の連続維持'),state.enterprise.expansion.dominanceDays+'/30')}`);};
const expansionPaintDistrict=paintDistrict;paintDistrict=function(){expansionPaintDistrict();if(selectedMap!==4)return;const layer=$('district-scenery');if(!layer)return;layer.innerHTML=`<rect width="800" height="340" fill="${PALETTES[sceneSeason()].land}"/><path d="M0 0H800V66H0Z" fill="${PALETTES[sceneSeason()].water}"/><path d="M0 180H800M280 66V340M510 66V340" stroke="#dddcd3" stroke-width="28"/><path d="M0 67H800" stroke="#617780" stroke-width="8"/>${[70,165,360,570,675].map((x,i)=>`<rect x="${x}" y="${i%2?240:100}" width="72" height="45" fill="#9badb3" stroke="#576c77"/><path d="M${x+6} ${i%2?253:113}h60" stroke="#dedfce" stroke-width="10"/>`).join('')}<path d="M365 25h130l-17 24h-95z" fill="#5b788c"/><path d="M610 65V16h55M610 16l42 49" stroke="#536973" stroke-width="5" fill="none"/>`;};
const expansionDraw=drawModal;drawModal=function(){expansionDraw();if(!expansionEnabled())return;
 if(modalView==='retirement'){$('modal-body').innerHTML=`<h2>${T('사업 종료','事業終了')}</h2>${row(T('현재 순자산','現在の純資産'),money(assets()))}<p>${T('현재 실적으로 경영을 마감합니다. 결과 화면에서 자유 경영을 이어갈 수 있습니다.','現在の実績で経営を終了します。結果画面から自由経営を続けられます。')}</p>`+buttons(closeButton()+expansionButton('retire-confirm',T('사업 종료 확정','事業終了を確定')));}
 if(modalView==='end'){const e=state.enterprise.expansion,x=expansionFirm(playerFirm());$('modal-body').insertAdjacentHTML('beforeend',`<h3>${state.ending?.reason==='industry'?T('산업 지배 달성','産業支配達成'):state.ending?.reason==='retired'?T('자진 철수','自主撤退'):T('최종 운영 통계','最終運営統計')}</h3>${row(T('최고 기업가치','最高企業価値'),money(e.peakValue))}${row(T('제조 / 폐기 수량','製造／廃棄数量'),x.produced+' / '+x.waste)}${row(T('폐기 원가 / 수령 배당','廃棄原価／受取配当'),money(x.wasteValue)+' / '+money(x.dividends))}${row(T('누적 이자 비용','累計利息費用'),money(x.interestPaid))}${row(T('보유 기기 / 공장 라인','保有機械／工場ライン'),state.machines.length+' / '+(x.plants.drink+x.plants.machine))}${row(T('NPC 기업 합병','NPC企業合併'),e.mergers)}${e.debug?`<p>${T('시험 실행','試験実行')}</p>`:''}`);}
};
document.addEventListener('change',event=>{
 if(!expansionEnabled()||state.ended)return;const el=event.target,x=expansionFirm(playerFirm()),a=x.automation,k=el.dataset.policy;
 if(k){if(k==='enabled')a.enabled=el.checked;else if(k==='transfer')a.transfer=el.checked?1:0;else if(k==='reserveUSD'){const n=Number(el.value);if(finite(n)&&n>=0&&n<=1000000)a.reserve=Math.round(n*1000);}else{const n=Number(el.value),limits={min:[0,500],target:[a.min,1000],markup:[0,300],repair:[0,100]};if(limits[k]&&int(n,...limits[k]))a[k]=n;a.target=Math.max(a.target,a.min);}if(a.enabled)state.enterprise.autoOrder=false;}
 if(el.id==='policy-collect'||el.id==='policy-restock'){const map=Number(el.value);if(int(map,-1,MAPS.length-1))a[el.id==='policy-collect'?'collectMap':'restockMap']=map;}
 if(el.id==='factory-kind'){factoryKind=el.value;factoryQuantity=factoryKind==='machine'?1:100;}if(el.id==='factory-product')factoryProduct=Number(el.value);if(el.id==='factory-qty')factoryQuantity=Number(el.value);save();el.blur();renderExpansion();
});
document.addEventListener('click',event=>{const b=event.target.closest('[data-expansion]');if(!b||b.disabled||!expansionEnabled()||state.ended)return;const action=b.dataset.expansion,arg=b.dataset.arg,f=playerFirm(),e=state.enterprise.expansion;let ok=false;
 if(action==='plant')ok=buildFactory(f,arg);if(action==='plant-sell')ok=liquidatePlant(f,arg);if(action==='produce')ok=produce(f,factoryKind,factoryProduct,factoryQuantity);if(action==='install')ok=installKit(f,Number(arg));if(action==='production-liquidate')ok=liquidateProduction(f);
 if(action.startsWith('stock-'))ok=tradeStock(f,arg,action==='stock-buy'?10:action==='stock-sell'?-10:-(expansionFirm(f).holdings[arg]?.qty||0));if(action==='city')ok=openNewCity();if(action==='bid'){const a=e.auctions.find(a=>a.id===Number(arg));if(a)ok=bidLand(f,a.id,Math.max(LOCATIONS[a.loc].cost,a.bid+10000));}
 if(action==='lease'){const [loc,term]=arg.split(':').map(Number),m=machine(loc);if(m)ok=negotiateLease(f,m,term);}if(action==='lease-end'&&machine(Number(arg)))ok=endLease(f,machine(Number(arg)));if(action==='liquidate')ok=liquidateWarehouse(f,Number(arg));if(action==='collateral')ok=collateralLoan(f,Number(arg));
 if(action==='retire'){openModal('retirement');return;}if(action==='retire-confirm'){retireCompany();return;}
 if(action==='debug'&&expansionDebugAccess){e.debug=true;state.enterprise.industry.sandbox=true;if(arg==='cash')state.cash+=10000000;if(arg==='step'&&!state.pending){if(!state.live)startBusiness();advanceBusiness(DAY_MS);}if(arg==='event'&&!state.pending&&state.machines.length){state.pending={id:'regulation-review',loc:state.machines[0].loc};openModal('event');}if(arg==='inspect')toast(valid(state)?B('저장 검사 통과','セーブ検査成功'):B('저장 검사 실패','セーブ検査失敗'));ok=true;}
 if(!ok)toast(B('조건 불충족 · 자금·용량·계약 확인','条件未達・資金・容量・契約を確認'));save();render();
});
document.addEventListener('keydown',event=>{if(event.altKey&&!modalView&&['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const n=DESK_TABS.findIndex(t=>t[0]===deskTab),next=(n+(event.key==='ArrowDown'?1:-1)+DESK_TABS.length)%DESK_TABS.length;selectDesk(DESK_TABS[next][0]);deskNav.querySelector(`[data-desk="${deskTab}"]`)?.focus();}});
renderExpansion();
