/* Management panels for the shared company simulation. */
function companyStatus(f){return f.policy.defeated?T('철수','撤退'):tr(RIVAL_MODES[f.policy.mode]);}
function companyMarketRows(){return rivalFirms().map(f=>{const report=state.enterprise.industry.researchReports.find(r=>r.id===f.id),grade=report?({closed:T('철수','撤退'),weak:T('취약','脆弱'),stable:T('안정','安定'),watch:T('주의','注意')})[report.grade]:'—',trend=report?({up:T('증가','増加'),down:T('감소','減少'),flat:T('보합','横ばい'),unknown:T('자료 부족','資料不足')})[report.trend]:'';
 return `<tr><td>${companyName(f)}<br>${T('사업 기수','事業期')} ${f.meta.generation}</td><td>${f.machines.length}</td><td>${companyStatus(f)}${f.policy.plan?`<br>DAY ${f.policy.plan.start} ${tr(MAPS[f.policy.plan.target].name)} · ${tr(RIVAL_MODES[f.policy.plan.mode])}`:''}</td><td>${grade}${report?` · DAY ${report.day}<br>${T('매출 추세','売上推移')} ${trend}`:''}</td><td><button class="small" data-company-research="${f.id}" ${disabled(state.cash<20000||state.ended)}>${T('조사 $20','調査 $20')}</button><button class="small" data-company-buyout="${f.id}" ${disabled(f.policy.defeated||state.ended)}>${T('기업 인수','企業買収')}</button></td></tr>`;});}
const industryOldRivalPanel=renderRivalPanel;
renderRivalPanel=function(){if(!industryEnabled())return industryOldRivalPanel();const o=state.offer,f=o&&rivalById(o.buyer||'mono');patchPanel($('rival-panel'),`<div class="panel-head"><h2>${T('거래 제안','取引提案')}</h2></div><div class="hq-body">${o&&f?`<p>${companyName(f)} · ${tr(LOCATIONS[o.loc].short)} · ${money(o.price)} · DAY ${o.deadline}</p><button class="full" id="accept-offer" ${disabled(!saleAvailable())}>${T('매입 제안 검토','買収提案を検討')}</button>`:`<p>${T('접수된 제안 없음','受領した提案なし')}</p>`}</div>`);};
const industryOldCompetition=competitionBody;
competitionBody=function(){if(!industryEnabled())return industryOldCompetition();return `<h3>${T('경쟁 회사','競合会社')}</h3>`+enterpriseTable([T('회사','会社'),T('기기','機械'),T('영업 동향','営業動向'),T('조사 보고','調査報告'),T('거래','取引')],companyMarketRows())+`<h3>${T('상권별 대응','商圏別の対策')}</h3>`+enterpriseTable([T('상권','商圏'),T('자사 / 경쟁 기기','自社／競合機械'),T('대응 전략','対抗戦略')],MAPS.map((map,k)=>{const c=activeCampaign(k);return `<tr><td>${tr(map.name)}</td><td>${state.machines.filter(m=>LOCATIONS[m.loc].map===k).length} / ${rivalLocations().filter(loc=>LOCATIONS[loc].map===k).length}</td><td>${c?`${tr(CAMPAIGNS[c.kind].name)} · DAY ${c.until}`:Object.entries(CAMPAIGNS).map(([id,v])=>`<button class="small" data-campaign="${id}" data-campaign-map="${k}" ${disabled(state.ended||state.cash<v.cost||!state.machines.some(m=>LOCATIONS[m.loc].map===k))}>${tr(v.name)} ${money(v.cost)}</button>`).join(' ')}</td></tr>`;}))+`<h3>${T('경쟁 전황','競争の推移')}</h3>`+rivalFirms().flatMap(f=>f.policy.history).sort((a,b)=>b.day-a.day).slice(0,15).map(h=>`<p>DAY ${h.day} · ${esc(tr(h.text))}</p>`).join('');};
function renderCompanyBank(){if(!industryEnabled())return;const f=playerFirm(),m=f.meta;patchPanel($('bank-panel'),`<div class="panel-head"><h2>${T('은행 · 신용','銀行・信用')}</h2><span>${T('신용','信用')} ${m.credit}/100</span></div><div class="hq-body">${row(T('기업가치 / 순자산','企業価値／純資産'),money(companyValue(f))+' / '+money(companyEquity(f)))}${row(T('차입 원금 / 미납 이자','借入元金／未払利息'),money(f.bank.principal)+' / '+money(f.bank.arrears))}${row(T('일 이율 / 만기','日利／満期'),(companyRate(f)*100).toFixed(2)+'% / DAY '+m.due)}${row(T('추가 대출 가능액','追加融資可能額'),money(companyBorrowRoom(f)))}${row(T('자금 경색','資金難'),m.distress+T('일','日'))}<p>${T('만기 원금 자동 상환. 만기 10일 전부터 신용 45 이상·이자 미납 없음이면 1.5% 수수료로 60일 연장. 자금난 7일 이상·회복 수단 소진 시 파산.','満期に元金を自動返済。満期10日前から信用45以上・利息未払いなしで、1.5%の手数料により60日延長。資金難7日以上かつ回復手段枯渇で破産。')}</p><div class="world-buttons"><button data-bank="borrow" ${disabled(state.ended||companyBorrowRoom(f)<=0)}>${T('최대 $250 대출','最大$250借入')}</button><button data-bank="repay" ${disabled(state.ended||state.cash<=0)}> ${T('$100 상환','$100返済')}</button><button data-bank="repayAll" ${disabled(state.ended||state.cash<=0)}>${T('가능한 만큼 상환','できるだけ返済')}</button><button data-bank="renew" ${disabled(state.ended||!f.bank.principal||m.credit<45||f.bank.arrears>0||m.due-state.day>10||state.cash<Math.round(f.bank.principal*.015))}>${T('만기 연장','満期延長')}</button></div></div>`);}
const industryOldRenderWorld=renderWorld;
renderWorld=function(){industryOldRenderWorld();if(!industryEnabled())return;renderCompanyBank();document.querySelectorAll('.map-pin').forEach(el=>{const f=rivalOwner(Number(el.dataset.select));if(f){const label=companyName(f)+' · '+tr(LOCATIONS[Number(el.dataset.select)].short);if(el.textContent!==label)el.textContent=label;el.style.borderColor=({mono:'#76577a',atlas:'#8c651b',nova:'#235c89'})[f.id];}});};
const industryOldModal=drawModal;
drawModal=function(){industryOldModal();if(!industryEnabled())return;const i=state.enterprise.industry;
 if(modalView==='company-buyout'){const q=i.buyout,f=q&&rivalById(q.id);if(!q||!f)return;const error=companyBuyoutError();$('modal-body').insertAdjacentHTML('beforeend',`<h2>${companyName(f)} · ${T('기업 인수','企業買収')}</h2>${row(T('주주 지급액','株主への支払額'),money(q.price))}${row(T('승계 현금','承継現金'),money(f.account.cash))}${row(T('승계 차입 원금 / 이자','承継借入元金／利息'),money(f.bank.principal)+' / '+money(f.bank.arrears))}${row(T('운영 기기','稼働機械'),f.machines.length)}<p>${T('기기·창고·운송 재고·기술·브랜드·부채·입지 계약 승계. 대상 공급 계약 중도 종료 시 $5 별도. 유효 기한: 당일.','機械・倉庫・輸送中在庫・技術・ブランド・負債・立地契約を承継。対象の仕入契約中途終了は別途$5。有効期限：本日。')}</p><p role="status">${error}</p><button class="primary full" id="company-buyout-confirm" ${disabled(!!error)}>${T('계약 체결','契約を締結')}</button>`+buttons(closeButton()));}
 if(modalView==='end'){$('modal-body').insertAdjacentHTML('beforeend',`<h3>${T('경영 기록','経営記録')}</h3>${row(T('기업가치','企業価値'),money(companyValue(playerFirm())))}${row(T('누적 매출','累計売上'),money(i.totalRevenue))}${row(T('최고 판매 점유율','最高販売シェア'),Math.round(i.maxShare*100)+'%')}${row(T('기업 인수 / 경쟁사 철수','企業買収／競合撤退'),i.acquisitions+' / '+i.exits)}`);}
};
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.companyResearch)commissionResearch(b.dataset.companyResearch);if(b.dataset.companyBuyout)quoteCompany(b.dataset.companyBuyout);if(b.id==='company-buyout-confirm'&&!completeCompanyBuyout())drawModal();});

const industryManage=renderManage;
renderManage=function(){industryManage();if(!industryEnabled())return;const m=machine(selected);if(!m)return;let host=$('lease-controls');if(!host){host=document.createElement('div');host.id='lease-controls';$('manage').append(host);}const active=m.lease&&m.lease.until>=state.day,fee=Math.round(LOCATIONS[m.loc].rent*(1-state.research.efficiency*.1)*inflationFactor())*3;patchPanel(host,`<h3>${T('입지 계약','立地契約')}</h3>${active?row('DAY '+m.lease.until+T('까지','まで'),money(m.lease.rate)+T('/일','/日')):`<p>${T('계약금: 기본 임대료 3일분 / 30일간 임대료 15% 할인·고정','契約金：基本賃料3日分／30日間賃料15%割引・固定')}</p><button class="full" id="sign-lease" ${disabled(state.ended||state.cash<fee)}>${T('30일 계약','30日契約')} · ${money(fee)}</button>`}`);};
const industryEnterprise=renderEnterprise;
renderEnterprise=function(force=true){industryEnterprise(force);if(!industryEnabled())return;const body=$('enterprise').querySelector('.enterprise-body');if(!body)return;
 if(enterpriseTab==='supply'){let host=$('supply-contract');if(!host){host=document.createElement('div');host.id='supply-contract';body.prepend(host);}const c=playerFirm().meta.contract,active=c&&c.until>=state.day;patchPanel(host,`<h3>${T('공급 단가 고정 계약','仕入単価固定契約')}</h3>${active?`<p>${tr(SUPPLIERS[c.supplier].name)} · DAY ${c.until}${T('까지','まで')} · ${T('타 공급처 발주 불가','他の仕入先への発注不可')}</p>`+enterpriseTable([T('상품','商品'),T('고정 단가','固定単価')],PRODUCTS.map((p,k)=>`<tr><td>${tr(p.name)}</td><td>${money(c.prices[k])}</td></tr>`))+`<button id="end-supply" ${disabled(state.ended||state.cash<5000)}>${T('중도 해지 $5','中途解約 $5')}</button>`:`<p>${T('30일 단가 고정 / 계약금 $15 / 중도 해지 $5 / 계약 공급처만 발주. 배송 지연 가능.','30日間単価固定／契約金$15／中途解約$5／契約先のみ発注。配送遅延の可能性あり。')}</p><button id="sign-supply" ${disabled(state.ended||state.cash<15000)}>${T('선택 공급처와 계약','選択した仕入先と契約')}</button>`}`);if(active){const select=$('supplier');if(select){select.value=String(c.supplier);select.disabled=true;}}}
 if(enterpriseTab==='market'){patchPanel(body,`<h3>${T('상권별 경쟁 가격','商圏別の競合価格')}</h3>`+enterpriseTable([T('상권','商圏'),...rivalFirms().map(companyName),T('자사 광고','自社広告')],MAPS.map((map,k)=>`<tr><td>${tr(map.name)}</td>${rivalFirms().map(f=>`<td>${f.machines.some(m=>LOCATIONS[m.loc].map===k)?money(f.meta.prices[k]):'—'}</td>`).join('')}<td><button class="small" data-enterprise="ad" data-param="${k}" ${disabled(state.ended||state.cash<25000||state.enterprise.ads[k]>0)}>${state.enterprise.ads[k]?state.enterprise.ads[k]+T('일 진행 중','日実施中'):T('5일 광고 $25','5日広告 $25')}</button></td></tr>`))+`<p>${T('가격은 기본 음료 기준. 상품별 판매가는 각 회사의 상품 구성과 할인에 따라 달라집니다.','価格は基本飲料の基準。商品の販売価格は各社の商品構成と値下げにより異なります。')}</p>`);}
 if(enterpriseTab==='overview'){const i=state.enterprise.industry;patchPanel(body,`<h3>${T('경영 목표','経営目標')}</h3>${row(T('기업가치','企業価値'),money(companyValue(playerFirm())))}${row(T('판매 점유율 60%·흑자 연속 유지','販売シェア60%・連続黒字'),i.shareDays+'/60 '+T('일','日'))}${row(T('최고 판매 점유율','最高販売シェア'),Math.round(i.maxShare*100)+'%')}${row(T('누적 매출','累計売上'),money(i.totalRevenue))}${row(T('인수 / 경쟁사 철수','買収／競合撤退'),i.acquisitions+' / '+i.exits)}<p>${i.sandbox||state.continued?T('자유 경영 · 기간 평가 없음','自由経営・期間評価なし'):T(`DAY ${state.duration} 실적 평가. 판매 점유율 60%·흑자 60일 유지 또는 기기 8대·기업가치 $10,000·흑자로 성장 목표 달성.`,`DAY ${state.duration}に業績評価。販売シェア60%・黒字60日維持、または機械8台・企業価値$10,000・黒字で成長目標達成。`)}</p><p>${T('기업가치 = 순자산 + 최근 평균 일 이익의 양수 부분 × 30 + 브랜드 가치.','企業価値＝純資産＋最近の平均日次利益の正の部分×30＋ブランド価値。')}</p>`);}
};
const businessModal=drawModal;
drawModal=function(){businessModal();if(modalView==='newrun'){const select=$('run-duration');if(select&&!select.querySelector('[value="36500"]'))select.insertAdjacentHTML('beforeend',`<option value="36500" ${chosenDuration===36500?'selected':''}>${T('자유 경영 · 기간 제한 없음','自由経営・期間制限なし')}</option>`);}if(!industryEnabled())return;
 if(modalView==='event'){$('modal-body').querySelectorAll('[data-close]').forEach(el=>el.remove());const help=$('modal-body').querySelector('.helper');if(help)help.textContent=T('선택 대기 · 영업 정지','選択待ち・営業停止');}
};
const industryLaunchUI=launchNew;
launchNew=function(){industryLaunchUI();if(industryEnabled()){state.enterprise.industry.sandbox=chosenDuration===36500;save();}};
const industryUpdate=updateDesk;
updateDesk=function(){industryUpdate();if(!industryEnabled())return;document.querySelector('.goal').hidden=true;let notice=$('company-notice');if(!notice){notice=document.createElement('div');notice.id='company-notice';officeRegister.prepend(notice);}const c=state.complaints.at(-1);patchPanel(notice,c?`<button class="small" data-desk="alerts">${T('미처리 민원','未対応の相談')} ${state.complaints.length} · ${tr(LOCATIONS[c.loc].short)} · DAY ${c.deadline}</button>`:'');};
document.addEventListener('click',event=>{const id=event.target.closest('button')?.id;if(!industryEnabled()||state.ended)return;let ok=false;if(id==='sign-supply')ok=companySignSupply(playerFirm(),state.enterprise.supplier);if(id==='end-supply')ok=companyEndSupply(playerFirm());if(id==='sign-lease'&&machine(selected))ok=companySignLease(playerFirm(),machine(selected));if(ok){save();render();}});
