/* Flat ledgers and business exceptions; control elements are patched, never replaced per tick. */
DESK_TABS.push(['management-migrate',B('장기 경영 전환','長期経営へ移行'),()=>refEnabled()&&!mgEnabled()]);
function mgButton(action,label,arg='',off=false){return `<button data-mg="${action}" data-arg="${esc(String(arg))}" ${disabled(off||state.ended)}>${label}</button>`;}
function mgReason(key){return tr(({manager:B('관리자 배치 필요','管理者の配置が必要'),supply:B('발주 보류 · 공급·예산 확인','発注保留・供給と予算を確認'),staff:B('생산 인력 없음','生産人員なし'),product:B('생산 상품 선택 필요','製品の選択が必要'),materials:B('원재료 대기','原材料待ち'),delivery:B('배송 보류 · 인력·차량·재고·예산','配送保留・人員・車両・在庫・予算')})[key]);}
function mgFinanceUI(f){const a=mgFirm(f),r=refFirm(f),kind=refValue('mg-loan-kind','equipment'),amount=Number(refValue('mg-amount',100))*1000,room=companyBorrowRoom(f),annual=mgAnnualRate(f,kind)-(kind!=='bond'&&refValue('mg-rate-type','fixed')==='variable'?.005:0);
 return `<h3>${T('재무 · 월 상환','財務・月次返済')}</h3>`+row(T('현금 / 추가 차입 한도','現金／追加借入枠'),money(f.account.cash)+' / '+money(room))+row(T('신용 / 적용 연 이율','信用／適用年利'),f.meta.credit+' / '+(annual*100).toFixed(2)+'%')+
 `<div class="expansion-form">${refField('mg-loan-kind',T('차입 상품','借入商品'),[['equipment',T('설비 · 24개월 / 원금 3개월 거치','設備・24か月／元金3か月据置')],['working',T('운전자금 · 3개월 만기 일시상환','運転資金・3か月満期一括返済')],['bond',T('회사채 · 36개월 / 6개월 흑자 필요','社債・36か月／6か月黒字が必要')]])}${refField('mg-rate-type',T('금리 조건','金利条件'),[['fixed',T('고정','固定')],['variable',T('변동 · 최초 연 -0.5%p (회사채 제외)','変動・初回年−0.5ポイント（社債除外）')]])}${refNumber('mg-amount',T('금액 ($)','金額 ($)'),100,10,1000000)}${mgButton('borrow',T('차입 실행','借入実行'),'',amount>room||f.meta.credit<40)}${refButton('equity',T('100주 신주 발행','新株100株発行'))}${refButton('buyback',T('100주 자사주 매입','自社株100株買戻し'))}${refButton('insurance',T('보험 $15 / 30일','保険 $15／30日'))}</div>`+
 row(T('입력 금액의 월 이자 예상 / 거치 후 월 원금','入力額の月利息概算／据置後月元金'),money(amount*annual/12)+' / '+(kind==='equipment'?money(Math.ceil(amount/21)):T('만기 일시상환','満期一括返済')))+
refTable([T('계약','契約'),T('잔액 / 연 이율','残高／年利'),T('다음 지급 / 만기','次回支払／満期'),T('상환','返済')],r.notes.map(n=>[`#${n.id} ${n.legacy||!n.calendar?T('기존 계약','既存契約'):n.product==='working'?T('운전자금','運転資金'):n.product==='bond'?T('회사채','社債'):T('설비','設備')}`,`${money(n.principal)} / ${(n.rate*365*100).toFixed(2)}% · ${n.variable&&!n.fixed?T('변동','変動'):T('고정','固定')}`,`${mgDateText(n.next||n.due)} / ${mgDateText(n.due)}${n.missed?' · '+T('연체 ','延滞 ')+n.missed:''}`,mgButton('repay',T('입력 금액 상환','入力額を返済'),n.id)+mgButton('repay-all',T('잔액 상환','残高を返済'),n.id)+refButton('restructure',T('재조정','再調整'),n.id) ]))+
 refTable([T('지급 예정','支払予定'),T('기일','期日'),T('금액','金額')],r.bills.slice().sort((a,b)=>a.due-b.due).map(b=>[b.kind==='wages'?T('급여','給与'):b.kind==='interest'?T('이자','利息'):b.kind==='tax'?T('법인세','法人税'):T('매입·기타','仕入・その他'),mgDateText(b.due),money(b.amount)]));
}
function mgPoliciesUI(f){const a=mgFirm(f),r=refFirm(f);refInputs['mg-pricing']??=a.pricing;return `<h3>${T('운영 규정','運営規定')}</h3>`+row(T('오늘 집행 / 일 예산','本日執行／日次予算'),money(a.spent)+' / '+money(a.dailyBudget))+
 `<div class="expansion-form">${mgButton('auto',a.enabled?T('자동 운영 중 · 정지','自動運営中・停止'):T('자동 운영 시작','自動運営を開始'))}${refNumber('mg-budget',T('일 예산 ($)','日次予算 ($)'),a.dailyBudget/1000,1,100000)}${refNumber('mg-reserve',T('최소 현금 ($)','最低現金 ($)'),a.reserve/1000,0,1000000)}${refField('mg-pricing',T('가격 정책','価格方針'),[['manual',T('직접 지정 가격 유지','手動指定価格を維持')],['margin',T('마진 확보 · 원가 ×2.2','利益確保・原価 ×2.2')],['share',T('판매 확대 · 원가 ×1.7','販売拡大・原価 ×1.7')]])}${mgButton('policy-save',T('규정 저장','規定を保存'))}${mgButton('review',a.review?T('연구 단계 자동 승인: 켬','研究段階自動承認：オン'):T('연구 단계 자동 승인: 끔','研究段階自動承認：オフ'))}${mgButton('month-pause',refWorld().management.pauseMonth?T('월말 자동 정지: 켬','月末自動停止：オン'):T('월말 자동 정지: 끔','月末自動停止：オフ'))}</div>`+
 `<p>${T('판매 상품만 수요·배송 대기량에 맞춰 발주. 7일 내 지급 예정액과 최소 현금은 유보합니다. 연구 추가 예산은 별도 승인합니다.','販売商品のみ需要・配送待ち量に応じて発注。7日以内の支払予定額と最低現金を留保。研究追加予算は個別に承認します。')}</p>`+
 refTable([T('거점','拠点'),T('책임자','責任者'),T('공급사 / 정비 기준','仕入先／整備基準'),T('운영','運営')],r.sites.filter(s=>s.kind==='warehouse'&&!s.closed).map(s=>[`#${s.id} ${tr(MAPS[s.map].name)}`,s.id===refHome(f).id?T('사장 · 배송 최대 2대','社長・配送最大2台'):s.manager?'#'+s.manager:T('미배치','未配置'),['Aqua','Sun','Value'][s.policy.supplier]+' / '+s.policy.repair+'%',refButton('policy-toggle',s.policy.enabled?T('정지','停止'):T('가동','稼働'),s.id)]))+
 `<div class="expansion-form">${refField('policy-site',T('거점','拠点'),refSiteChoices(f,'warehouse'))}${refField('policy-supplier',T('주 공급사','主仕入先'),[[0,'Aqua'],[1,'Sun'],[2,'Value']])}${refField('policy-backup',T('예비 공급사','予備仕入先'),[[1,'Sun'],[0,'Aqua'],[2,'Value']])}${refNumber('policy-repair',T('정비 기준 (%)','整備基準 (%)'),35,0,100)}${mgButton('site-policy',T('거점 규정 저장','拠点規定を保存'))}</div>`+
 refTable([T('운영 보류','運営保留'),T('거점','拠点')],a.blocked.map(x=>[mgReason(x.key),'#'+x.site]));}
function mgReportsUI(f){const a=mgFirm(f),r=refFirm(f),last=a.month.find(m=>m.closed),previous=last&&a.month[a.month.indexOf(last)+1],due=r.bills.filter(b=>b.due<=state.day+30).reduce((n,b)=>n+b.amount,0)+r.notes.reduce((sum,n)=>sum+(n.due<=state.day+30?n.principal:n.next<=state.day+30&&n.next>n.grace&&n.product==='equipment'?Math.min(n.principal,n.installment):0),0);
 return `<h3>${T('월 결산 · 경영 분석','月次決算・経営分析')}</h3>`+row(T('30일 내 지급 예정 / 현금','30日以内支払予定／現金'),money(due)+' / '+money(f.account.cash))+row(T('전월 순이익 / 전전월 대비','前月純利益／前々月比'),last?money(last.profit)+' / '+(previous?money(last.profit-previous.profit):'—'):'—')+
 refTable([T('월 / 결산일수','月／決算日数'),T('매출 / 원가','売上／原価'),T('급여 / 세금','給与／税金'),T('순이익','純利益'),T('영업 / 투자 / 재무 현금흐름','営業／投資／財務キャッシュフロー')],a.month.map(m=>[m.key+' / '+m.days+(m.closed?'':T(' 집계 중',' 集計中')),money(m.revenue)+' / '+money(m.cost),money(m.payroll)+' / '+money(m.tax),money(m.profit),money(m.operating)+' / '+money(m.investing)+' / '+money(m.financing)]))+
 refTable([T('병목','ボトルネック'),T('사업장','事業所')],[...a.blocked.map(x=>[mgReason(x.key),'#'+x.site]),...f.machines.filter(m=>!m.stock).map(m=>[T('품절','品切れ'),tr(LOCATIONS[m.loc].short)])]);}
const mgBeforeRender=renderReference;renderReference=function(){
 if(deskTab==='management-migrate'&&!mgEnabled()){for(const n of Object.values(deskNodes))n.hidden=n!==refPanel;patchPanel(refPanel,`<h3>${T('장기 경영 전환','長期経営へ移行')}</h3><p>${T('달력 계절·월 급여·월 결산을 적용합니다. 기존 차입·연구 계약은 유지하며, 자동 운영은 운영 규정에서 켭니다. 전환 전 저장을 별도 보관합니다.','暦の季節・月給・月次決算を適用。既存の借入・研究契約は維持し、自動運営は運営規定で開始。移行前セーブを別途保存します。')}</p>${mgButton('migrate',T('전환 적용','移行を適用'))}`);return;}
 if(!mgEnabled()||!['finance','policies','reports'].includes(deskTab))return mgBeforeRender();refDesk=deskTab;for(const n of Object.values(deskNodes))n.hidden=n!==refPanel;const f=playerFirm();patchPanel(refPanel,deskTab==='finance'?mgFinanceUI(f):deskTab==='policies'?mgPoliciesUI(f):mgReportsUI(f));
};
const mgBeforeExtra=refExtraUI;refExtraUI=function(f){let html=mgBeforeExtra(f);if(!mgEnabled())return html;const a=mgFirm(f);if(refDesk==='production')html+=`<h4>${T('계속 생산','継続生産')}</h4><div class="expansion-form">${refField('mg-factory',T('공장','工場'),refSiteChoices(f).filter(([id])=>['drink','machine'].includes(refSite(f,id).kind)))}${refField('mg-sku',T('상품','商品'),refOwnProducts(f).map(s=>[s.id,tr(s.name)]))}${refNumber('mg-target',T('목표 재고','目標在庫'),200,1,1000)}${refNumber('mg-batch',T('회당 생산량','1回生産量'),100,1,500)}${mgButton('production',T('계속 생산 등록','継続生産を登録'))}</div>`+refTable([T('공장 / 상품','工場／商品'),T('목표 / 회당','目標／1回'),T('상태','状態')],a.production.map(p=>['#'+p.site+' / '+(refSKU(p.sku)?tr(refSKU(p.sku).name):T('기기','機械')),p.target+' / '+p.batch,mgButton('production-toggle',p.enabled?T('가동 중 · 정지','稼働中・停止'):T('재개','再開'),p.site)]));
 if(refDesk==='research')html+=row(T('선택 과제 예산 / 독점 계약','選択課題予算／独占契約'),money(600000*(chainFirm(f).licenses[refValue('research-key','quality')]+1))+' / '+money(900000*(chainFirm(f).licenses[refValue('research-key','quality')]+1)))+`<p>${T('신규 연구: 단계별 기본 30일 × 기술 단계. 협력사 연구 인원·동시 프로젝트·사내 연구소에 따라 완료일이 달라집니다.','新規研究：各段階の基本30日 × 技術レベル。提携先研究人員・同時案件・社内研究所で完了日が変わります。')}</p>`;return html;};
document.addEventListener('click',e=>{const b=e.target.closest('[data-mg]');if(!b||b.disabled)return;let ok=false;if(b.dataset.mg==='migrate')ok=mgInitialize(true);else if(mgEnabled()){const f=playerFirm(),a=mgFirm(f),n=id=>Number(refValue(id)),action=b.dataset.mg;
 if(action==='borrow')ok=mgBorrow(f,n('mg-amount')*1000,refValue('mg-loan-kind','equipment'),refValue('mg-rate-type','fixed'));
 if(action==='repay'||action==='repay-all')ok=mgRepay(f,+b.dataset.arg,action==='repay-all'?Infinity:n('mg-amount')*1000);
 if(action==='auto'){a.enabled=!a.enabled;ok=true;}if(action==='review'){a.review=!a.review;ok=true;}if(action==='month-pause'){refWorld().management.pauseMonth=!refWorld().management.pauseMonth;ok=true;}
 if(action==='policy-save'){const budget=n('mg-budget')*1000,reserve=n('mg-reserve')*1000,pricing=refValue('mg-pricing');if(int(budget,1000,100000000)&&int(reserve,0,1000000000)&&['manual','margin','share'].includes(pricing)){Object.assign(a,{dailyBudget:budget,reserve,pricing});ok=true;}}
 if(action==='site-policy')ok=refPolicy(f,n('policy-site'),{supplier:n('policy-supplier'),backup:n('policy-backup'),repair:n('policy-repair')});
 if(action==='production'){const s=refSite(f,n('mg-factory')),sku=refSKU(refValue('mg-sku'));if(s&&['drink','machine'].includes(s.kind)&&(s.kind==='machine'||sku&&sku.owner===f.id&&!sku.retired)&&int(n('mg-target'),1,1000)&&int(n('mg-batch'),1,500)){a.production=a.production.filter(p=>p.site!==s.id);a.production.push({site:s.id,sku:s.kind==='machine'?'':sku.id,target:s.kind==='machine'?Math.min(10,n('mg-target')):n('mg-target'),batch:s.kind==='machine'?1:n('mg-batch'),enabled:true});ok=true;}}
 if(action==='production-toggle'){const p=a.production.find(p=>p.site===+b.dataset.arg);if(p){p.enabled=!p.enabled;ok=true;}}
 }if(!ok)toast(B('실행 조건·자금 확인','実行条件・資金を確認'));save();render();});
const mgOfficeBefore=officeUpdate;officeUpdate=function(){mgOfficeBefore();document.body.classList.toggle('management',mgEnabled());if(mgEnabled()){controlText('day',mgDateText());const small=document.querySelector('.day-control small');if(small)small.textContent=refWorld().management.free?T(' / 자유 경영',' / 自由経営'):' / '+mgDateText(state.duration);}};
const mgModalBefore=drawModal;drawModal=function(){mgModalBefore();if(modalView==='newrun'){const select=$('run-duration');if(select){select.innerHTML=[[36500,T('자유 경영 · 기간 제한 없음','自由経営・期間制限なし')],[365,T('1년 평가','1年評価')],[1095,T('3년 평가','3年評価')]].map(([d,label])=>`<option value="${d}" ${d===chosenDuration?'selected':''}>${label}</option>`).join('');}const p=$('modal-body').querySelector('p');if(p)p.textContent=T('회사 설립 · 2000-01-01. 자동 발주와 사장 배송으로 영업을 시작합니다.','会社設立・2000-01-01。自動発注と社長配送で営業を開始します。');}
 if(modalView==='help'&&mgEnabled())$('modal-body').innerHTML=`<h2>${T('회사 운영','会社運営')}</h2><p>${T('1배속 하루 3분. 계절은 달력에 따라 변합니다. 급여는 월말, 차입금은 계약의 월 지급일에 지급합니다.','1倍速で一日3分。季節は暦に従って変化。給与は月末、借入金は契約の月次支払日に支払います。')}</p><p>${T('운영 규정에서 예산·현금 유보·가격을 지정합니다. 첫 거점은 사장이 관리하고 최대 2대까지 배송합니다. 확장 거점은 관리자, 배송은 직원·차량·경로가 필요합니다.','運営規定で予算・現金留保・価格を指定。最初の拠点は社長が管理し最大2台に配送。追加拠点には管理者、配送には社員・車両・ルートが必要です。')}</p><p>${T('공장의 계속 생산에는 관리자·생산 직원·원재료가 필요합니다. 연구 추가 예산과 투자 결정은 직접 처리합니다.','工場の継続生産には管理者・生産社員・原材料が必要です。研究追加予算と投資判断は個別に処理します。')}</p>`+buttons(inGameSession&&menuOpen?`<button id="menu-back">${T('메뉴로','メニューへ')}</button>`:closeButton());};
