/* Jobs and education use paid people, not company-wide upgrade counters. */
function chainRole(role){return ({collect:[2000,'매출 회수','売上回収'],restock:[3000,'상품 보충','商品補充'],technician:[2800,'정비·설치','整備・設置'],logistics:[2400,'입출고','入出庫'],drink:[2600,'음료 생산','飲料生産'],machine:[3200,'기기 생산','機械生産'],research:[4000,'연구','研究']})[role];}
function chainEmployee(role){return {id:state.enterprise.chain.next++,role,skill:1,salary:chainRole(role)[0],map:-1,training:0,experience:0};}
function chainWorkers(f,role,map=-1){return chainFirm(f).staff.filter(w=>w.role===role&&w.training<=0&&(map<0||w.map<0||w.map===map)).reduce((n,w)=>n+w.skill,0);}
function syncChainStaff(){if(!chainEnabled())return;for(const role of ['collect','restock'])state.staff[role]=chainFirm(playerFirm()).staff.filter(w=>w.role===role&&w.training<=0).length;}
function chainHire(f,role){const c=chainFirm(f);if(!chainRole(role)||c.staff.length>=30||f.account.cash<5000||state.ended)return false;companyExpense(f,5000);c.staff.push(chainEmployee(role));syncChainStaff();return true;}
function chainTrain(f,id){const w=chainFirm(f).staff.find(w=>w.id===id);if(!w||w.training||w.skill>=3||f.account.cash<10000||state.ended)return false;companyExpense(f,10000);w.training=DAY_MS*5;syncChainStaff();return true;}
function chainDismiss(f,id){const c=chainFirm(f),w=c.staff.find(w=>w.id===id);if(!w||state.ended||f.account.cash<w.salary*3)return false;companyExpense(f,w.salary*3);c.staff=c.staff.filter(v=>v!==w);if(f.id==='player')state.jobs=state.jobs.filter(j=>j.employee!==id);else f.ops.jobs=f.ops.jobs.filter(j=>j.employee!==id);syncChainStaff();return true;}
function chainPayroll(f){return chainFirm(f).staff.reduce((n,w)=>n+w.salary,0)*inflationFactor();}
function chainTechnicalRate(f,order){const c=chainFirm(f),map=LOCATIONS[order.loc].map;return c.staff.filter(w=>w.role==='technician'&&!w.training&&(w.map<0||w.map===map)).reduce((n,w)=>n+w.skill/Math.max(1,c.orders.filter(o=>['installation','repair'].includes(o.kind)&&!o.outsourced&&(w.map<0||w.map===LOCATIONS[o.loc].map)).length),0);}
const chainOldPayroll=companyPayroll;companyPayroll=function(f){return chainEnabled()?chainPayroll(f):chainOldPayroll(f);};
const chainOldHire=hire;hire=function(role,delta){if(!chainEnabled())return chainOldHire(role,delta);if(delta>0)chainHire(playerFirm(),role);else{const w=chainFirm(playerFirm()).staff.find(w=>w.role===role);if(w)chainDismiss(playerFirm(),w.id);}save();render();};
const chainDispatch=dispatch;dispatch=function(type,loc,staff=false){
 if(!chainEnabled()||!staff)return chainDispatch(type,loc,staff);
 const c=chainFirm(playerFirm()),w=c.staff.find(w=>w.role===type&&!w.training&&(w.map<0||w.map===LOCATIONS[loc].map)&&!state.jobs.some(j=>j.employee===w.id));if(!w)return false;
 const result=chainDispatch(type,loc,true);if(result){const j=state.jobs.at(-1);j.employee=w.id;j.remaining/=w.skill;j.duration/=w.skill;}return result;
};
function chainRepair(f,loc){const c=chainFirm(f),m=f.machines.find(m=>m.loc===loc);if(!m||m.condition>=100||c.orders.some(o=>o.kind==='repair'&&o.loc===loc)||state.ended)return false;const workers=chainWorkers(f,'technician',LOCATIONS[loc].map),value=workers?5000:15000;if(f.account.cash<value)return false;companyExpense(f,value);const duration=DAY_MS*(workers?1:2);c.orders.push({id:state.enterprise.chain.next++,kind:'repair',loc,outsourced:!workers,qty:1,value:0,remaining:duration,duration});return true;}
const organizationReceive=companyReceive;companyReceive=function(f,ms){if(!chainEnabled())return organizationReceive(f,ms);if(!finite(ms)||ms<0)return;let left=ms;while(left>0){const step=Math.min(200,left);organizationReceive(f,step);for(const w of chainFirm(f).staff){if(w.training>0){w.training=Math.max(0,w.training-step);if(w.training===0){w.skill=Math.min(3,w.skill+.5);w.salary=Math.round(chainRole(w.role)[0]*(.8+w.skill*.2));}}else w.experience+=step/DAY_MS;}left-=step;}syncChainStaff();};
const organizationAutomation=runAutomation;runAutomation=function(f){if(!chainEnabled())return organizationAutomation(f);const a=expansionFirm(f).automation,repair=a.repair;if(repair)for(const m of f.machines)if(m.condition<repair)chainRepair(f,m.loc);a.repair=0;try{return organizationAutomation(f);}finally{a.repair=repair;}};
const chainAdvanceNPC=advanceRivalOperations;advanceRivalOperations=function(ms){
 if(!chainEnabled())return chainAdvanceNPC(ms);for(const f of rivalFirms()){if(f.policy.defeated||!f.ops.market||f.ops.market.legacy)continue;f.ops.market.payroll+=chainPayroll(f)*ms/DAY_MS;companyReceive(f,ms);for(const j of f.ops.jobs)j.remaining-=ms;
  for(const j of f.ops.jobs.filter(j=>j.remaining<=0)){const m=f.machines.find(m=>m.loc===j.loc);if(m){if(j.type==='collect'){f.account.cash+=m.vault;m.vault=0;}else companyRestock(f,m);}}f.ops.jobs=f.ops.jobs.filter(j=>j.remaining>0&&f.account.owned.includes(j.loc));
  for(const w of chainFirm(f).staff.filter(w=>['collect','restock'].includes(w.role)&&!w.training)){if(f.ops.jobs.some(j=>j.employee===w.id))continue;const m=f.machines.filter(m=>(w.map<0||LOCATIONS[m.loc].map===w.map)&&!f.ops.jobs.some(j=>j.type===w.role&&j.loc===m.loc)).sort((a,b)=>w.role==='collect'?b.vault-a.vault:a.stock-b.stock).find(m=>w.role==='collect'?m.vault>=10000:m.stock<companyCapacity(f,m)*.35);if(m)f.ops.jobs.push({type:w.role,loc:m.loc,employee:w.id,remaining:(4500+LOCATIONS[m.loc].map*1200)/w.skill});}
 }};
function chainAI(){
 for(const f of rivalFirms()){const c=chainFirm(f),r=f.policy,x=expansionFirm(f);if(c.lastAI>=state.day)continue;c.lastAI=state.day;
  if(r.defeated){if(state.enterprise.industry.entry&&state.day-f.meta.exitDay>=30&&state.day%10===0)reviveCompany(f);continue;}
  recoverCompanyCash(f);if(f.account.cash<30000)borrowCompany(f,Math.max(0,100000-f.account.cash));
  if(f.meta.distress>=7&&companyRecoverable(f)<=0){closeCompany(f,'자금조달 실패');continue;}
  if(r.until<state.day){r.mode=f.ops.lastProfit<0?'retreat':f.id==='nova'?'advertise':'price';r.target=LOCATIONS[f.machines[0]?.loc||0].map;r.until=state.day+5;f.meta.prices.fill(1500);if(r.mode==='price'&&f.account.cash>100000)f.meta.prices[r.target]=1200;}
  for(const role of ['collect','restock'])if(c.staff.filter(w=>w.role===role).length<Math.ceil(f.machines.length/3)&&f.account.cash>120000)chainHire(f,role);
  for(let p=0;p<6;p++)if(f.machines.some(m=>m.slots.some(s=>s.product===p))&&f.ops.warehouse[p].qty<40&&!f.ops.orders.some(o=>o.product===p)){if(x.plants.drink&&chainWorkers(f,'drink')){if(c.materials.drink.qty<100&&!c.orders.some(o=>o.kind==='raw'))orderMaterials(f,'drink',300);produce(f,'drink',p,100);}else{const options=state.enterprise.chain.suppliers.filter(s=>s.kind==='drink'&&s.stock[p].qty>=100).sort((a,b)=>supplierPrice(a,p,f)-supplierPrice(b,p,f));if(options[0])companyOrder(f,p,100,['aqua','sun','value'].indexOf(options[0].id));}}
  for(const m of f.machines)if(m.condition<35)chainRepair(f,m.loc);
  if(f.account.cash>600000&&state.day%10===0){const l=LOCATIONS.filter(l=>!l.auction&&!machine(l.id)&&!rivalLocations().includes(l.id)&&!chainSiteOwner(l.id))[0];if(l&&!c.sites.length)reserveSite(f,l.id);if(c.sites.length&&!x.kits.length&&!c.orders.some(o=>o.kind==='machine'))chainOrderMachine(f,'koyo',0);}
  if(x.kits.length&&c.sites.length)installKit(f,c.sites[0].loc);
  if(f.account.cash>700000&&state.day%14===0){const key=c.licenses.quality<1?'quality':c.licenses.products<3?'products':'efficiency';chainResearch(f,key,key==='efficiency'?'koyo':'aqua');}
  if(f.account.cash>1400000&&c.licenses.quality&&!x.plants.drink&&!c.builds.length)buildFactory(f,'drink');if(x.plants.drink&&!chainWorkers(f,'drink')&&f.account.cash>150000)chainHire(f,'drink');
  for(const a of state.enterprise.expansion.auctions)if(a.bidder!==f.id&&f.account.cash>Math.max(LOCATIONS[a.loc].cost,a.bid+10000)+300000)bidLand(f,a.id,Math.max(LOCATIONS[a.loc].cost,a.bid+10000));
  if(state.day%30===0){const target=rivalFirms().find(v=>v.id!==f.id&&!v.policy.defeated&&v.meta.distress>2);if(target)mergeCompanies(f,target);}
 }}
const organizationRivalTurn=rivalTurn;rivalTurn=function(){if(chainEnabled()){chainAI();expansionAI();return;}return organizationRivalTurn();};
const organizationDay=expansionDay;expansionDay=function(){if(chainEnabled())supplierDaily();return organizationDay();};
const chainAuctions=settleAuctions;settleAuctions=function(){if(!chainEnabled())return chainAuctions();const e=state.enterprise.expansion;for(const a of [...e.auctions])if(a.until<=state.day){const f=allFirms().find(f=>f.id===a.bidder&&!f.policy?.defeated);if(f){chainFirm(f).sites.push({loc:a.loc,value:a.bid});LOCATIONS[a.loc].auction=false;e.auctions=e.auctions.filter(v=>v!==a);}else{const old=allFirms().find(f=>f.id===a.bidder);if(old)old.account.cash+=a.bid;a.bid=0;a.bidder=null;a.until=state.day+5;}}};
const chainBid=bidLand;bidLand=function(f,id,amount){const a=state.enterprise?.expansion?.auctions.find(a=>a.id===id);if(chainEnabled()&&a&&chainSiteOwner(a.loc))return false;return chainBid(f,id,amount);};
function transferChain(buyer,target){if(!chainEnabled())return;const a=chainFirm(buyer),b=chainFirm(target);for(const k of ['staff','orders','sites','builds','projects'])a[k].push(...b[k]);for(const k of ['drink','machine']){a.materials[k].qty+=b.materials[k].qty;a.materials[k].value+=b.materials[k].value;}for(const k of Object.keys(a.licenses))a.licenses[k]=Math.max(a.licenses[k],b.licenses[k]);state.enterprise.chain.firms[target.id]=chainFreshFirm(target);syncChainStaff();}
const organizationTransfer=transferExpansionAssets;transferExpansionAssets=function(buyer,target){transferChain(buyer,target);return organizationTransfer(buyer,target);};
const organizationClose=closeCompany;closeCompany=function(f,reason){if(chainEnabled()&&!f.policy.defeated){f.account.cash+=chainAssets(f)*.5;state.enterprise.chain.firms[f.id]=chainFreshFirm(f);}return organizationClose(f,reason);};
const organizationRevive=reviveCompany;reviveCompany=function(f){if(!chainEnabled())return organizationRevive(f);const l=LOCATIONS.find(l=>!l.auction&&!machine(l.id)&&!rivalLocations().includes(l.id)&&!chainSiteOwner(l.id));if(!l||!f.policy.defeated)return false;const capital=mgEnabled()?Math.max(500000,runRules().rivalFunds,supplierPrice(chainSupplier('koyo'),0,f)+Math.round(l.cost*.35)+500000):Math.max(500000,runRules().rivalFunds);if(mgEnabled()){if(refWorld().investorCash<capital)return false;refWorld().investorCash-=capital;}const generation=f.meta.generation+1;Object.assign(f.meta,companyMeta(f.id),{generation});f.meta.brand=MAPS.map(()=>15);f.meta.prices=MAPS.map(()=>1500);f.account.cash=capital;if(mgEnabled())f.meta.capital=capital;f.account.owned=[];Object.assign(f.ops,emptyOperations());Object.assign(f.policy,rivalryFresh());const next=rivalById(f.id);state.enterprise.expansion.firms[f.id]=expansionFreshFirm();state.enterprise.chain.firms[f.id]=chainFreshFirm(next);for(const role of ['collect','restock','logistics'])chainFirm(next).staff.push(chainEmployee(role));reserveSite(next,l.id);chainOrderMachine(next,'koyo',0);ensureListings();companyLog(next,'신규 투자자 진입 · 기기 발주','新規投資家参入・機械発注');return true;};
function validChain(c,s){
 const nn=n=>finite(n)&&n>=0,arr=(a,n)=>Array.isArray(a)&&a.length<=n,roles=['collect','restock','technician','logistics','drink','machine','research'];
 if(!c||c.version!==1||!int(c.next,1,1e12)||!int(c.lastDay,0,1e6)||!nn(c.rawCash)||!arr(c.suppliers,5)||c.suppliers.length!==5||!c.firms)return false;
 if(!c.suppliers.every(v=>['aqua','sun','value','koyo','hokuto'].includes(v.id)&&['drink','machine'].includes(v.kind)&&finite(v.cash)&&finite(v.profit)&&nn(v.price)&&nn(v.quality)&&nn(v.capacity)&&nn(v.researchers)&&nn(v.skill)&&nn(v.technology)&&arr(v.stock,6)&&v.stock.every(w=>int(w.qty,0,100000)&&nn(w.value)))||new Set(c.suppliers.map(v=>v.id)).size!==5)return false;
 const ids=['player','mono',...(s.enterprise.industry.companies||[]).map(v=>v.meta.id)],used=[],employeeIds=[],orderIds=[];
 for(const id of ids){const f=c.firms[id];if(!f||!arr(f.staff,120)||!arr(f.orders,400)||!arr(f.sites,30)||!arr(f.builds,24)||!arr(f.projects,20)||!int(f.lastAI,0,1e6)||!f.licenses||!['products','quality','efficiency','logistics'].every(k=>int(f.licenses[k],0,3))||!f.materials||!['drink','machine'].every(k=>int(f.materials[k]?.qty,0,100000)&&nn(f.materials[k]?.value)))return false;
  if(!f.staff.every(w=>int(w.id,1,c.next-1)&&roles.includes(w.role)&&finite(w.skill)&&w.skill>=1&&w.skill<=3&&nn(w.salary)&&int(w.map,-1,MAPS.length-1)&&nn(w.training)&&nn(w.experience)))return false;employeeIds.push(...f.staff.map(w=>w.id));
  if(!f.orders.every(o=>int(o.id,1,c.next-1)&&['machine','raw','installation','repair'].includes(o.kind)&&int(o.qty,1,1000)&&nn(o.value)&&finite(o.remaining)&&o.remaining>0&&finite(o.duration)&&o.duration>0&&(o.kind!=='raw'||['drink','machine'].includes(o.material))&&(!['installation','repair'].includes(o.kind)||int(o.loc,0,LOCATIONS.length-1))&&(!['machine','installation'].includes(o.kind)||int(o.model,0,1)&&finite(o.energy)&&o.energy>=.5&&o.energy<=1)))return false;orderIds.push(...f.orders.map(o=>o.id));
  if(!f.sites.every(v=>int(v.loc,0,LOCATIONS.length-1)&&nn(v.value))||!f.builds.every(v=>int(v.id,1,c.next-1)&&['drink','machine'].includes(v.kind)&&nn(v.value)&&finite(v.remaining)&&v.remaining>0&&nn(v.duration))||!f.projects.every(p=>int(p.id,1,c.next-1)&&['products','quality','efficiency','logistics'].includes(p.key)&&c.suppliers.some(v=>v.id===p.supplier)&&int(p.tier,1,3)&&nn(p.budget)&&nn(p.spent)&&p.spent<=p.budget+.001&&nn(p.remaining)&&finite(p.duration)&&p.duration>0&&typeof p.exclusive==='boolean'&&int(p.rightsUntil,0,1e6)))return false;used.push(...f.sites.map(v=>v.loc));
 }
 const inventories=[{machines:s.machines,warehouse:s.enterprise.warehouse,orders:s.enterprise.orders},s.enterprise.operations,...s.enterprise.industry.companies.map(v=>v.operations)];
 if(!inventories.every(f=>[...f.warehouse,...f.orders,...f.machines.flatMap(m=>m.slots||[])].every(w=>w.quality===undefined||finite(w.quality)&&w.quality>=0&&w.quality<=3)&&f.orders.every(o=>o.handling===undefined||finite(o.handling)&&o.handling>0&&finite(o.handlingCapacity)&&o.handlingCapacity>=.5)&&f.machines.every(m=>(m.model===undefined||int(m.model,0,1))&&(m.energy===undefined||finite(m.energy)&&m.energy>=.5&&m.energy<=1))))return false;
 const owned=[...s.machines.map(m=>m.loc),...s.npc.owned,...s.enterprise.industry.companies.flatMap(v=>v.npc.owned)];return new Set([...owned,...used]).size===owned.length+used.length&&new Set(employeeIds).size===employeeIds.length&&new Set(orderIds).size===orderIds.length;
}
