/* Pixel renderer: read-only presentation on the existing scene clock. */
const W=704,H=480,canvas=document.createElement('canvas');canvas.id='pixel-city';canvas.width=W;canvas.height=H;canvas.setAttribute('role','img');
const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;cityStage.prepend(canvas);document.querySelector('.city').style.visibility='hidden';document.querySelector('.city').setAttribute('aria-hidden','true');cityStage.classList.add('pixel-stage');
const ground=document.createElement('canvas');ground.width=W;ground.height=H;const gc=ground.getContext('2d');gc.imageSmoothingEnabled=false;
const point=(x,y)=>[265+(x-y)*24,176+(x+y)*12],lots=[[0,0],[6.5,0],[13,0],[0,7],[6.5,7],[13,7]],stop=i=>{const [x,y]=lots[i%6];return point(x-.25,y+.8);};
const districtPieces=[['garden','campus','startup','house','station','riverside'],['office','bank','startup','studio','office','hall'],['station','arcade','terminal','cinema','market','plaza'],['beach','garden','lookout','camp','inn','fair'],['station','warehouse','bank','riverside','terminal','tower']];
let key='',objects=[],lastSelection=-1,zoom='auto',lastDepths=[],lastActors=[],lastSales=[];
function blit(c,name,x,y){const s=SPRITES[name];c.drawImage(s.canvas,Math.round(x-s.ax),Math.round(y-s.ay));}
function object(name,x,y){objects.push({name,x,y,depth:y});}
function groundPoly(points,color,edge){new Pixel(gc).poly(points,color,edge);}
function plot(x,y,w,d,color){groundPoly([point(x,y),point(x+w,y),point(x+w,y+d),point(x,y+d)],color);}
function landscape(){const season=sceneSeason(),night=!!state.live&&state.live.elapsed>DAY_MS*.8,newKey=selectedMap+':'+season+':'+night+':'+state.weather+':'+lang;if(key===newKey)return;key=newKey;objects=[];const tree=season===1?'tree':'tree-'+['spring','summer','autumn','winter'][season],land=season===3?'mist':season===2?'sand':'grass';gc.fillStyle=PAL[land];gc.fillRect(0,0,W,H);
 for(let s=-35;s<45;s++)for(let x=-22;x<32;x++){const y=s-x;if(y<-24||y>35)continue;const [px,py]=point(x,y),road=(y>=2&&y<=3)||(y>=9&&y<=10)||(x>=2&&x<=3)||(x>=9&&x<=10),side=(y>=1&&y<=4)||(y>=8&&y<=11)||(x>=1&&x<=4)||(x>=8&&x<=11);if(road||side)blit(gc,road?'road':'paving',px,py);else if(season!==3)for(let i=0;i<3;i++)new Pixel(gc).dot(px+i*4,py+i*2,season===2?'gold':'leaf');}
 const gp=new Pixel(gc);for(const y of [2.5,9.5])for(let x=-14;x<30;x+=2)gp.line(...point(x,y),...point(x+.7,y),'yellow');for(const x of [2.5,9.5])for(let y=-12;y<22;y+=2)gp.line(...point(x,y),...point(x,y+.7),'yellow');
 for(const x of [2.5,9.5])for(const y of [1,4,8,11])for(let i=0;i<5;i++)gp.line(...point(x-1+i*.42,y-.22),...point(x-1+i*.42,y+.22),'white');
 if(selectedMap===3){plot(-20,-15,21,13.6,'blue');plot(-20,-1.4,21,.65,'cyan');plot(-20,-.75,21,.5,'gold');for(let x=-12;x<0;x+=1.4)gp.line(...point(x,-2.3),...point(x+.7,-2.3),'glass');}
 if(selectedMap===4){plot(-18,-14,37,9.7,'blue');plot(-18,-4.3,37,.6,'sand');object('boat',...point(1,-6));}
 if(selectedMap===2){plot(-7,-6,28,1.4,'sand');for(let x=-7;x<22;x+=.4)gp.line(...point(x,-6),...point(x,-4.6),'darkred');for(const y of [-5.8,-4.8])gp.line(...point(-7,y),...point(22,y),'steel');object('train',...point(1,-5.2));}
 districtPieces[selectedMap].forEach((kind,i)=>{const [x,y]=lots[i],[sx,sy]=point(x,y);plot(x-3,y-2.5,4,3.8,kind==='garden'||kind==='fair'||kind==='camp'?land:'cream');
  if(['garden','riverside','beach','camp','lookout','fair','plaza','market'].includes(kind)){
   if(['riverside','camp'].includes(kind)){plot(x-4.5,y-3.5,4.8,2.2,'blue');plot(x-4.3,y-3.3,4.4,1.8,'cyan');for(let t=0;t<5;t++)gp.line(...point(x-4+t*.7,y-2.8),...point(x-3.7+t*.7,y-2.8),'glass');if(kind==='beach')plot(x-4.5,y-1.3,4.8,.7,'gold');}
   if(kind==='camp'){object('tent',sx-33,sy-17);object('tent',sx+22,sy-42);object('sign',sx+30,sy-4);}
   if(kind==='lookout'){plot(x-3,y-3,4,3,'sand');object('lookout',sx-5,sy-7);object(tree,sx+42,sy-37);}
   if(kind==='fair'){object('wheel',sx,sy-13);object('stall',sx-53,sy-3);object('gate',sx+21,sy+5);}
   if(kind==='garden'){object('gazebo',sx+8,sy-9);object(tree,sx-54,sy-23);object(tree,sx+42,sy-44);object(tree,sx-18,sy-69);object('bench',sx-40,sy+2);}
   if(kind==='riverside'||kind==='beach'){object('bench',sx-28,sy-1);object('lamp',sx+14,sy-8);if(kind==='beach'){object('umbrella',sx-49,sy-38);object('umbrella',sx-15,sy-56);}else object(tree,sx+29,sy-37);}
   if(kind==='plaza'){object('sign',sx-33,sy-22);object('bench',sx+25,sy-17);object(tree,sx,sy-60);object('lamp',sx-50,sy-39);}
   if(kind==='market'){for(const [dx,dy]of [[-44,-28],[0,-52],[32,-29]])object(night?'stall':'stall-closed',sx+dx,sy+dy);object('sign',sx-2,sy+2);}
  }else{object(kind,sx,sy);if(kind==='campus')object('gate',sx-29,sy+12);if(kind==='terminal')object('bus',sx+33,sy+22);if(kind==='station'){object('sign',sx-47,sy+9);object('bike',sx+38,sy-3);}if(kind==='inn')object('steam',sx+26,sy-59);if(['house','startup','studio'].includes(kind))object('bike',sx+29,sy-1);if(kind==='warehouse')object('cart',sx+33,sy+7);}
  object('bin',sx+20,sy+13);object('lamp',sx-66,sy+24);if(!['garden','lookout','fair','camp','beach','riverside'].includes(kind))object(tree,sx+49,sy-35);
 });
 // Small edge plots make a continuous district without turning names into interchangeable buildings.
 for(const [x,y]of [[-5,-3],[7,-5],[15,-3],[-4,5]]){const p=point(x,y);if(selectedMap===0)object('house',...p);else if(selectedMap===3)object(tree,...p);else if(selectedMap===4)object('warehouse',...p);else object('store',...p);}
 if(season===3){for(let x=0;x<W;x+=17)for(let y=0;y<H;y+=19){const data=gc.getImageData(x,y,1,1).data;if(data[0]!==parseInt(PAL.asphalt.slice(1,3),16))gp.rect(x,y,3,1,'white');}}
 if(season===3){for(const o of objects){if(!['house','office','tower','store','inn','cinema','station','bank','campus','startup','studio','hall','terminal','arcade','warehouse'].includes(o.name))continue;const name=o.name+'-snow';if(!SPRITES[name])snowRoof(name,o.name);o.name=name;}}
 if(night){for(const o of objects){if(!['office','tower','store','inn','cinema','station','bank'].includes(o.name.replace('-snow','')))continue;const n=o.name+'-night';if(!SPRITES[n])paletteCopy(n,o.name,{glass:'yellow',cyan:'gold'});o.name=n;}}
 canvas.setAttribute('aria-label',tr(MAPS[selectedMap].name)+' · '+tr(SEASONS[season].name)+' · '+sceneWeatherName());
}
function route(loc,progress){const [x,y]=lots[loc%6];return point(x-2.7+2.45*Math.max(0,Math.min(1,progress)),y+1.18);}
function addPerson(actors,loc,progress,seed,time,using,worker=false,out=false,cargo=true){const [x,y]=route(loc,progress),dir=out?'nw':'se',frame=sceneMotion?Math.floor(time/145+seed)%4:0,name=using?(worker?'worker-use':'customer-use'):worker?`worker-${dir}-${frame}`:`customer-${['blue','leaf','gold'][seed%3]}-${dir}-${frame}`;actors.push({name,x,y,depth:y,kind:worker?'worker':'customer',loc});if(worker&&cargo)actors.push({name:'cart',x:x+13,y:y+5,depth:y+5,kind:'cargo',loc});if(state.weather===2&&sceneSeason()!==3)actors.push({name:'umbrella',x,y:y-19,depth:y+.1,kind:'umbrella',loc});}
function paint(time){landscape();ctx.clearRect(0,0,W,H);ctx.drawImage(ground,0,0);const actors=[],bubbles=[],l=state.live,clock=l?Math.min(DAY_MS,l.elapsed+businessCarry):time;
 const firms=typeof industryEnabled==='function'&&industryEnabled()?allFirms():[{id:'player',machines:state.machines}];const shown=new Set();for(const f of firms)for(const m of f.machines.filter(m=>LOCATIONS[m.loc]?.map===selectedMap)){const [x,y]=stop(m.loc);shown.add(m.loc);const service=(m.condition??100)<25,name=service?'machine-service':f.id==='player'?(m.stock?'machine':'machine-empty'):(m.stock?'machine-rival':'machine-rival-empty');actors.push({name,x,y,depth:y,kind:'machine',loc:m.loc});}
 if(!(typeof industryEnabled==='function'&&industryEnabled()))for(const loc of rivalLocations().filter(id=>LOCATIONS[id]?.map===selectedMap&&!shown.has(id))){const [x,y]=stop(loc);actors.push({name:'machine-rival',x,y,depth:y,kind:'machine',loc});}
 // Ambient pedestrians carry no purchase marker and never modify accounts.
 for(let i=0;i<6;i++){const progress=sceneMotion?((time/19000+i/6)%1):.25,loc=selectedMap*6+i;addPerson(actors,loc,progress,i,time,false);}
 if(l){for(const r of sceneCustomerRows(l).filter(r=>LOCATIONS[r.loc]?.map===selectedMap))for(const bought of (r.bought||[]).slice(-80)){const age=clock-sceneCustomerDue(r,bought.i);if(age<0||age>2200)continue;const progress=sceneMotion?(age<700?1:1-(age-700)/1500):1;addPerson(actors,r.loc,progress,r.loc*43+bought.i,clock,age<700,false,age>=700);if(age>=700){const [x,y]=route(r.loc,progress);actors.push({name:'can',x:x-5,y:y-11,depth:y+.2,kind:'drink',loc:r.loc});}if(age<1200)bubbles.push({loc:r.loc,text:'+'+money(bought.price),age});}}
 const jobs=[...(state.jobs||[])];for(const f of firms){if(f.id!=='player')jobs.push(...(f.ops?.jobs||[]));const ref=state.enterprise?.reference?.firms?.[f.id];for(const j of ref?.work||[])if(j.kind==='route'&&j.duration>0&&j.stops?.length){const progress=Math.max(0,Math.min(.999,1-j.remaining/j.duration)),idx=Math.min(j.stops.length-1,Math.floor(progress*j.stops.length));jobs.push({loc:j.stops[idx].loc,remaining:(1-progress*j.stops.length+idx)*j.duration,duration:j.duration,type:'restock'});}}
 for(const [i,j]of jobs.entries()){if(LOCATIONS[j.loc]?.map!==selectedMap||!(j.duration>0))continue;const progress=Math.max(0,Math.min(1,1-j.remaining/j.duration));addPerson(actors,j.loc,Math.min(1,progress/ .82),i,clock,progress>.82,true,false,j.type!=='collect');}
 const all=[...objects,...actors].sort((a,b)=>a.depth-b.depth);lastDepths=all.map(a=>a.depth);lastActors=actors.map(({kind,loc,name,x,y})=>({kind,loc,name,x,y}));lastSales=bubbles.map(b=>b.loc);for(const o of all)blit(ctx,o.name,o.x,o.y);
 const p=new Pixel(ctx),season=sceneSeason(),t=sceneMotion?time:0;if(state.weather===2||season===0||season===2){const count=state.weather===2?55:13;for(let i=0;i<count;i++){const x=Math.round((i*137+t*.012)%W),y=Math.round((i*73+t*(state.weather===2&&season!==3?.16:.027))%H);if(state.weather===2&&season!==3)p.line(x,y,x-2,y+6,'glass');else p.rect(x,y,2,1,season===3?'white':season===2?'gold':'red');}}
 for(const b of bubbles.slice(-12)){const [x,y]=stop(b.loc);ctx.font='11px Tahoma, sans-serif';const width=Math.ceil(ctx.measureText(b.text).width)+8;p.rect(x-width/2,y-47,width,16,'cream');p.line(x-width/2,y-47,x+width/2,y-47,'ink');ctx.fillStyle=PAL.ink;ctx.textAlign='center';ctx.fillText(b.text,Math.round(x),Math.round(y-35));}
}
const camera=document.createElement('select');camera.id='city-zoom';for(const [v,t]of [['auto',''],['1','1×'],['2','2×'],['3','3×']]){const o=document.createElement('option');o.value=v;o.textContent=t;camera.append(o);}cityReadout.append(camera);camera.onchange=()=>{zoom=camera.value;cityFit();focusLocation();};
cityFit=function(){const fit=Math.min(cityViewport.clientWidth/W,cityViewport.clientHeight/H),scale=zoom==='auto'?Math.max(.1,fit<1?fit:Math.min(3,Math.floor(fit))):Number(zoom);cityStage.style.width=(W*scale)+'px';cityStage.style.height=(H*scale)+'px';cityStage.classList.toggle('compact-city',W*scale<500);cityViewport.classList.toggle('pixel-scroll',zoom!=='auto');};
function focusLocation(){if(zoom==='auto')return;const [x,y]=stop(selected),scale=Number(zoom);cityViewport.scrollLeft=x*scale-cityViewport.clientWidth/2;cityViewport.scrollTop=y*scale-cityViewport.clientHeight/2;}
function pins(){for(const pin of $('pins').children){const id=Number(pin.dataset.select),[x,y]=stop(id);pin.dataset.number=String(id%6+1);pin.title=tr(LOCATIONS[id].name);pin.setAttribute('aria-label',tr(LOCATIONS[id].name));pin.style.left=(x/W*100)+'%';pin.style.top=((y+21)/H*100)+'%';}camera.options[0].textContent=T('전체','全体');camera.setAttribute('aria-label',T('지도 배율','地図の倍率'));if(lastSelection!==selected){lastSelection=selected;focusLocation();}}
paintDistrict=landscape;paintScene=paint;const beforeRender=render;render=function(){beforeRender();pins();};cityFit();pins();paint(ambientClock);
window.pixelCity={canvas,point,stop,lots,districtPieces,sprites:SPRITES,palette:PAL,snapshot:()=>({depths:lastDepths,actors:lastActors,sales:lastSales,scene:key})};

