/* Visual actors sample real receipts; their movement never advances the economy. */
const traffic={map:-1,state:null,last:0,next:0,serial:0,agents:[],pending:new Map(),seen:new WeakMap(),bubbles:new Map(),stats:{}};
const dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
function setPath(a,path){a.path=path;a.segment=0;a.p=[...path[0]];}
function streetRoute(index){const upper=1.4,lower=8.4,J=1.25,routes=[[[ -18,upper],[26,upper]],[[26,upper],[-18,upper]],[[-18,lower],[J,lower],[J,upper],[26,upper]],[[26,lower],[J,lower],[J,upper],[-18,upper]],[[-18,upper],[J,upper],[J,lower],[26,lower]],[[26,lower],[-18,lower]]],route=routes[index%routes.length],forward=route.at(-1)[0]>route[0][0],lane=forward?.24:-.24;return route.map(([x,y],i)=>point(x+(x===J?lane:0),y+lane));}
function seedWalker(index,spread=false){const a={id:++traffic.serial,kind:'customer',role:'walk',loc:-1,speed:17+(index%4)*2,service:0,batch:null,blocked:0};setPath(a,streetRoute(index));if(spread){let remaining=130+(index*139)%800;while(remaining>0&&a.segment<a.path.length-1){const end=a.path[a.segment+1],d=dist(a.p,end);if(remaining<d){a.p=[a.p[0]+(end[0]-a.p[0])*remaining/d,a.p[1]+(end[1]-a.p[1])*remaining/d];break;}remaining-=d;a.p=[...end];a.segment++;}}if(traffic.agents.some(b=>dist(a.p,b.p)<24))return;traffic.agents.push(a);}
function resetTraffic(time){Object.assign(traffic,{map:selectedMap,state,agents:[],pending:new Map(),seen:new WeakMap(),bubbles:new Map(),last:time,next:time+4000,serial:0});for(let i=0;i<10;i++)seedWalker(i,true);}
function receipts(rows){for(const r of rows){if(LOCATIONS[r.loc]?.map!==selectedMap)continue;const bought=r.bought||[],seen=traffic.seen.get(r)||0;traffic.seen.set(r,bought.length);if(bought.length<=seen)continue;const group=traffic.pending.get(r.loc)||{n:0,value:0};for(let i=seen;i<bought.length;i++){group.n++;group.value+=bought[i].price;}traffic.pending.set(r.loc,group);}}
function admitBuyers(){for(const [loc,batch]of traffic.pending){if(!batch.n||traffic.agents.some(a=>a.loc===loc&&a.role==='buy'))continue;const [x,y]=lots[loc%6],target=point(x-.25,y+1.18),near=traffic.agents.filter(a=>a.role==='walk'&&Math.abs(fromScreen(...a.p)[1]-(y+1.4))<.48&&dist(a.p,target)<140).sort((a,b)=>dist(a.p,target)-dist(b.p,target))[0];if(!near)continue;const py=fromScreen(...near.p)[1];near.exit=near.path.at(-1)[0]>near.p[0]?26:-18;near.role='buy';near.loc=loc;near.batch={...batch};near.service=0;setPath(near,[[...near.p],point(x-.25,py),target]);traffic.pending.delete(loc);}}
function updateTraffic(time,rows,reserved=[]){if(traffic.map!==selectedMap||traffic.state!==state||time<traffic.last){resetTraffic(time);for(const r of rows)traffic.seen.set(r,(r.bought||[]).length);}receipts(rows);admitBuyers();let remaining=sceneMotion?Math.min(1000,Math.max(0,time-traffic.last)):0;traffic.last=time;
 while(remaining>0){const dt=Math.min(50,remaining);remaining-=dt;
 for(const a of traffic.agents){if(a.segment>=a.path.length-1){if(a.role==='buy'){a.service+=dt;if(a.service>700&&!a.receipted){traffic.bubbles.set(a.loc,{text:'+'+money(a.batch.value)+(a.batch.n>1?' · '+a.batch.n+T('건','件'):''),until:time+1800});a.receipted=true;}if(a.service>=1700){const [x,y]=lots[a.loc%6],lane=a.exit===26?.24:-.24;a.role='leave';setPath(a,[[...a.p],point(x-.25,y+1.4+lane),point(a.exit,y+1.4+lane)]);}}else a.done=true;continue;}
 const to=a.path[a.segment+1],d=dist(a.p,to),step=Math.min(d,a.speed*dt/1000),candidate=d<.001?[...to]:[a.p[0]+(to[0]-a.p[0])*step/d,a.p[1]+(to[1]-a.p[1])*step/d];
 const collision=traffic.agents.some(b=>b!==a&&!b.done&&dist(candidate,b.p)<10&&dist(candidate,b.p)<dist(a.p,b.p))||reserved.some(p=>dist(candidate,p)<11&&dist(candidate,p)<dist(a.p,p));
 if(collision){a.blocked+=dt;if(a.blocked>=400){const vx=(to[0]-a.p[0])/Math.max(1,d),vy=(to[1]-a.p[1])/Math.max(1,d);for(const side of [a.id%2?1:-1,a.id%2?-1:1]){const bypass=[a.p[0]-vy*side*2+vx*.2,a.p[1]+vx*side*2+vy*.2];if(!walkable(fromScreen(...bypass)))continue;if(traffic.agents.some(b=>b!==a&&!b.done&&dist(bypass,b.p)<10)||reserved.some(p=>dist(bypass,p)<11))continue;a.p=bypass;a.facing=[-vy*side,vx*side];break;}}continue;}a.blocked=0;a.facing=[candidate[0]-a.p[0],candidate[1]-a.p[1]];a.p=candidate;if(d<=step+.001)a.segment++;
 }
 traffic.agents=traffic.agents.filter(a=>!a.done);
 }
 if(sceneMotion&&time>=traffic.next&&traffic.agents.length<12){seedWalker(traffic.serial);traffic.next=time+3500;}
 for(const [loc,b]of traffic.bubbles)if(time>b.until)traffic.bubbles.delete(loc);
 traffic.stats={total:traffic.agents.length,buying:traffic.agents.filter(a=>a.role==='buy').length,pending:[...traffic.pending.values()].reduce((n,b)=>n+b.n,0),blocked:traffic.agents.filter(a=>a.blocked>0).length};
 return traffic.agents.filter(a=>a.p[0]>-18&&a.p[0]<W+18&&a.p[1]>-28&&a.p[1]<H+25);
}
function actorSprite(a,time){const using=a.role==='buy'&&a.segment>=a.path.length-1,dx=a.facing?.[0]??1,dy=a.facing?.[1]??1,dir=(dy<0?'n':'s')+(dx<0?'w':'e'),frame=sceneMotion&&!a.blocked?Math.floor(time/155+a.id)%4:0;return using?'customer-use':`customer-${['blue','leaf','gold'][a.id%3]}-${dir}-${frame}`;}
