/* B/G: financing changes liabilities and voting power, never operating profit. */
function refBorrow(f,amount,kind='loan'){const r=refFirm(f),w=refWorld();if(!['loan','bond'].includes(kind)||!int(amount,10000,2000000)||r.notes.length>=5||f.meta.credit<40||amount+r.notes.reduce((n,l)=>n+l.principal,0)>Math.max(0,companyEquity(f))*.6||w.bankCash<amount||state.ended)return false;w.bankCash-=amount;f.account.cash+=amount;const city=w.cities[refHome(f).map];r.notes.push({id:refId(),kind,principal:amount,rate:(kind==='bond'?.0015:.002)*city.interest,due:state.day+(kind==='bond'?180:60),missed:0});refPost(f,kind,amount,'financing');return true;}
function refRepay(f,id){const r=refFirm(f),n=r.notes.find(n=>n.id===id);if(!n||f.account.cash<n.principal)return false;f.account.cash-=n.principal;refWorld().bankCash+=n.principal;refPost(f,'principal-payment',-n.principal,'financing');r.notes=r.notes.filter(x=>x!==n);return true;}
function refInsurance(f,kind){const r=refFirm(f);if(!['equipment','stock','all'].includes(kind)||r.insurance)return false;const premium=kind==='all'?15000:8000;if(!refSpend(f,premium,'insurance-premium'))return false;refWorld().bankCash+=premium;r.insurance={kind,until:state.day+30,limit:100000,paid:0,deductible:5000};return true;}
function refClaim(f,kind,loss){const p=refFirm(f).insurance;if(!p||p.until<state.day||!['all',kind].includes(p.kind))return 0;const paid=Math.max(0,Math.min(loss-p.deductible,p.limit-p.paid,refWorld().bankCash));p.paid+=paid;refWorld().bankCash-=paid;refIncome(f,paid,'insurance-claim');return paid;}
function refRestructure(f,id){const r=refFirm(f),n=r.notes.find(n=>n.id===id);if(!n||!n.missed||n.restructured||f.account.cash<n.principal*.1)return false;const payment=Math.round(n.principal*.1);f.account.cash-=payment;n.principal-=payment;refWorld().bankCash+=payment;n.due=state.day+90;n.rate*=1.25;n.missed=0;n.restructured=true;f.meta.credit=Math.max(0,f.meta.credit-10);refPost(f,'restructuring-payment',-payment,'financing');return true;}
function refIssueEquity(f,qty,buyerId='market'){const r=refFirm(f),s=r.share,w=refWorld();if(!int(qty,10,500)||s.total+qty>5000||state.ended)return false;const buyer=buyerId==='market'?null:allFirms().find(v=>v.id===buyerId);if(buyerId!=='market'&&(!buyer||buyer.id===f.id))return false;const unit=Math.max(100,Math.round(companyEquity(f)/s.total)),cost=unit*qty,account=buyer?.account||w;if((buyer?account.cash:w.investorCash)<cost)return false;if(buyer){account.cash-=cost;refFirm(buyer).shareInvestments??={};refFirm(buyer).shareInvestments[f.id]=(refFirm(buyer).shareInvestments[f.id]||0)+qty;}else w.investorCash-=cost;f.account.cash+=cost;s.total+=qty;s.holders[buyerId]=(s.holders[buyerId]||0)+qty;s.listed=true;s.price=unit;refPost(f,'equity-issue',cost,'financing');return true;}
function refBuyback(f,qty){const s=refFirm(f).share;if(!int(qty,10,500)||(s.holders.market||0)<qty)return false;const cost=Math.round(Math.max(100,companyEquity(f)/s.total)*qty*1.1);if(f.account.cash<cost)return false;f.account.cash-=cost;refWorld().investorCash+=cost;s.holders.market-=qty;s.total-=qty;refPost(f,'share-buyback',-cost,'financing');return true;}
function refControl(f,otherId,strategy){const other=allFirms().find(v=>v.id===otherId);if(!other||other.id===f.id||!['density','premium','manufacturer','defensive'].includes(strategy))return false;const key=listingKey(other),votes=expansionFirm(f).holdings[key]?.qty||0;if(votes<=500)return false;refFirm(other).strategy.kind=strategy;refFirm(other).controller=f.id;refFirm(other).strategy.until=state.day+30;return true;}
function refSubsidiary(f,name,siteIds,budget){const r=refFirm(f);if(typeof name!=='string'||!name.trim()||name.length>24||!Array.isArray(siteIds)||!siteIds.length||new Set(siteIds).size!==siteIds.length||r.units.length>=10||!siteIds.every(id=>{const s=refSite(f,id);return s&&!s.owner&&!s.build;})||!int(budget,10000,2000000)||f.account.cash<budget)return false;f.account.cash-=budget;const id=refId(),unit={id,name:name.trim(),sites:[...siteIds],cash:budget,ownership:1,listed:false,profit:0,history:[],integration:7,transferPrice:1000};r.units.push(unit);for(const sid of siteIds)refSite(f,sid).owner=id;refPost(f,'subsidiary-capital',-budget,'internal');return id;}
function refUnitTransfer(f,from,to,amount){const r=refFirm(f),a=from===0?f.account:r.units.find(u=>u.id===from),b=to===0?f.account:r.units.find(u=>u.id===to);if(!a||!b||from===to||!int(amount,1000,2000000)||a.cash<amount)return false;if(from!==0&&to!==0&&(a.ownership<1||b.ownership<1))return false;a.cash-=amount;if(from===0){b.cash+=amount;b.parentLoan=(b.parentLoan||0)+amount;}else if(to===0){const repayment=Math.min(amount,a.parentLoan||0);a.parentLoan=Math.max(0,(a.parentLoan||0)-repayment);b.cash+=repayment+(amount-repayment)*a.ownership;refWorld().investorCash+=(amount-repayment)*(1-a.ownership);}else b.cash+=amount;refPost(f,'intragroup-transfer',0,'internal',0,{from,to,amount});return true;}
function refUnitIPO(f,id,percent){const r=refFirm(f),u=r.units.find(u=>u.id===id);if(!u||u.integration||!int(percent,5,40)||u.ownership-percent/100<.51)return false;const book=refUnitValue(f,u),value=Math.round((book+Math.max(0,u.history.slice(0,30).reduce((n,h)=>n+h.profit,0)/Math.max(1,Math.min(30,u.history.length)))*30)*percent/100);if(refWorld().investorCash<value)return false;refWorld().investorCash-=value;f.account.cash+=value;u.ownership-=percent/100;u.listed=true;refPost(f,'subsidiary-ipo',value,'financing');return true;}
function refUnitDissolve(f,id){const r=refFirm(f),u=r.units.find(u=>u.id===id);if(!u||u.ownership!==1)return false;f.account.cash+=u.cash;for(const site of r.sites)if(site.owner===id)site.owner=null;r.units=r.units.filter(v=>v!==u);refPost(f,'subsidiary-consolidation',u.cash,'internal');return true;}
function refFinanceDay(f){const r=refFirm(f);if(mgEnabled())mgDebtDay(f);for(const n of mgEnabled()?[]:r.notes){const interest=Math.round(n.principal*n.rate);companyExpense(f,interest);refWorld().bankCash+=interest;refPost(f,'debt-interest',-interest);if(n.due<=state.day){if(!refRepay(f,n.id)){n.missed++;f.meta.credit=Math.max(0,f.meta.credit-1);if(n.missed===1)refNotice(f,'차입 만기 · 상환/재조정 필요','借入満期・返済／再調整が必要','finance',n.id);}}}if(r.insurance?.until<state.day)r.insurance=null;
 const rows=f.id==='player'?state.live?.rows:f.ops.market?.rows,revenue=(rows||[]).reduce((n,x)=>n+x.revenue,0),cost=(rows||[]).reduce((n,x)=>n+x.cost,0),payroll=chainPayroll(f),rent=f.machines.reduce((n,m)=>n+companyRent(f,m),0),expenses=f.id==='player'?f.ops.expenseToday:(f.ops.market?.extra||0),profit=revenue-cost-payroll-rent-expenses;

 const cashChange=f.account.cash-r.daybook.openingCash,financing=r.daybook.financing,investing=r.daybook.investing,internal=r.daybook.internal||0,operating=cashChange-financing-investing-internal;r.reports.unshift({day:state.day,openingCash:r.daybook.openingCash,revenue,cost,payroll,rent,expenses,profit,cash:f.account.cash,assets:companyStockAssets(f)+f.account.cash,liabilities:f.bank.principal+f.bank.arrears+r.notes.reduce((n,x)=>n+x.principal,0)+r.bills.reduce((n,x)=>n+x.amount,0),equity:companyEquity(f),operating,financing,investing,internal,cashChange});r.reports=r.reports.slice(0,120);r.daybook={openingCash:f.account.cash,operating:0,financing:0,investing:0};
 for(const site of r.sites){site.metrics.salary=chainFirm(f).staff.filter(w=>w.site===site.id).reduce((n,w)=>n+w.salary*(1+site.policy.overtime*.3),0)*inflationFactor();site.metrics.overhead+=(rows||[]).filter(row=>f.machines.some(m=>m.loc===row.loc&&m.ref.hub===site.id)).reduce((n,row)=>n+row.rent,0)+(['drink','machine'].includes(site.kind)?2000:0)+site.original/3600;}for(const u of r.units){u.integration=Math.max(0,u.integration-1);u.profit=u.sites.reduce((n,id)=>n+((refSite(f,id)?.metrics.revenue||0)-(refSite(f,id)?.metrics.cost||0)-(refSite(f,id)?.metrics.salary||0)-(refSite(f,id)?.metrics.overhead||0)),0);u.history.unshift({day:state.day,profit:u.profit,cash:u.cash});u.history=u.history.slice(0,60);if(u.cash<5000)refNotice(f,'자회사 운영자금 부족','子会社の運転資金不足','group',u.id);}for(const s of r.sites){s.history.unshift({day:state.day,...s.metrics,cashFlow:s.cashFlow});s.history=s.history.slice(0,60);s.cashFlow=0;s.metrics={revenue:0,cost:0,salary:0,overhead:0,throughput:0,wait:0};}
}
