/* M/A/E/U: finite customers, remembered service and budgeted business policies. */
function refCustomer(map,index){const root=state.enterprise.operations.market,d=root.districts[map],city=refWorld().cities[map];if(!d||!city)return;const segment=Math.floor(enterpriseRandom()*4),origin=map*6+Math.floor(enterpriseRandom()*6),hour=(mgEnabled()?8:6)+Math.floor((state.live.elapsed/DAY_MS)*(mgEnabled()?12:18)),season=sceneSeason(),choices=[];
 for(const f of allFirms().filter(f=>!f.policy?.defeated))for(const m of f.machines){if(LOCATIONS[m.loc].map!==map)continue;const r=(f.id==='player'?state.live.rows:f.ops.market?.rows||[]).find(r=>r.loc===m.loc);if(!r)continue;r.attempted=d.attempted;const trust=refFirm(f).trust[m.loc]??50;for(const slot of m.slots){if(!slot.stock||!refSupports(m,slot.product)||beSlotBlocked(f,m,slot))continue;const p=PRODUCTS[slot.product],sku=refSKU(slot.sku),brand=sku&&refFirm(f).brands.find(b=>b.id===sku.brand),distance=Math.abs(m.loc-origin),paid=bePrice(f,m,slot,f.id==='player'?campaignPrice(slot,map):refClamp(Math.round(slot.price*f.meta.prices[map]/1500),800,4000));let fit=p.fit[LOCATIONS[origin].kind]||1;if(slot.product===4)fit*=[1,2,.8,.35][season];if(slot.product===5)fit*=[1,.45,1.3,2][season];if(slot.product===1&&hour<10)fit*=1.5;if(segment===0&&slot.product===0)fit*=1.3;if(segment===3&&slot.product===2)fit*=1.4;const age=sku?state.day-sku.launched:0,novelty=age<30?1.1:age>360?.85:1,priceScore=Math.exp((1-paid/(p.price*city.income*(sku?.volume||350)/350))*[2.8,1.7,1,.7][segment]),quality=1+(slot.quality||0)*[.03,.08,.16,.23][segment],awareness=(1+(brand?.awareness[map]||f.brand[map]||0)/250)*(brand?.position==='premium'?(segment>=2?1.2:.9):brand?.position==='value'?(segment===0?1.15:.95):1),repeat=.6+trust/125,score=beChoiceFactor(f,m,slot)*(f.id==='player'?complaintDemandFactor(m.loc):1)*fit*priceScore*quality*awareness*repeat*novelty*(f.policy?rivalSkillFactor():.65+state.reputation/200)*(.5+m.condition/200)*(m.ref.payment&&segment>1?1.12:1)/(1+distance*.7)/4;choices.push({f,m,slot,r,paid,score});}}
 let pick=enterpriseRandom()*(.45+choices.reduce((n,c)=>n+c.score,0)),chosen;for(const c of choices){pick-=c.score;if(pick<0){chosen=c;break;}}if(chosen){recordMarketSale(chosen.m,chosen.slot,chosen.r,index,chosen.paid,chosen.f.id==='player');d[chosen.f.id==='player'?'player':'rival']++;const r=refFirm(chosen.f);r.trust[chosen.m.loc]=Math.min(100,(r.trust[chosen.m.loc]||50)+.05);}else d.none++;
 for(const f of allFirms())for(const m of f.machines.filter(m=>LOCATIONS[m.loc].map===map)){const row=(f.id==='player'?state.live.rows:f.ops.market?.rows||[]).find(r=>r.loc===m.loc);if(!row)continue;row.attempted=d.attempted;if(chosen?.m!==m){row.lost[!m.stock?'stock':chosen?'competition':'price']++;if(!m.stock)refFirm(f).trust[m.loc]=Math.max(0,(refFirm(f).trust[m.loc]||50)-.03);}}
}
function refPolicy(f,site,patch){const s=refSite(f,site);if(!s||!patch||typeof patch!=='object')return false;const next={...s.policy,...patch};if(typeof next.enabled!=='boolean'||!int(next.min,0,500)||!int(next.target,next.min,1000)||!int(next.reserve,0,10000000)||!int(next.supplier,0,2)||!int(next.backup,0,2)||!int(next.markup,0,200)||!int(next.repair,0,100)||!int(next.overtime,0,2))return false;s.policy=next;return true;}
function refSavePolicy(f,site){const s=refSite(f,site),r=refFirm(f);if(!s||r.savedPolicies.length>=10)return false;r.savedPolicies.push({id:refId(),policy:{...s.policy}});return true;}
function refApplyPolicy(f,id,sites){const policy=refFirm(f).savedPolicies.find(p=>p.id===id);if(!policy||!Array.isArray(sites)||!sites.every(id=>refSite(f,id)))return false;for(const id of sites)refPolicy(f,id,policy.policy);return true;}
function refDelegate(f){const r=refFirm(f);if(r.delegation.day===state.day)return;r.delegation.day=state.day;r.delegation.spent=0;for(const s of r.sites.filter(s=>s.kind==='warehouse'&&!s.build&&s.policy.enabled)){const manager=chainFirm(f).staff.find(w=>w.id===s.manager&&!w.training&&w.fatigue<90);if(!manager){r.delegation.exceptions++;continue;}const policy=s.policy;if(state.day%7===0&&!chainFirm(f).staff.some(w=>w.site===s.id&&w.role==='logistics')&&f.account.cash>policy.reserve+5000&&r.delegation.spent+5000<=r.delegation.budget){const before=f.account.cash;if(refHireEmployee(f,'logistics',s.id))r.delegation.spent+=before-f.account.cash;}for(let p=0;p<6;p++){const qty=refSiteInventory(f,s.id).filter(b=>b.product===p).reduce((n,b)=>n+b.qty,0),pending=r.work.filter(j=>j.kind==='purchase'&&j.site===s.id&&j.product===p).reduce((n,j)=>n+j.qty,0);if(qty+pending>=policy.min)continue;const need=Math.min(200,policy.target-qty-pending),cost=need*PRODUCTS[p].cost;if(need<20||f.account.cash-cost<policy.reserve||r.delegation.spent+cost>r.delegation.budget)continue;const vendor=['aqua','sun','value'][policy.supplier],backup=['aqua','sun','value'][policy.backup];const before=f.account.cash;if(refOrder(f,vendor+':'+p,need,s.id,backup+':'+p))r.delegation.spent+=before-f.account.cash;}for(const m of f.machines.filter(m=>m.ref.hub===s.id)){const fee=chainWorkers(f,'technician',LOCATIONS[m.loc].map)?5000:15000;if(m.condition<policy.repair&&f.account.cash>=policy.reserve+fee&&r.delegation.spent+fee<=r.delegation.budget){const before=f.account.cash;if(chainRepair(f,m.loc))r.delegation.spent+=before-f.account.cash;}for(const slot of m.slots)slot.price=refClamp(Math.round(PRODUCTS[slot.product].cost*(1+policy.markup/100)),800,4000);}}}
function refGoal(f,kind){if(!['operator','manufacturer','regional','group','survivor'].includes(kind)||refFirm(f).goal.achieved)return false;refFirm(f).goal={kind,streak:0,achieved:false};return true;}
function refWorldDay(){const w=refWorld();for(const map of MAPS)if(!w.cities[map.id])w.cities.push({map:map.id,population:10000,income:1,employment:.92,wage:1,demand:1,interest:1,development:0});for(const city of w.cities){const activity=allFirms().flatMap(f=>f.machines).filter(m=>LOCATIONS[m.loc].map===city.map).length;city.development=refClamp(city.development+activity/2000,0,1);city.employment=refClamp(city.employment+(enterpriseRandom()-.5)*.01,.7,.99);city.income=refClamp(.6+city.employment*.45+city.development*.2,.7,1.4);city.wage=refClamp(.7+city.employment*.35+city.development*.2,.8,1.4);city.demand=city.income*(.8+city.employment*.2);city.interest=1+(1-city.employment)*2;city.population=Math.round(10000*(1+city.development));}
 for(const s of state.enterprise.chain.suppliers){const a=supplierAccount(s),extra=w.suppliers[s.id];if(a.cash<0&&!extra.closedUntil){extra.closedUntil=state.day+14;extra.health=0;refNotice(playerFirm(),'공급사 조업 중단 · 대체 거래처 확인','仕入先が操業停止・代替先を確認','supply');}if(extra.closedUntil&&extra.closedUntil<=state.day){const funding=Math.min(500000,w.investorCash);if(funding>0){w.investorCash-=funding;a.cash+=funding;extra.closedUntil=0;extra.health=60;extra.generation++;}}if(a.cash>2000000&&s.capacity<1000){a.cash-=200000;s.capacity+=s.kind==='drink'?50:1;extra.investment+=200000;}}
 refTenderDay();if(state.day%30===0)refTenderCreate();for(const f of allFirms().filter(f=>!f.policy?.defeated)){const r=refFirm(f),g=r.goal,profit=r.reports[0]?.profit||0,qualified=g.kind==='operator'?f.machines.length>=5&&profit>0:g.kind==='manufacturer'?r.stats.wholesale>=1000:g.kind==='regional'?new Set(f.machines.map(m=>LOCATIONS[m.loc].map)).size>=3&&profit>0:g.kind==='group'?r.units.length>=2&&profit>0:state.day>=365&&companyEquity(f)>0;g.streak=qualified?g.streak+1:0;if(g.streak>=30&&!g.achieved){g.achieved=true;refNotice(f,'사업 목표 달성','事業目標達成','reports');}refDelegate(f);}}
function refAI(f){if(f.policy?.defeated)return;const r=refFirm(f),hub=refHome(f);if(!hub)return;if(r.strategy.until<=state.day){const target=playerFirm().machines.slice().sort((a,b)=>Number(a.stock>0)-Number(b.stock>0))[0];r.strategy.target=target?LOCATIONS[target.loc].map:hub.map;r.strategy.budget=Math.max(0,Math.min([50000,100000,200000][runRules().aggression],f.account.cash*[.05,.1,.2][runRules().aggression]));r.strategy.spent=0;r.strategy.until=state.day+30;if(f.account.cash<100000)r.strategy.kind='defensive';refNotice(playerFirm(),`${companyNameFor(f.id,0)} · ${tr(MAPS[r.strategy.target].name)} 영업 확대`,`${companyNameFor(f.id,1)}・${MAPS[r.strategy.target].name[1]}で営業拡大`,'rivals');}
 if(state.day%14===0&&chainFirm(f).licenses.products>=2&&chainFirm(f).licenses.quality<2&&f.account.cash>300000)refResearch(f,'quality','aqua');const controlled=r.controller&&allFirms().find(v=>v.id===r.controller);if(controlled&&(expansionFirm(controlled).holdings[listingKey(f)]?.qty||0)<=500)r.controller=null;const target=r.strategy.target;
 if(r.strategy.kind!=='defensive'&&f.account.cash>150000&&r.strategy.spent+10000<=r.strategy.budget){if(refAdvertise(f,'house',target,10000))r.strategy.spent+=10000;f.meta.prices[target]=r.strategy.kind==='premium'?1650:1300;}
 for(const employee of chainFirm(f).staff)if(employee.satisfaction<50&&f.account.cash>150000)refRaise(f,employee.id,10);for(const p of r.projects.filter(p=>p.paused))if(f.account.cash>p.extra+100000)refResearchTopUp(f,p.id);
 if(!r.routes.length&&chainFirm(f).staff.some(w=>w.role==='restock'))refRoute(f,hub.id,r.vehicles[0]?.id,f.machines.filter(m=>m.ref.hub===hub.id).slice(0,12).map(m=>m.loc));
 if(state.day%7===0&&f.account.cash>300000){refTerms(f,'aqua',50,7);if(r.strategy.kind==='manufacturer')refReserveCapacity(f,'aqua',20);for(const t of refWorld().tenders.filter(t=>!t.closed&&t.until>state.day))if(f.account.cash>t.min+200000)refBid(f,t.id,t.min+10000);}
}
