/* One working surface: persistent navigation, compact ledgers and explicit orders. */
const refPanel=document.createElement('section');refPanel.id='reference-panel';refPanel.hidden=true;deskNodes.reference=refPanel;deskContent.append(refPanel);
DESK_TABS.push(['business',B('사업 규칙 전환','事業ルール移行'),()=>!refEnabled()]);
let refDesk='sites';const refInputs={};
const REF_DESKS=[['sites',B('사업장','事業所')],['logistics',B('배송','配送')],['people',B('인사','人事')],['supply',B('구매 계약','仕入契約')],['products',B('상품','商品')],['production',B('공장','工場')],['research',B('개발','開発')],['equipment',B('기기 수명','機械寿命')],['contracts',B('시설 계약','施設契約')],['finance',B('자금','資金')],['group',B('기업집단','企業グループ')],['reports',B('경영 분석','経営分析')]];
const REF_ROUTES={sites:'sites',logistics:'logistics',people:'staff',supply:'supply',products:'products',production:'manufacture',research:'research',equipment:'maintenance',contracts:'contracts',finance:'finance',group:'group',reports:'reports',policies:'policies'};
const REF_MENU_ADDITIONS=[['sites',B('사업장','事業所')],['logistics',B('물류','物流')],['products',B('상품','商品')],['maintenance',B('기기 정비','機械整備')],['contracts',B('시설 계약','施設契約')],['group',B('기업집단','企業グループ')],['reports',B('경영 분석','経営分析')]];
for(const tab of REF_MENU_ADDITIONS)DESK_TABS.push([...tab,()=>refEnabled()]);
function refOpenDesk(id){selectDesk(REF_ROUTES[id]||'reports');}
function refButton(action,label,arg='',off=false){return `<button data-ref-action="${action}" data-arg="${esc(String(arg))}" ${disabled(off||state.ended)}>${label}</button>`;}
function refField(id,label,choices,empty=T('선택 가능한 항목 없음','選択可能な項目なし')){const value=choices.some(([v])=>String(v)===String(refInputs[id]))?refInputs[id]:choices[0]?.[0]??'';refInputs[id]=value;return `<label>${label} <select data-ref-input="${id}" id="ref-${id}" ${disabled(!choices.length)}>${choices.length?choices.map(([v,text])=>`<option value="${esc(String(v))}" ${String(v)===String(value)?'selected':''}>${esc(String(text))}</option>`).join(''):`<option value="">${empty}</option>`}</select></label>`;}

function refNumber(id,label,value,min=1,max=1000000){return `<label>${label} <input data-ref-input="${id}" id="ref-${id}" type="number" value="${refInputs[id]??value}" min="${min}" max="${max}"></label>`;}
function refValue(id,fallback){return refInputs[id]??document.querySelector('#ref-'+id)?.value??fallback;}
function refTable(headers,rows){return enterpriseTable(headers,rows.map(cells=>`<tr>${cells.map(c=>`<td>${c}</td>`).join('')}</tr>`));}
function refSiteChoices(f,kind){return refFirm(f).sites.filter(s=>!s.closed&&(!kind||s.kind===kind)).map(s=>[s.id,`#${s.id} ${tr(refName(s.kind))} · ${tr(MAPS[s.map].name)}`]);}
function refLabel(key){const labels={warehouse:B('배송 거점','配送拠点'),research:B('연구소','研究所'),drink:B('음료 공장','飲料工場'),machine:B('기기 공장','機械工場'),water:B('용수','用水'),concentrate:B('원액','原液'),package:B('용기','容器'),steel:B('금속','金属'),electronics:B('전자 부품','電子部品'),purchase:B('상품 입고','商品入荷'),material:B('원자재 입고','原材料入荷'),production:B('생산','生産'),route:B('배송 운행','配送運行'),recruit:B('이직 대기','転職待ち'),retrofit:B('개조','改造'),replacement:B('기기 교체','機械交換'),relocation:B('이전','移転'),cold:B('냉각','冷却'),hot:B('가열','加熱'),payment:B('전자 결제','電子決済'),telemetry:B('원격 재고','遠隔在庫'),overhaul:B('분해 정비','分解整備'),density:B('상권 집중','商圏集中'),premium:B('고급화','高級化'),manufacturer:B('제조 확대','製造拡大'),defensive:B('현금 보전','現金確保')};return labels[key]?tr(labels[key]):key;}
function renderReference(){if(!refEnabled()&&deskTab!=='business')return;if(refEnabled()){const selected=Object.entries(REF_ROUTES).find(([,tab])=>tab===deskTab);if(!selected)return;refDesk=selected[0];}for(const [k,n] of Object.entries(deskNodes))n.hidden=k!=='reference'&&!(deskTab==='finance'&&['bank','enterprise'].includes(k));deskMap.hidden=true;if(!refEnabled()){patchPanel(refPanel,`<h3>${T('사업 규칙 전환','事業ルール移行')}</h3><p>${T('사업장·거래 계약 규칙으로 전환합니다. 전환 전 저장은 별도로 보존됩니다.','事業所・取引契約ルールに移行。移行前のセーブは別途保存されます。')}</p>${refButton('migrate',T('규칙 적용','ルールを適用'))}`);return;}
 const f=playerFirm(),r=refFirm(f),c=chainFirm(f),siteChoices=refSiteChoices(f),hubs=refSiteChoices(f,'warehouse'),skuChoices=refCatalog().filter(s=>!s.retired).map(s=>[s.id,tr(s.name)+' / '+(s.volume||350)+' ml']),machineChoices=f.machines.map(m=>[m.loc,tr(LOCATIONS[m.loc].short)]),vendorChoices=state.enterprise.chain.suppliers.filter(s=>s.kind==='drink').map(s=>[s.id,chainSupplierName(s.id)]);
 let html=`<h3>${tr(DESK_TABS.find(d=>d[0]===deskTab)[1])}</h3>`;
 if(refDesk==='sites'){
  html+=`<div class="expansion-form">${refField('site-kind',T('유형','種類'),['warehouse','research','drink','machine'].map(k=>[k,refLabel(k)]))}${refField('map',T('상권','商圏'),MAPS.map(m=>[m.id,tr(m.name)]))}${refButton('site-build',T('건설 발주','建設発注'),'',!!refBuildRequirement(f,refValue('site-kind','warehouse')))}</div>`;
  html+=refRequirementUI('build',refBuildRequirement(f,refValue('site-kind','warehouse')));
  html+=refTable([T('사업장','事業所'),T('장부가 / 입고량','簿価／在庫量'),T('상태','状態'),T('업무','業務')],r.sites.filter(s=>!s.closed).map(s=>[`#${s.id} ${refLabel(s.kind)} · ${tr(MAPS[s.map].name)}`,`${money(s.book)} / ${refSiteUsed(f,s.id)} / ${s.capacity}`,s.build?chainDays(s.build)+T('일','日'):T('운영','稼働'),refButton('site-close',T('매각','売却'),s.id)]));
 }
 if(refDesk==='policies'){
  html+=refTable([T('사업장','事業所'),T('발주점 / 목표 재고','発注点／目標在庫'),T('자동 발주','自動発注')],r.sites.filter(s=>s.kind==='warehouse'&&!s.closed).map(s=>[`#${s.id} · ${tr(MAPS[s.map].name)}`,`${s.policy.min} / ${s.policy.target}`,refButton('policy-toggle',s.policy.enabled?T('중지','停止'):T('적용','適用'),s.id)]));
  html+=`<div class="expansion-form">${refField('policy-site',T('사업장','事業所'),hubs)}${refNumber('policy-min',T('발주점','発注点'),40,0,500)}${refNumber('policy-target',T('목표 재고','目標在庫'),160,0,1000)}${refField('policy-supplier',T('주 공급사','主仕入先'),[[0,'Aqua Drinks'],[1,'Sun Beverage'],[2,'Value Drinks']])}${refField('policy-backup',T('예비 공급사','予備仕入先'),[[1,'Sun Beverage'],[0,'Aqua Drinks'],[2,'Value Drinks']])}${refNumber('policy-budget',T('일 위임 예산 ($)','日次委任予算 ($)'),200,1,5000)}${refNumber('policy-reserve',T('현금 유보 ($)','現金留保 ($)'),100,0,10000)}${refNumber('policy-markup',T('원가 가산율 (%)','原価加算率 (%)'),50,0,200)}${refNumber('policy-repair',T('정비 기준 (%)','整備基準 (%)'),35,0,100)}${refNumber('policy-overtime',T('연장 근무','残業'),0,0,2)}${refButton('policy-save',T('규정 저장·적용','規定保存・適用'))}${refButton('policy-all',T('전체 거점 적용','全拠点に適用'))}</div>`;
 }
 if(refDesk==='logistics'){
  html+=`<div class="expansion-form">${refField('hub',T('거점','拠点'),hubs)}${refField('vehicle-type',T('차종','車種'),[['van',T('밴 $60','バン $60')],['cold',T('냉장차 $100','冷蔵車 $100')],['truck',T('트럭 $160','トラック $160')]])}${refButton('vehicle-buy',T('구매','購入'))}${refButton('vehicle-lease',T('60일 리스','60日リース'))}</div>`;
  html+=refTable([T('차량 / 거점','車両／拠点'),T('적재 / 상태','積載／状態'),T('경로','ルート')],r.vehicles.map(v=>[`#${v.id} / #${v.hub}`,`${v.capacity} / ${v.busy?chainDays(v.busy)+T('일','日'):T('대기','待機')}`,refButton('route-auto',T('담당 기기 경로 편성','担当機械のルート編成'),v.id)+refButton('route-run',T('출발','出発'),v.id)]));
  html+=`<div class="expansion-form">${refField('move-machine',T('기기','機械'),machineChoices)}${refField('move-hub',T('거점','拠点'),hubs)}${refButton('machine-hub',T('담당 변경','担当変更'))}</div>`;
  html+=`<div class="expansion-form">${refField('transfer-from',T('출발','出発'),hubs)}${refField('transfer-to',T('도착','到着'),hubs)}${refField('transfer-product',T('상품','商品'),PRODUCTS.map((p,i)=>[i,tr(p.name)]))}${refNumber('transfer-qty',T('수량','数量'),20,1,1000)}${refButton('transfer',T('재고 이동','在庫移動'))}</div>`;
  html+=refTable([T('배치 / 상품','ロット／商品'),T('거점 / 수량','拠点／数量'),T('기한 / 원가','期限／原価')],f.ops.warehouse.flatMap(w=>w.batches).map(b=>[`#${b.id} ${esc(refSKU(b.sku)?tr(refSKU(b.sku).name):tr(PRODUCTS[b.product].name))}`,`#${b.hub} / ${b.qty}`,`D${b.expires} / ${money(b.value)}`]));
 }
 if(refDesk==='people'){
  html+=`<div class="expansion-form">${refField('role',T('직무','職務'),['collect','restock','logistics','technician','drink','machine','research'].map(k=>[k,tr(chainRole(k).slice(1))]))}${refField('staff-site',T('사업장','事業所'),siteChoices)}${refField('skill',T('숙련','熟練'),[[1,'1 / $5'],[2,'2 / $20'],[3,'3 / $45']])}${refButton('hire',T('채용','採用'))}</div>`;
  html+=refTable([T('직원 / 직무','社員／職務'),T('사업장 / 급여','事業所／給与'),T('숙련 / 피로 / 만족','熟練／疲労／満足'),T('인사','人事')],c.staff.map(w=>[`#${w.id} ${tr(chainRole(w.role).slice(1))}`,`#${w.site} / ${money(w.salary)}`,`${w.skill.toFixed(1)} / ${Math.round(w.fatigue)} / ${Math.round(w.satisfaction)}`,refButton('staff-assign',T('선택 사업장 배치','選択事業所へ配置'),w.id)+refButton('raise',T('급여 +10%','給与 +10%'),w.id)+refButton('manager',T('관리자 임명','管理者任命'),w.id)+refButton('train',T('교육','研修'),w.id)]));
  html+=refTable([T('경쟁사 직원','競合の社員'),T('숙련 / 유지 상태','熟練／定着状態'),T('채용 제안','採用提案')],rivalFirms().filter(f=>!f.policy.defeated).flatMap(other=>chainFirm(other).staff.filter(w=>w.skill>=1).slice(0,5).map(w=>[`${companyName(other)} #${w.id}`,`${w.skill.toFixed(1)} / ${Math.round(w.satisfaction)}`,refButton('poach',money(w.salary*20),other.id+':'+w.id)])));
 }
 if(refDesk==='supply'){
  html+=`<div class="expansion-form">${refField('sku',T('상품','商品'),skuChoices)}${refNumber('qty',T('수량','数量'),100,20,1000)}${refField('order-hub',T('입고 거점','入荷拠点'),hubs)}${refButton('order',T('발주','発注'))}</div>`;
  html+=`<div class="expansion-form">${refField('vendor',T('공급사','仕入先'),vendorChoices)}${refField('minimum',T('최소 수량','最小数量'),[[20,'20'],[50,'50'],[100,'100'],[200,'200']])}${refField('credit-days',T('결제 기일','支払期日'),[[0,T('선불','前払')],[7,T('7일','7日')],[14,T('14일','14日')],[30,T('30일','30日')]])}${refButton('terms',T('60일 계약','60日契約'))}${refButton('reserve',T('일 20개 우선 공급','日20本の優先供給'))}</div>`;
  html+=refTable([T('거래처','取引先'),T('최소 수량 / 할인','最小数量／割引'),T('결제 / 만료','支払／満了')],r.purchaseTerms.map(t=>[chainSupplierName(t.supplier),`${t.min} / ${Math.round(t.discount*100)}%`,`${t.days} / D${t.until}`]));
  html+=refTable([T('우선 공급','優先供給'),T('예약 / 오늘 사용','予約／本日使用'),T('미사용 비용','未使用費用')],r.reservations.map(x=>[chainSupplierName(x.supplier),`${x.qty} / ${x.used}`,money(Math.max(0,x.qty-x.used)*30)]));
  html+=`<div class="expansion-form">${refField('import-product',T('수입 상품','輸入商品'),PRODUCTS.map((p,i)=>[i,tr(p.name)]))}${refButton('import',T('100개 수입 · 5일','100本輸入・5日'))}</div>`;
 }
 if(refDesk==='products'){
  html+=`<div class="expansion-form"><label>${T('브랜드명','ブランド名')} <input data-ref-input="brand-name" id="ref-brand-name" maxlength="24" value="${esc(String(refInputs['brand-name']||'HC'))}"></label>${refField('position',T('포지션','位置付け'),[['value',T('저가','低価格')],['standard',T('표준','標準')],['premium',T('고급','高級')]])}${refButton('brand',T('브랜드 등록 $10','ブランド登録 $10'))}</div>`;
  html+=`<div class="expansion-form">${refField('brand',T('브랜드','ブランド'),r.brands.map(b=>[b.id,b.name]))}${refField('product',T('품목','品目'),PRODUCTS.map((p,i)=>[i,tr(p.name)]))}${refField('volume',T('용량','容量'),[[250,'250 ml'],[350,'350 ml'],[500,'500 ml']])}${refButton('trial',T('시험 출시 $15','試験発売 $15'))}${refButton('launch',T('정식 출시 $50','正式発売 $50'))}${refField('ad-map',T('광고 상권','広告商圏'),MAPS.map(m=>[m.id,tr(m.name)]))}${refButton('advertise',T('광고 $10','広告 $10'))}</div>`;
  html+=refTable([T('자사 상품','自社商品'),T('판매 / 매출총이익','販売／売上総利益'),T('상태','状態')],r.products.map(id=>refSKU(id)).filter(Boolean).map(s=>[esc(tr(s.name)),`${s.sold||0} / ${money((s.revenue||0)-(s.cost||0))}`,s.trialUntil?`D${s.trialUntil} ${T('시험 판매 종료','試験販売終了')}`:T('정식 판매','正式販売')]));
  html+=`<div class="expansion-form">${refField('sku-machine',T('기기','機械'),machineChoices)}${refField('slot',T('슬롯','スロット'),[0,1,2,3].map(i=>[i,String(i+1)]))}${refField('slot-sku',T('상품','商品'),skuChoices)}${refButton('sku-set',T('빈 슬롯 상품 지정','空スロットの商品指定'))}</div>`;
 }
 if(refDesk==='production'){
  const factories=r.sites.filter(s=>['drink','machine'].includes(s.kind)&&!s.closed);html+=`<div class="expansion-form">${refField('factory',T('공장','工場'),factories.map(s=>[s.id,`#${s.id} ${refLabel(s.kind)}${s.build?' · '+T('건설 중','建設中'):''}`]),T('공장 건설 필요','工場建設が必要'))}${refField('material',T('원재료','原材料'),['water','concentrate','package','steel','electronics'].map(k=>[k,refLabel(k)]))}${refNumber('raw-qty',T('수량','数量'),100,1,1000)}${refField('raw-quality',T('등급','等級'),[0,1,2,3].map(i=>[i,String(i)]))}${refButton('raw',T('원재료 발주','原材料発注'),'',!refSite(f,Number(refValue('factory')))||!!refSite(f,Number(refValue('factory')))?.build)}</div>`;
  const factory=refSite(f,Number(refValue('factory'))),isMachine=factory?.kind==='machine';
  html+=`<div class="expansion-form">${refField('production-sku',T('생산 상품','生産商品'),isMachine?[]:refOwnProducts(f).map(s=>[s.id,tr(s.name)+' / '+(s.volume||350)+' ml']),isMachine?T('기기 생산 · 음료 선택 불필요','機械生産・飲料の選択不要'):T('자사 음료 출시 필요','自社飲料の発売が必要'))}${refNumber('production-qty',T('생산량','生産量'),isMachine?1:100,1,isMachine?1:500)}${refButton('produce',T('생산 지시','生産指示'),'',!!refProductionRequirement(f,Number(refValue('factory')),refValue('production-sku'),Number(refValue('production-qty',isMachine?1:100))))}${refField('stage',T('증설 공정','増設工程'),[[0,T('배합 / 가공','調合／加工')],[1,T('충전 / 조립','充填／組立')],[2,T('검사 / 포장','検査／梱包')]])}${refButton('process',T('공정 증설','工程増設'),'',!factory||!!factory.build)}</div>`;
  html+=refRequirementUI('production',refProductionRequirement(f,Number(refValue('factory')),refValue('production-sku'),Number(refValue('production-qty',isMachine?1:100))));
  html+=refTable([T('공장','工場'),T('공정 능력','工程能力'),T('원재료','原材料'),T('처리 인력','処理人員')],factories.map(s=>[`#${s.id}`,s.process.join(' / '),r.materials.filter(b=>b.site===s.id).map(b=>refLabel(b.material)+': '+b.qty).join(', '),refStaffPower(f,s.kind,s.id).toFixed(2)]));
  html+=refTable([T('생산 실적','生産実績'),T('재료 / 인건비','材料／人件費'),T('단위 원가','単位原価')],r.analytics.slice(0,10).map(a=>[`D${a.day} / ${a.qty}`,`${money(a.material)} / ${money(a.labor)}`,money(a.unit)]));
 }
 if(refDesk==='research'){
  html+=`<div class="expansion-form">${refField('research-key',T('과제','課題'),['quality','products','efficiency','logistics'].map(k=>[k,tr(chainResearchName(k))]))}${refField('research-vendor',T('협력사','提携先'),state.enterprise.chain.suppliers.map(s=>[s.id,chainSupplierName(s.id)]))}${refButton('research',T('공동 개발','共同開発'))}${refButton('research-exclusive',T('60일 독점 개발','60日独占開発'))}</div>`;
  html+=refTable([T('과제 / 단계','課題／段階'),T('진행 / 집행 예산','進捗／執行予算'),T('조치','処置')],r.projects.map(p=>[`${tr(chainResearchName(p.key))} ${p.tier} / ${p.complete?T('완료','完了'):[T('설계','設計'),T('시제품','試作品'),T('검증','検証')][p.stage]}`,`${Math.round(p.progress/p.duration*100)}% / ${money(p.spent)} / ${money(p.budget)}`,p.paused?refButton('top-up',T('추가 투자 ','追加投資 ')+money(p.extra),p.id):p.exclusive?`D${p.rightsUntil}`:'—']));
  html+=`<div class="expansion-form">${refField('license-firm',T('기술 제공사','技術提供会社'),rivalFirms().map(f=>[f.id,companyName(f)]))}${refButton('license',T('선택 과제 기술 도입','選択課題の技術導入'))}</div>`;
 }
 if(refDesk==='equipment'){
  html+=`<div class="expansion-form">${refField('equipment',T('기기','機械'),machineChoices)}${refField('upgrade',T('개조','改造'),['cold','hot','payment','telemetry','overhaul'].map(k=>[k,refLabel(k)]))}${refButton('retrofit',T('개조 발주','改造発注'))}${refButton('replace',T('보유 기기로 교체','所有機械と交換'))}${refButton('used',T('중고 교체 $100','中古交換 $100'))}${refButton('machine-lease',T('리스 교체 $30','リース交換 $30'))}${refField('relocation',T('이전 입지','移転先'),refRelocationSites(f).map(s=>[s.loc,tr(LOCATIONS[s.loc].short)]),T('계약한 빈 입지 없음','契約済みの空き立地なし'))}${refButton('relocate',T('이전 $20','移転 $20'),'',!!refRelocationRequirement(f,Number(refValue('equipment')),Number(refValue('relocation'))))}</div>`;
  html+=refRequirementUI('relocation',refRelocationRequirement(f,Number(refValue('equipment')),Number(refValue('relocation'))));
  html+=refTable([T('기기','機械'),T('사용일 / 신뢰성','使用日／信頼性'),T('장부가 / 상태','簿価／状態')],f.machines.map(m=>[tr(LOCATIONS[m.loc].short),`${m.ref.age} / ${Math.round(m.ref.reliability*100)}%`,`${money(m.ref.book)} / ${m.ref.downtime?T('정지','停止'):T('가동','稼働')}`]));
 }
 if(refDesk==='contracts'){
  html+=`<div class="expansion-form">${refField('contract-machine',T('기기','機械'),machineChoices)}${refField('contract-kind',T('계약','契約'),[['fixed',T('고정 임대료','固定賃料')],['share',T('임대료 50% + 매출 15%','賃料50% + 売上15%')],['service',T('임대료 85% / 가동 기준 95%','賃料85%／稼働基準95%')]])}${refButton('contract',T('60일 계약','60日契約'))}${refField('provider',T('위탁 운영사','運営委託先'),rivalFirms().map(f=>[f.id,companyName(f)]))}${refButton('outsource',T('운영 위탁 $10','運営委託 $10'))}</div>`;
  html+=refTable([T('입지','立地'),T('서비스 / 기준','サービス／基準'),T('만료 / 보증금','満了／保証金')],r.contracts.map(c=>[tr(LOCATIONS[c.loc].short),`${c.score.toFixed(1)} / ${c.target}`,`D${c.until} / ${money(c.deposit)}`]));
  html+=refTable([T('시설 묶음 입찰','施設一括入札'),T('마감 / 최저가','締切／最低額'),T('입찰','入札')],refWorld().tenders.filter(t=>!t.closed).map(t=>[t.locs.map(l=>tr(LOCATIONS[l].short)).join(' / '),`D${t.until} / ${money(t.min)}`,refButton('bid',T('최저가 +$10 예치','最低額 +$10 預託'),t.id)]));
 }
 if(refDesk==='finance'){
  html+=`<div class="expansion-form">${refNumber('loan',T('조달 금액 ($)','調達額 ($)'),100,10,2000)}${refButton('loan',T('60일 대출','60日融資'))}${refButton('bond',T('180일 회사채','180日社債'))}${refButton('insurance',T('보험 $15 / 30일','保険 $15／30日'))}${refButton('equity',T('100주 신주 발행','新株100株発行'))}${refButton('buyback',T('100주 자사주 매입','自社株100株買戻し'))}</div>`;
  html+=refTable([T('차입','借入'),T('원금 / 일 금리','元金／日利'),T('만기 / 조치','満期／処置')],r.notes.map(n=>[`#${n.id}`,`${money(n.principal)} / ${(n.rate*100).toFixed(2)}%`,`D${n.due} ${refButton('repay',T('상환','返済'),n.id)} ${refButton('restructure',T('재조정','再調整'),n.id)}`]));
  html+=refTable([T('미지급금','未払金'),T('기일','期日'),T('금액','金額')],r.bills.map(b=>[esc(chainSupplierName(b.to)),`D${b.due}`,money(b.amount)]));
  html+=row(T('창업자 의결권','創業者の議決権'),(r.share.owner/r.share.total*100).toFixed(1)+'%');
 }
 if(refDesk==='group'){
  html+=`<div class="expansion-form">${refField('unit-site',T('분리 사업장','分離事業所'),siteChoices)}${refNumber('unit-budget',T('출자 ($)','出資 ($)'),100,10,2000)}${refButton('subsidiary',T('자회사 설립','子会社設立'))}</div>`;
  html+=refTable([T('회사 / 지분','会社／持分'),T('현금 / 본사 차입 / 통합 잔여일','現金／本社借入／統合残日数'),T('거래','取引')],r.units.map(u=>[`${esc(u.name)} / ${Math.round(u.ownership*100)}%`,`${money(u.cash)} / ${money(u.parentLoan||0)} / ${u.integration}`,refButton('unit-fund',T('$10 출자','$10 出資'),u.id)+refButton('unit-return',T('$10 회수','$10 回収'),u.id)+refButton('unit-ipo',T('20% 공개 매각','20% 公開売却'),u.id)+refButton('unit-dissolve',T('본사 통합','本社へ統合'),u.id)+refExtraButton('unit-divest',T('선택 경쟁사에 매각','選択競合に売却'),u.id)]));
  html+=`<div class="expansion-form">${refField('control-firm',T('지배 대상','支配対象'),rivalFirms().map(f=>[f.id,companyName(f)]))}${refField('strategy',T('사업 전략','事業戦略'),['density','premium','manufacturer','defensive'].map(k=>[k,refLabel(k)]))}${refButton('control',T('과반 지분 경영권 행사','過半数持分の経営権行使'))}</div>`;
 }
 if(refDesk==='reports'){
  html+=refTable([T('일자','日付'),T('매출 / 원가','売上／原価'),T('영업 손익','営業損益'),T('영업 / 투자 / 재무 현금','営業／投資／財務キャッシュ')],r.reports.slice(0,30).map(x=>[`D${x.day}`,`${money(x.revenue)} / ${money(x.cost)}`,money(x.profit),`${money(x.operating)} / ${money(x.investing)} / ${money(x.financing)}`]));
  html+=refTable([T('상권','商圏'),T('수요 / 소득 / 임금','需要／所得／賃金'),T('고용률','雇用率')],refWorld().cities.map(c=>[tr(MAPS[c.map].name),`${c.demand.toFixed(2)} / ${c.income.toFixed(2)} / ${c.wage.toFixed(2)}`,Math.round(c.employment*100)+'%']));
  html+=`<div class="expansion-form">${refField('goal',T('사업 목표','事業目標'),[['operator',T('5대 흑자 운영','5台黒字運営')],['manufacturer',T('도매 1,000개','卸売1,000本')],['regional',T('3상권 흑자','3商圏黒字')],['group',T('자회사 2곳 흑자','子会社2社黒字')],['survivor',T('1년 생존','1年間存続')]])}${refButton('goal',T('목표 선택','目標選択'))}</div>`+row(T('목표 유지 / 달성','目標維持／達成'),`${r.goal.streak} / ${r.goal.achieved?T('달성','達成'):'—'}`);
 }
 html+=refExtraUI(f);
 if(r.work.length)html+=refTable([T('작업','作業'),T('사업장','事業所'),T('남은 일수 / 단계','残日数／段階')],r.work.slice(0,30).map(j=>[refLabel(j.kind),`#${j.site||'—'}`,j.kind==='production'?`${j.stage+1}/3 · ${Math.round(j.progress/j.duration*100)}%`:chainDays(Math.max(0,j.remaining))]));
 if(r.notices.length)html+=`<h4>${T('업무 통지','業務通知')}</h4>`+r.notices.slice(0,8).map(n=>`<p>D${n.day} ${esc(tr(n.text))} <button data-ref-desk="${REF_DESKS.some(d=>d[0]===n.desk)?n.desk:'reports'}">${T('확인','確認')}</button></p>`).join('');patchPanel(refPanel,html);
}
const refSelectDesk=selectDesk;selectDesk=function(tab){refSelectDesk(tab);renderReference();};
const refUpdateDesk=updateDesk;updateDesk=function(){refUpdateDesk();renderReference();};
document.addEventListener('change',event=>{const input=event.target.closest('[data-ref-input]');if(input){refInputs[input.dataset.refInput]=input.value;if(input.dataset.refInput==='factory'&&refSite(playerFirm(),Number(input.value))?.kind==='machine')refInputs['production-qty']=1;renderReference();}});
document.addEventListener('input',event=>{const input=event.target.closest('[data-ref-input="production-qty"]');if(input){refInputs['production-qty']=input.value;renderReference();}});
document.addEventListener('click',event=>{const tab=event.target.closest('[data-ref-desk]');if(tab){refOpenDesk(tab.dataset.refDesk);return;}const button=event.target.closest('[data-ref-action]');if(!button||button.disabled)return;const a=button.dataset.refAction,arg=button.dataset.arg;if(a==='migrate'){refInitialize();refSeedCatalog();save();selectDesk('policies');return;}if(!refEnabled()||state.ended)return;const f=playerFirm(),r=refFirm(f),v=(id,otherwise)=>refValue(id,otherwise),n=(id,otherwise)=>Number(v(id,otherwise));let ok=false;
 if(a==='site-build')ok=refBuildSite(f,v('site-kind','warehouse'),n('map',0));if(a==='site-close')ok=refCloseSite(f,+arg);if(a==='policy-toggle'){const s=refSite(f,+arg);ok=refPolicy(f,+arg,{enabled:!s.policy.enabled});}if(a==='policy-save'){const id=n('policy-site');ok=refPolicy(f,id,{min:n('policy-min',40),target:n('policy-target',160),overtime:n('policy-overtime',0),supplier:n('policy-supplier',0),backup:n('policy-backup',1),reserve:n('policy-reserve',100)*1000,markup:n('policy-markup',50),repair:n('policy-repair',35)});if(ok){const budget=n('policy-budget',200)*1000;if(int(budget,1000,5000000))r.delegation.budget=budget;refSavePolicy(f,id);}}if(a==='policy-all'){const last=r.savedPolicies.at(-1);ok=last&&refApplyPolicy(f,last.id,r.sites.filter(s=>s.kind==='warehouse'&&!s.closed).map(s=>s.id));}
 if(a==='vehicle-buy'||a==='vehicle-lease')ok=refVehicle(f,n('hub'),v('vehicle-type','van'),a==='vehicle-lease');if(a==='route-auto'){const vehicle=r.vehicles.find(v=>v.id===+arg);ok=refRoute(f,vehicle.hub,vehicle.id,f.machines.filter(m=>m.ref.hub===vehicle.hub).slice(0,12).map(m=>m.loc));}if(a==='route-run'){const route=r.routes.find(t=>t.vehicle===+arg);ok=route&&refDispatchRoute(f,route.id);}if(a==='machine-hub')ok=refAssignMachine(f,n('move-machine'),n('move-hub'));if(a==='transfer')ok=refTransferStock(f,n('transfer-from'),n('transfer-to'),n('transfer-product'),n('transfer-qty',20));
 if(a==='hire')ok=refHireEmployee(f,v('role'),n('staff-site'),n('skill',1));if(a==='staff-assign')ok=refAssignEmployee(f,+arg,n('staff-site'));if(a==='raise')ok=refRaise(f,+arg);if(a==='manager')ok=refAppointManager(f,+arg,n('staff-site'));if(a==='train')ok=chainTrain(f,+arg);if(a==='poach'){const [other,id]=arg.split(':');ok=refPoach(f,other,+id,n('staff-site'));}
 if(a==='order')ok=refOrder(f,v('sku'),n('qty',100),n('order-hub'));if(a==='terms')ok=refTerms(f,v('vendor'),n('minimum',20),n('credit-days',0));if(a==='reserve')ok=refReserveCapacity(f,v('vendor'),20);if(a==='import')ok=refImport(f,n('import-product'),100,n('order-hub'));
 if(a==='brand')ok=refBrand(f,v('brand-name','HC'),v('position','standard'));if(a==='trial'||a==='launch')ok=refLaunchProduct(f,n('product'),v('brand'),a==='trial',n('volume',350));if(a==='advertise')ok=refAdvertise(f,v('brand'),n('ad-map'),10000);if(a==='sku-set')ok=refSetSKU(f,n('sku-machine'),n('slot'),v('slot-sku'));
 if(a==='raw')ok=refRawOrder(f,v('material'),n('raw-qty',100),n('raw-quality',0),n('factory'));if(a==='produce')ok=refProduce(f,n('factory'),v('production-sku'),n('production-qty',100));if(a==='process')ok=refImproveProcess(f,n('factory'),n('stage'));
 if(a==='research'||a==='research-exclusive')ok=refResearch(f,v('research-key'),v('research-vendor'),a==='research-exclusive');if(a==='top-up')ok=refResearchTopUp(f,+arg);if(a==='license')ok=refLicense(f,v('license-firm'),v('research-key'));
 if(a==='retrofit')ok=refRetrofit(f,n('equipment'),v('upgrade'));if(['replace','used','machine-lease'].includes(a))ok=refReplace(f,n('equipment'),a==='used',a==='machine-lease');if(a==='relocate')ok=refRelocate(f,n('equipment'),n('relocation'));
 if(a==='contract')ok=refContract(f,n('contract-machine'),v('contract-kind'));if(a==='outsource')ok=refOutsource(f,n('contract-machine'),v('provider'));if(a==='bid'){const t=refWorld().tenders.find(t=>t.id===+arg);ok=refBid(f,+arg,t.min+10000);}
 if(a==='loan'||a==='bond')ok=refBorrow(f,n('loan',100)*1000,a);if(a==='repay')ok=refRepay(f,+arg);if(a==='restructure')ok=refRestructure(f,+arg);if(a==='insurance')ok=refInsurance(f,'all');if(a==='equity')ok=refIssueEquity(f,100);if(a==='buyback')ok=refBuyback(f,100);
 if(a==='subsidiary')ok=refSubsidiary(f,'HC '+(r.units.length+1),[n('unit-site')],n('unit-budget',100)*1000);if(a==='unit-fund')ok=refUnitTransfer(f,0,+arg,10000);if(a==='unit-return')ok=refUnitTransfer(f,+arg,0,10000);if(a==='unit-ipo')ok=refUnitIPO(f,+arg,20);if(a==='unit-dissolve')ok=refUnitDissolve(f,+arg);if(a==='control')ok=refControl(f,v('control-firm'),v('strategy'));if(a==='goal')ok=refGoal(f,v('goal'));
 if(!ok)toast(B('조건 불충족 · 자금·인력·재고·계약 확인','条件未達・資金・人員・在庫・契約を確認'));save();render();renderReference();
});
