/* Explicit mode boundary. Existing saves and regression fixtures retain their rules. */
const chainOldBuildForReference=buildFactory;
const launchBeforeReference=launchNew;
function launchReference(){launchBeforeReference();refInitialize();refSeedCatalog();save();render();}
const refOldOrder=companyOrder;companyOrder=function(f,p,qty,supplier){return refEnabled()?refOrder(f,['aqua','sun','value'][supplier]+':'+p,qty,refHome(f).id):refOldOrder(f,p,qty,supplier);};
const refOldResearch=chainResearch;chainResearch=function(f,key,supplier,exclusive=false){return refEnabled()?refResearch(f,key,supplier,exclusive):refOldResearch(f,key,supplier,exclusive);};
const refOldHire=chainHire;chainHire=function(f,role){if(!refEnabled())return refOldHire(f,role);const site=refFirm(f).sites.find(s=>!s.closed&&!s.build&&s.kind===(['drink','machine','research'].includes(role)?role:'warehouse'));return site?!!refHireEmployee(f,role,site.id):false;};
const refOldBuild=buildFactory;buildFactory=function(f,kind){return refEnabled()?!!refBuildSite(f,kind,refHome(f).map):refOldBuild(f,kind);};
const refOldRestock=companyRestock;companyRestock=function(f,m,emergency=false){if(!refEnabled())return refOldRestock(f,m,emergency);refInitializeMachine(f,m,refHome(f).id);if(refFirm(f).work.some(j=>j.kind==='route'&&j.stops.some(s=>s.loc===m.loc)))return 0;let moved=0;for(const s of m.slots){if(!refSupports(m,s.product))continue;const w=f.ops.warehouse[s.product],batches=refTake(w,Math.min(Math.max(0,20-moved),Math.max(0,Math.floor(companyCapacity(f,m)/4)-s.stock)),b=>b.hub===m.ref.hub&&(s.sku.startsWith('legacy:')||b.sku===s.sku));moved+=batches.reduce((n,b)=>n+b.qty,0);refSyncBucket(w);refAdd(s,batches,true);}syncMachine(m);return moved;};
const refOldSlot=enterpriseSlotProduct;enterpriseSlotProduct=function(slot,p){if(!refEnabled())return refOldSlot(slot,p);const f=playerFirm(),m=machine(selected),s=m?.slots[slot];if(!s||!int(p,0,5)||!retailProductAllowed(f,p)||!refSupports(m,p)||refSiteUsed(f,m.ref.hub)+s.stock>refSite(f,m.ref.hub).capacity)return;refAdd(f.ops.warehouse[s.product],s.batches.map(b=>({...b,hub:m.ref.hub})));s.batches=[];s.product=p;s.sku='legacy:'+p;s.price=PRODUCTS[p].price;refSyncBucket(s,true);syncMachine(m);save();render();};
const refOldSale=recordMarketSale;recordMarketSale=function(m,s,row,index,paid,ours){if(!refEnabled())return refOldSale(m,s,row,index,paid,ours);const f=ours?playerFirm():rivalOwner(m.loc),batches=refTake(s,1),cost=batches.reduce((n,b)=>n+b.value,0);if(!batches.length)return;refSyncBucket(s,true);m.vault+=paid;m.total++;m.condition=Math.max(0,m.condition-.045);row.products??=PRODUCTS.map(()=>({sold:0,revenue:0,cost:0}));const p=row.products[s.product];p.sold++;p.revenue+=paid;p.cost+=cost;row.served++;row.revenue+=paid;row.cost+=cost;row.bought.push({i:index,price:paid});if(ours)state.totalSold++;const r=refFirm(f),site=refSite(f,m.ref.hub);if(site){site.metrics.revenue+=paid;site.metrics.cost+=cost;}const sku=refSKU(batches[0].sku);if(sku){sku.sold=(sku.sold||0)+1;sku.revenue=(sku.revenue||0)+paid;sku.cost=(sku.cost||0)+cost;const brand=r.brands.find(b=>b.id===sku.brand);if(brand)brand.sales++;}syncMachine(m);};
const refOldCustomer=marketCustomer;marketCustomer=function(map,index){return refEnabled()?refCustomer(map,index):refOldCustomer(map,index);};
const refOldReceive=companyReceive;companyReceive=function(f,ms){if(!refEnabled())return refOldReceive(f,ms);if(!finite(ms)||ms<=0)return;let left=ms;while(left>0){const step=Math.min(200,left),orders=[...f.ops.orders],jobs=[...expansionFirm(f).jobs];refOldReceive(f,step);refImportLegacyRaw(f);for(const o of orders.filter(o=>!f.ops.orders.includes(o)))refAdd(f.ops.warehouse[o.product],[refBatch(f,o.product,o.qty,o.value,o.quality||0,o.expiresDay,refHome(f).id)]);for(const j of jobs.filter(j=>j.kind==='drink'&&!expansionFirm(f).jobs.includes(j)))refAdd(f.ops.warehouse[j.product],[refBatch(f,j.product,j.qty,j.value,j.quality||0,state.day+expiryLife(j.product),refHome(f).id)]);for(const m of f.machines){refInitializeMachine(f,m,refHome(f).id);m.ref.serviceTotal=(m.ref.serviceTotal||0)+step;m.ref.serviceReady=(m.ref.serviceReady||0)+step*m.slots.filter(s=>s.stock>0&&refSupports(m,s.product)).length/4;}refOperationsAdvance(f,step);refCommerceAdvance(f,step);refProductionAdvance(f,step);refEquipmentAdvance(f,step);left-=step;}};
const refOldExpiry=expireInventory;expireInventory=function(f){if(!refEnabled())return refOldExpiry(f);let loss=0,count=0;for(const bucket of [...f.ops.warehouse,...f.machines.flatMap(m=>m.slots)]){for(const b of bucket.batches.filter(b=>b.expires<=state.day)){loss+=b.value;count+=b.qty;}bucket.batches=bucket.batches.filter(b=>b.expires>state.day);refSyncBucket(bucket,'stock'in bucket);}for(const m of f.machines)syncMachine(m);if(count){expansionFirm(f).waste+=count;expansionFirm(f).wasteValue+=loss;expenseBookLoss(f,loss);refClaim(f,'stock',loss);refNotice(f,`기한 만료 · ${count}개 폐기`,`期限切れ・${count}本廃棄`,'supply');}};
const refOldSupplierDay=supplierDaily;supplierDaily=function(){if(!refEnabled())return refOldSupplierDay();const w=refWorld();if(w.lastDay>=state.day)return;w.lastDay=state.day;const stopped=[];for(const s of state.enterprise.chain.suppliers)if(w.suppliers[s.id].closedUntil>state.day){stopped.push([s,s.capacity]);s.capacity=0;}refOldSupplierDay();for(const [s,capacity]of stopped)s.capacity=capacity;for(const f of allFirms().filter(f=>!f.policy?.defeated)){refOperationsDay(f);refCommerceDay(f);refEquipmentDay(f);refFinanceDay(f);}refWorldDay();};
const refOldAI=chainAI;chainAI=function(){refOldAI();if(refEnabled())for(const f of rivalFirms())refAI(f);};
const refOldStockAssets=companyStockAssets;companyStockAssets=function(f){return refOldStockAssets(f)+(refEnabled()?refExtraAssets(f):0);};
const refOldAssets=assets;assets=function(){return refOldAssets()+(refEnabled()?refExtraAssets(playerFirm()):0);};
const refOldRent=companyRent;companyRent=function(f,m){const base=refOldRent(f,m);if(!refEnabled())return base;const c=refFirm(f).contracts.find(c=>c.loc===m.loc&&c.kind!=='outsourced');if(!c)return base;if(c.kind==='share'){const rows=f.id==='player'?state.live?.rows:f.ops.market?.rows;return base*.5+(rows?.find(r=>r.loc===m.loc)?.revenue||0)*c.share;}return base*(c.kind==='service'?.85:.95);};
const refOldLiquidateWarehouse=liquidateWarehouse;liquidateWarehouse=function(f,p){if(!refEnabled())return refOldLiquidateWarehouse(f,p);const result=refOldLiquidateWarehouse(f,p);if(result){f.ops.warehouse[p].batches=[];refSyncBucket(f.ops.warehouse[p]);}return result;};
const refOldDispatch=dispatch;dispatch=function(type,loc,staff=false){if(refEnabled()&&staff){const f=playerFirm(),m=machine(loc);if(!m||!chainFirm(f).staff.some(w=>refEmployeeEligible(w,m.ref.hub,type)&&refWorkerFactor(f,w)>0&&!refFirm(f).work.some(j=>j.employee===w.id)&&!state.jobs.some(j=>j.employee===w.id)))return false;if(refFirm(f).work.some(j=>j.kind==='route'&&j.stops.some(s=>s.loc===loc)))return false;}return refOldDispatch(type,loc,staff);};
const refOldAdvanceRivals=advanceRivalOperations;advanceRivalOperations=function(ms){if(!refEnabled())return refOldAdvanceRivals(ms);for(const f of rivalFirms()){if(f.policy.defeated||!f.ops.market||f.ops.market.legacy)continue;f.ops.market.payroll+=chainPayroll(f)*ms/DAY_MS;companyReceive(f,ms);for(const j of f.ops.jobs)j.remaining-=ms;for(const j of f.ops.jobs.filter(j=>j.remaining<=0)){const m=f.machines.find(m=>m.loc===j.loc);if(m){if(j.type==='collect'){refIncome(f,m.vault,'collection',m.ref.hub,false);m.vault=0;}else companyRestock(f,m);}}f.ops.jobs=f.ops.jobs.filter(j=>j.remaining>0&&f.account.owned.includes(j.loc));for(const w of chainFirm(f).staff.filter(w=>['collect','restock'].includes(w.role)&&refWorkerFactor(f,w)>0)){if(mgEnabled()&&mgFirm(f).enabled&&refFirm(f).routes.some(t=>t.enabled&&t.hub===w.site)||f.ops.jobs.some(j=>j.employee===w.id)||refFirm(f).work.some(j=>j.employee===w.id))continue;const m=f.machines.filter(m=>m.ref.hub===w.site&&!f.ops.jobs.some(j=>j.loc===m.loc&&j.type===w.role)&&!refFirm(f).work.some(j=>j.kind==='route'&&j.stops.some(s=>s.loc===m.loc))).find(m=>w.role==='collect'?m.vault>=10000:m.stock<companyCapacity(f,m)*.35);if(m)f.ops.jobs.push({type:w.role,loc:m.loc,employee:w.id,remaining:4500/w.skill});}}};
const refOldTransfer=transferExpansionAssets;transferExpansionAssets=function(buyer,target){if(refEnabled()){const b=refFirm(buyer),t=refFirm(target);for(let p=0;p<6;p++){refAdd(buyer.ops.warehouse[p],target.ops.warehouse[p].batches||[]);target.ops.warehouse[p].batches=[];refSyncBucket(target.ops.warehouse[p]);}for(const key of ['sites','vehicles','routes','transfers','contracts','purchaseTerms','reservations','bills','receivables','notes','projects','licenses','brands','products','materials','work','units'])b[key].push(...t[key]);for(const sku of refCatalog())if(sku.owner===target.id)sku.owner=buyer.id;for(const tender of refWorld().tenders)for(const bid of tender.bids)if(bid.firm===target.id)bid.firm=buyer.id;refWorld().firms[target.id]=refNewFirm(target);for(const unit of b.units)unit.integration=Math.max(unit.integration,14);refNotice(buyer,'인수 사업장 통합 중 · 14일','買収事業所を統合中・14日','group');}return refOldTransfer(buyer,target);};
function refResetFirm(f){const r=refNewFirm(f);refWorld().firms[f.id]=r;const hub=refNewSite('warehouse',LOCATIONS[f.machines[0]?.loc||chainFirm(f).sites[0]?.loc||0].map);r.sites.push(hub);r.vehicles.push({id:refId(),hub:hub.id,capacity:160,cold:true,book:0,age:0,busy:0,lease:null});for(const w of chainFirm(f).staff)Object.assign(w,{site:hub.id,fatigue:0,satisfaction:70,specialty:0,shift:0,manager:false,notice:0});for(let p=0;p<6;p++){const w=f.ops.warehouse[p];w.batches=w.qty?[refBatch(f,p,w.qty,w.value,w.quality||0,w.expiresDay||state.day+expiryLife(p),hub.id)]:[];}for(const m of f.machines)refInitializeMachine(f,m,hub.id);}
const refOldRevive=reviveCompany;reviveCompany=function(f){const ok=refOldRevive(f);if(ok&&refEnabled())refResetFirm(rivalById(f.id));return ok;};
const refOldClose=closeCompany;closeCompany=function(f,reason){if(refEnabled()&&!f.policy.defeated){const r=refFirm(f),recover=r.sites.filter(s=>['warehouse','research'].includes(s.kind)).reduce((n,s)=>n+s.book*.5,0)+r.vehicles.reduce((n,v)=>n+v.book*.5,0)+r.units.reduce((n,u)=>n+u.cash,0);f.account.cash+=recover;for(const t of refWorld().tenders)for(const bid of t.bids.filter(b=>b.firm===f.id)){f.account.cash+=bid.value;t.bids=t.bids.filter(b=>b!==bid);}refWorld().firms[f.id]=refNewFirm(f);}const result=refOldClose(f,reason);if(refEnabled())for(const w of f.ops.warehouse){w.batches=[];refSyncBucket(w);}return result;};
const refOldDemand=demand;demand=function(m){const n=refOldDemand(m);return refEnabled()?Math.min(4800,n*(refWorld().cities[LOCATIONS[m.loc].map]?.demand||1)):n;};
const refOldLiquidatePlant=liquidatePlant;liquidatePlant=function(f,kind){if(!refEnabled())return refOldLiquidatePlant(f,kind);const site=refFirm(f).sites.findLast(s=>s.kind===kind&&!s.closed&&!s.build);if(!site||site.owner||refFirm(f).work.some(j=>j.site===site.id))return false;const result=refOldLiquidatePlant(f,kind);if(result){site.closed=true;site.book=0;site.processInvestment=0;for(const w of chainFirm(f).staff)if(w.site===site.id){w.site=refHome(f).id;w.map=refHome(f).map;}}return result;};
const refOldInstall=installKit;installKit=function(f,loc){if(refEnabled()){const kit=expansionFirm(f).kits[0],available=['station','office'].includes(LOCATIONS[loc]?.kind)?2:1;if(kit?.model===1&&available<2)return refError(B('대형 기기 설치 면적 부족','大型機械の設置面積不足'));}return refOldInstall(f,loc);};
