/* Reference economy: explicit resources, durable work, and one inherited clock. */
function refEnabled(){return chainEnabled()&&!!state.enterprise.reference;}
function refWorld(){return state.enterprise.reference;}
function refFirm(f){return refWorld().firms[f.id];}
function refId(){return refWorld().next++;}
function refClamp(n,min,max){return Math.max(min,Math.min(max,n));}
function refNow(){return state.day+(state.live?.elapsed||0)/DAY_MS;}
function refName(kind){return ({warehouse:B('배송 거점','配送拠点'),drink:B('음료 공장','飲料工場'),machine:B('기기 공장','機械工場'),research:B('연구소','研究所')})[kind];}
function refError(message){if(refEnabled())refWorld().lastError=message;return false;}
function refNotice(f,ko,ja,desk='sites',entity=null){const r=refFirm(f);r.notices.unshift({id:refId(),day:state.day,text:B(ko,ja),desk,entity});r.notices=r.notices.slice(0,60);if(f.id==='player')log(B(ko,ja));}
function refPost(f,kind,amount,flow='operating',site=0,other=null){
 const r=refFirm(f);if(!finite(amount))throw Error('Non-finite transaction');
 r.journal.push({id:refId(),day:state.day,kind,amount,flow,site,other});r.journal=r.journal.slice(-500);
 const d=r.daybook;d[flow]=(d[flow]||0)+amount;if(site){const s=r.sites.find(s=>s.id===site);if(s)s.cashFlow+=amount;}
}
function refSpend(f,amount,kind,site=0,capital=false){if(!finite(amount)||amount<0||state.ended||f.account.cash<amount)return false;f.account.cash-=amount;if(!capital)expenseBookLoss(f,amount);refPost(f,kind,-amount,capital?'investing':'operating',site);return true;}
function refIncome(f,amount,kind,site=0,profit=true){if(!finite(amount)||amount<0)throw Error('Invalid income');f.account.cash+=amount;if(profit)expenseBookLoss(f,-amount);refPost(f,kind,amount,'operating',site);}
function refNewSite(kind,map,book=0){return {id:refId(),kind,map,book,original:book,age:0,capacity:kind==='warehouse'?1000:500,cold:true,build:0,closed:false,owner:null,manager:null,cashFlow:0,history:[],process:[1,1,1],lastProduct:-1,maintenance:100,policy:{enabled:false,min:40,target:160,reserve:100000,supplier:0,backup:1,markup:50,repair:35,overtime:0},metrics:{revenue:0,cost:0,salary:0,overhead:0,throughput:0,wait:0}};}
function refNewFirm(f){return {sites:[],vehicles:[],routes:[],transfers:[],contracts:[],purchaseTerms:[],reservations:[],bills:[],receivables:[],notes:[],insurance:null,journal:[],reports:[],notices:[],projects:[],technology:{cold:0,materials:0,filling:0,network:0},licenses:[],brands:[{id:'house',name:'HC',position:'standard',awareness:MAPS.map(()=>15),spend:0,sales:0}],products:[],materials:[],work:[],trust:LOCATIONS.map(()=>50),preferences:[],analytics:[],strategy:{kind:f.id==='nova'?'premium':f.id==='atlas'?'manufacturer':'density',target:-1,until:0,budget:0,spent:0},units:[],share:{total:1000,owner:1000,float:0,holders:{},listed:false,price:1000},goal:{kind:'operator',streak:0,achieved:false},delegation:{budget:200000,spent:0,exceptions:0},lastDay:0,daybook:{openingCash:f.account.cash,operating:0,investing:0,financing:0},stats:{wholesale:0,manufactured:0,contractsWon:0,lostCustomers:0,recovered:0},savedPolicies:[]};}
function refInitialize(){
 if(!chainEnabled()||state.enterprise.reference)return false;
 try{const old=localStorage.getItem(KEY);if(old&&!localStorage.getItem(KEY+'-backup-before-reference'))localStorage.setItem(KEY+'-backup-before-reference',old);}catch{}
 state.enterprise.reference={version:1,next:1,lastDay:0,startYear:2000,lastError:null,firms:{},cities:MAPS.map(m=>({map:m.id,population:10000,income:1,employment:.92,wage:1,demand:1,interest:1,development:0})),catalog:[],suppliers:{},tenders:[],rawCash:50000000,bankCash:50000000,investorCash:50000000,talent:[],events:[],standards:{paymentYear:2001,coolingYear:2003},selectedSite:null};
 for(const f of allFirms()){
  const r=refNewFirm(f);refWorld().firms[f.id]=r;const hub=refNewSite('warehouse',LOCATIONS[f.machines[0]?.loc||0].map);hub.capacity=1000+f.tech.logistics*500;r.sites.push(hub);r.technology={cold:chainFirm(f).licenses.efficiency,materials:chainFirm(f).licenses.products,filling:chainFirm(f).licenses.quality,network:chainFirm(f).licenses.logistics};for(const order of f.ops.orders)order.hub=hub.id;
  r.vehicles.push({id:refId(),hub:hub.id,capacity:160,cold:true,book:0,age:0,busy:0,lease:null});
  for(const kind of ['drink','machine'])for(const facility of expansionFirm(f).facilities.filter(x=>x.kind===kind))r.sites.push(refNewSite(kind,hub.map,facility.value*.5));
  for(const build of chainFirm(f).builds){const site=refNewSite(build.kind,hub.map,build.value);site.build=build.remaining;site.chainBuild=build.id;r.sites.push(site);}
  for(const w of chainFirm(f).staff){w.site=hub.id;w.fatigue=0;w.satisfaction=70;w.specialty=0;w.shift=0;w.manager=false;w.notice=0;if(['drink','machine'].includes(w.role))w.site=r.sites.find(s=>s.kind===w.role)?.id||hub.id;}
  for(const m of f.machines)refInitializeMachine(f,m,hub.id);
  for(let p=0;p<6;p++){const w=f.ops.warehouse[p];w.batches=w.qty?[refBatch(f,p,w.qty,w.value,w.quality||0,w.expiresDay||state.day+expiryLife(p),hub.id)]:[];}refImportLegacyRaw(f);
 }
 for(const s of state.enterprise.chain.suppliers)refWorld().suppliers[s.id]={health:100,closedUntil:0,capacity:s.capacity,investment:0,reputation:70,generation:1};
 return true;
}
function refInitializeMachine(f,m,hub){m.ref??={hub,age:0,reliability:1,cold:m.model===1||m.slots.some(s=>s.stock&&s.product===4),hot:m.model===1||m.slots.some(s=>s.stock&&s.product===5),payment:0,telemetry:false,installed:state.day,observedStock:m.stock,observedDay:state.day,serviceTotal:0,serviceReady:0,lease:null,downtime:0,book:equipment(m)*.7,original:equipment(m)*.7,sla:100,skuTrial:null};for(const s of m.slots){s.sku??='legacy:'+s.product;s.batches??=s.stock?[refBatch(f,s.product,s.stock,s.value,s.quality||0,s.expiresDay||state.day+expiryLife(s.product),hub,s.sku)]:[];}}
function refBatch(f,p,qty,value,quality,expires,hub,sku='legacy:'+p){const id=refId();return {id,lot:id,product:p,sku,qty,value,quality:refClamp(quality,0,3),expires,hub};}
function refSyncBucket(bucket,slot=false){const batches=bucket.batches||[];bucket[slot?'stock':'qty']=batches.reduce((n,b)=>n+b.qty,0);bucket.value=batches.reduce((n,b)=>n+b.value,0);bucket.quality=bucket[slot?'stock':'qty']?batches.reduce((n,b)=>n+b.qty*b.quality,0)/bucket[slot?'stock':'qty']:0;bucket.expiresDay=batches.length?Math.min(...batches.map(b=>b.expires)):0;}
function refTake(bucket,qty,filter=()=>true){const taken=[];for(const b of [...(bucket.batches||[])].filter(filter).sort((a,b)=>a.expires-b.expires||a.id-b.id)){if(qty<=0)break;const n=Math.min(qty,b.qty),value=b.value*n/b.qty;taken.push({...b,lot:b.lot||b.id,id:refId(),qty:n,value});b.qty-=n;b.value=Math.max(0,b.value-value);qty-=n;}bucket.batches=bucket.batches.filter(b=>b.qty>0);return taken;}
function refAdd(bucket,batches,slot=false){bucket.batches??=[];for(const b of batches){if(!b.qty)continue;const match=bucket.batches.find(a=>(a.lot||a.id)===(b.lot||b.id)&&a.sku===b.sku&&a.expires===b.expires&&a.hub===b.hub&&a.quality===b.quality);if(match){match.qty+=b.qty;match.value+=b.value;}else bucket.batches.push({...b});}refSyncBucket(bucket,slot);}
function refSite(f,id){return refFirm(f).sites.find(s=>s.id===id&&!s.closed);}
function refHome(f){return refFirm(f).sites.find(s=>s.kind==='warehouse'&&!s.closed&&!s.build);}
function refSiteInventory(f,id){return f.ops.warehouse.flatMap(w=>w.batches||[]).filter(b=>b.hub===id);}
function refSiteUsed(f,id){return expansionFirm(f).jobs.filter(j=>j.kind==='drink'&&(j.hub||refHome(f)?.id)===id).reduce((n,j)=>n+j.qty,0)+refSiteInventory(f,id).reduce((n,b)=>n+b.qty,0)+f.ops.orders.filter(o=>o.hub===id).reduce((n,o)=>n+o.qty,0)+refFirm(f).work.filter(j=>j.kind==='purchase'&&j.site===id||j.kind==='production'&&!j.machine&&j.hub===id).reduce((n,j)=>n+j.qty,0)+refFirm(f).transfers.filter(t=>t.to===id).reduce((n,t)=>n+t.batches.reduce((n,b)=>n+b.qty,0),0);}
function refExtraAssets(f){const r=refFirm(f);return Object.entries(r.shareInvestments||{}).reduce((n,[id,qty])=>n+qty*(refWorld().firms[id]?.share.price||0),0)-r.units.reduce((n,u)=>n+(1-u.ownership)*Math.max(0,refUnitValue(f,u)),0)+f.machines.reduce((n,m)=>n+(m.ref?m.ref.book-equipment(m)*.7:0),0)+r.sites.filter(s=>['drink','machine'].includes(s.kind)&&!s.closed&&!s.build).reduce((n,s)=>n+s.book,0)-expansionFirm(f).plantValue*.5+r.sites.filter(s=>s.kind==='warehouse'||s.kind==='research').reduce((n,s)=>n+s.book,0)+r.vehicles.reduce((n,v)=>n+v.book,0)+r.transfers.reduce((n,t)=>n+t.batches.reduce((n,b)=>n+b.value,0),0)+r.work.filter(j=>j.kind==='route').reduce((n,j)=>n+j.stops.reduce((n,s)=>n+s.cargo.reduce((n,c)=>n+c.batches.reduce((n,b)=>n+b.value,0),0),0),0)+r.materials.reduce((n,b)=>n+b.value,0)+r.receivables.reduce((n,b)=>n+b.amount,0)+r.projects.reduce((n,p)=>n+p.budget-p.spent,0)+r.units.reduce((n,u)=>n+u.cash,0)+r.work.filter(j=>['purchase','material','production','replacement'].includes(j.kind)).reduce((n,j)=>n+(j.value||0),0)+r.contracts.reduce((n,c)=>n+c.deposit,0)+refWorld().tenders.filter(t=>!t.closed).flatMap(t=>t.bids).filter(b=>b.firm===f.id).reduce((n,b)=>n+b.value,0)-r.bills.reduce((n,b)=>n+b.amount,0)-r.notes.reduce((n,b)=>n+b.principal,0);}
function refCheckConservation(f){for(const w of f.ops.warehouse){if(Math.abs(w.qty-(w.batches||[]).reduce((n,b)=>n+b.qty,0))>.001||Math.abs(w.value-(w.batches||[]).reduce((n,b)=>n+b.value,0))>.01)return false;}for(const m of f.machines)for(const s of m.slots)if(s.batches&&(s.stock!==s.batches.reduce((n,b)=>n+b.qty,0)||Math.abs(s.value-s.batches.reduce((n,b)=>n+b.value,0))>.01))return false;return true;}
function validReference(x,s){
 const nn=n=>finite(n)&&n>=0,arr=(v,max)=>Array.isArray(v)&&v.length<=max;
 let nodes=0;function bounded(v,depth=0){if(++nodes>200000||depth>24)return false;if(typeof v==='number')return finite(v);if(typeof v==='string')return v.length<=2000;if(v===null||typeof v==='boolean')return true;if(Array.isArray(v))return v.length<=3000&&v.every(n=>bounded(n,depth+1));if(typeof v==='object')return Object.keys(v).length<=150&&Object.values(v).every(n=>bounded(n,depth+1));return false;}if(!bounded(x)||x?.management&&!mgValid(x))return false;
 if(!x||x.version!==1||!int(x.next,1,1e12)||!int(x.lastDay,0,1e6)||!int(x.startYear,1900,2100)||!x.firms||!arr(x.cities,5)||!arr(x.catalog,300)||!arr(x.tenders,100)||!nn(x.rawCash)||!nn(x.bankCash)||!nn(x.investorCash))return false;
 for(const r of Object.values(x.firms)){
  if(!arr(r.sites,100)||!arr(r.vehicles,200)||!arr(r.transfers,300)||!arr(r.journal,500)||!arr(r.reports,120)||!arr(r.notices,60)||!arr(r.bills,500)||!arr(r.receivables,500)||!arr(r.work,300)||!arr(r.projects,40)||!arr(r.units,20)||!r.daybook||!r.strategy||!r.share)return false;
  if(!r.sites.every(v=>int(v.id,1,x.next-1)&&['warehouse','drink','machine','research'].includes(v.kind)&&int(v.map,0,4)&&nn(v.book)&&nn(v.capacity)&&nn(v.build)&&typeof v.closed==='boolean')||new Set(r.sites.map(v=>v.id)).size!==r.sites.length)return false;
  if(!r.journal.every(v=>int(v.id,1,x.next-1)&&finite(v.amount)&&typeof v.kind==='string')||!r.vehicles.every(v=>int(v.id,1,x.next-1)&&nn(v.book)&&int(v.capacity,1,10000))||!r.bills.every(v=>nn(v.amount)&&int(v.due,1,1e6))||!r.receivables.every(v=>nn(v.amount)&&int(v.due,1,1e6)))return false;
 }
 const ids=['player','mono',...(s.enterprise.industry.companies||[]).map(v=>v.meta.id)],inventories=[{machines:s.machines,warehouse:s.enterprise.warehouse},s.enterprise.operations,...s.enterprise.industry.companies.map(v=>v.operations)];
 if(!ids.every(id=>x.firms[id])||!x.cities.every(c=>int(c.map,0,4)&&nn(c.income)&&nn(c.wage)&&nn(c.demand)&&nn(c.interest)))return false;
 for(let k=0;k<ids.length;k++){const r=x.firms[ids[k]],inv=inventories[k],site=id=>r.sites.some(h=>h.id===id&&!h.closed),batch=(b,p)=>b&&int(b.id,1,x.next-1)&&b.product===p&&int(b.qty,1,100000)&&nn(b.value)&&finite(b.quality)&&b.quality>=0&&b.quality<=3&&int(b.expires,1,1e6)&&site(b.hub)&&typeof b.sku==='string',bucket=(w,p,slot=false)=>arr(w.batches,1000)&&w.batches.every(b=>batch(b,p))&&w[slot?'stock':'qty']===w.batches.reduce((n,b)=>n+b.qty,0)&&Math.abs(w.value-w.batches.reduce((n,b)=>n+b.value,0))<.01;
  if(!inv.warehouse.every((w,p)=>bucket(w,p))||!inv.machines.every(m=>m.ref&&site(m.ref.hub)&&nn(m.ref.age)&&nn(m.ref.book)&&nn(m.ref.downtime)&&m.slots.every(slot=>typeof slot.sku==='string'&&bucket(slot,slot.product,true))))return false;
  if(!['contracts','purchaseTerms','reservations','licenses','brands','products','materials','routes','savedPolicies','analytics'].every(key=>arr(r[key],500))||!r.technology||!['cold','materials','filling','network'].every(key=>int(r.technology[key],0,3))||!r.goal||!r.delegation||!arr(r.trust,30)||!r.trust.every(n=>finite(n)&&n>=0&&n<=100))return false;
  if(!r.projects.every(p=>['products','quality','efficiency','logistics'].includes(p.key)&&int(p.tier,1,3)&&nn(p.budget)&&nn(p.spent)&&p.spent<=p.budget+.01&&int(p.stage,0,3)&&nn(p.progress)&&finite(p.duration)&&p.duration>0&&typeof p.complete==='boolean')||!r.work.every(j=>['route','recruit','purchase','material','production','retrofit','replacement','relocation'].includes(j.kind)&&finite(j.remaining)&&j.remaining>0))return false;
  if(!r.notes.every(n=>nn(n.principal)&&nn(n.rate)&&int(n.due,1,1e6))||!r.units.every(u=>nn(u.cash)&&finite(u.ownership)&&u.ownership>0&&u.ownership<=1&&arr(u.sites,100)&&u.sites.every(site)))return false;
  if(!s.enterprise.chain.firms[ids[k]].staff.every(w=>site(w.site)&&nn(w.fatigue)&&w.fatigue<=100&&nn(w.satisfaction)&&w.satisfaction<=100&&int(w.shift,0,2)))return false;
 }
 return true;
}
