/* A subsidiary sale transfers its operating assets and people, not a bonus counter. */
function refUnitValue(f,u){const r=refFirm(f),ids=u.sites;return u.cash-(u.parentLoan||0)+r.sites.filter(s=>ids.includes(s.id)).reduce((n,s)=>n+s.book,0)+r.vehicles.filter(v=>ids.includes(v.hub)).reduce((n,v)=>n+v.book,0)+f.ops.warehouse.flatMap(w=>w.batches).filter(b=>ids.includes(b.hub)).reduce((n,b)=>n+b.value,0)+r.materials.filter(b=>ids.includes(b.site)).reduce((n,b)=>n+b.value,0)+f.machines.filter(m=>ids.includes(m.ref.hub)).reduce((n,m)=>n+m.ref.book+m.vault+stockValue(m),0);}
function refDivestUnit(f,id,buyerId){const r=refFirm(f),u=r.units.find(u=>u.id===id),buyer=allFirms().find(v=>v.id===buyerId);if(!u||!buyer||buyer===f||buyer.id===f.id||buyer.policy?.defeated||u.integration||state.ended)return false;const ids=u.sites,sites=r.sites.filter(s=>ids.includes(s.id)),machines=f.machines.filter(m=>ids.includes(m.ref.hub)),locs=machines.map(m=>m.loc);if(!r.sites.some(s=>s.kind==='warehouse'&&!ids.includes(s.id)&&!s.closed)||r.work.some(j=>ids.includes(j.site)||locs.includes(j.loc))||r.projects.some(p=>!p.complete)||r.transfers.some(t=>ids.includes(t.from)||ids.includes(t.to))||f.ops.orders.length||expansionFirm(f).jobs.length||chainFirm(f).builds.length||chainFirm(f).orders.some(o=>locs.includes(o.loc)))return refError(B('사업장 작업·배송 종료 후 매각 가능','事業所作業・配送終了後に売却可能'));
 const price=Math.round(refUnitValue(f,u)*1.1);const parentLoan=u.parentLoan||0,ownerPercent=u.ownership;if(price<=0||buyer.account.cash<price+parentLoan||chainFirm(buyer).staff.length+chainFirm(f).staff.filter(w=>ids.includes(w.site)).length>120)return false;
 buyer.account.cash-=price+parentLoan;f.account.cash+=price*u.ownership+parentLoan;u.parentLoan=0;refWorld().investorCash+=price*(1-u.ownership);const b=refFirm(buyer);u.ownership=1;u.listed=false;u.integration=14;b.units.push(u);r.units=r.units.filter(v=>v!==u);b.sites.push(...sites);r.sites=r.sites.filter(s=>!ids.includes(s.id));for(const s of sites)s.integration=14;
 for(const key of ['vehicles','routes']){const moved=r[key].filter(v=>ids.includes(v.hub));b[key].push(...moved);r[key]=r[key].filter(v=>!moved.includes(v));}
 const staff=chainFirm(f).staff.filter(w=>ids.includes(w.site));chainFirm(buyer).staff.push(...staff);chainFirm(f).staff=chainFirm(f).staff.filter(w=>!staff.includes(w));const payrollJobs=f.id==='player'?state.jobs:f.ops.jobs;if(f.id==='player')state.jobs=payrollJobs.filter(j=>!locs.includes(j.loc));else f.ops.jobs=payrollJobs.filter(j=>!locs.includes(j.loc));
 for(let p=0;p<6;p++){const stock=f.ops.warehouse[p],batches=stock.batches.filter(batch=>ids.includes(batch.hub));stock.batches=stock.batches.filter(batch=>!ids.includes(batch.hub));refSyncBucket(stock);refAdd(buyer.ops.warehouse[p],batches);}const raw=r.materials.filter(x=>ids.includes(x.site));b.materials.push(...raw);r.materials=r.materials.filter(x=>!ids.includes(x.site));
 for(const site of sites.filter(s=>['drink','machine'].includes(s.kind))){const from=expansionFirm(f),to=expansionFirm(buyer),idx=from.facilities.findIndex(v=>v.kind===site.kind);if(idx>=0){const facility=from.facilities.splice(idx,1)[0];from.plantValue-=facility.value;from.plants[site.kind]--;to.plantValue+=facility.value;to.plants[site.kind]++;to.facilities.push(facility);}}
 for(const m of machines){if(f.id==='player')removeMachine(m.loc);else removeRivalMachine(f,m.loc);if(buyer.id==='player')state.machines.push(m);else{buyer.ops.machines.push(m);buyer.account.owned.push(m.loc);}const rows=buyer.id==='player'?state.live?.rows:buyer.ops.market?.rows;if(rows&&!rows.some(row=>row.loc===m.loc)){const n=state.enterprise.operations.market.districts[LOCATIONS[m.loc].map].n,row=marketRow(m,n);row.rent*=1-(state.live?.elapsed||0)/DAY_MS;rows.push(row);}}
 const movedContracts=r.contracts.filter(c=>locs.includes(c.loc));b.contracts.push(...movedContracts);r.contracts=r.contracts.filter(c=>!locs.includes(c.loc));refPost(f,'subsidiary-divestiture',price*ownerPercent+parentLoan-u.cash,'investing');refPost(buyer,'subsidiary-acquisition',-price-parentLoan+u.cash,'investing');syncChainStaff();return true;
}
function refTradeVoting(buyer,targetId,qty){const target=allFirms().find(f=>f.id===targetId);if(!target||target.id!=='player'||buyer.id===target.id||!int(qty,1,500)||state.ended)return false;const share=refFirm(target).share,r=refFirm(buyer),value=qty*Math.max(100,share.price);if((share.holders.market||0)<qty||buyer.account.cash<value)return false;buyer.account.cash-=value;refWorld().investorCash+=value;share.holders.market-=qty;share.holders[buyer.id]=(share.holders[buyer.id]||0)+qty;r.shareInvestments??={};r.shareInvestments[target.id]=(r.shareInvestments[target.id]||0)+qty;refPost(buyer,'voting-shares',-value,'investing');refNotice(target,`${companyNameFor(buyer.id,0)} · 지분 ${Math.round(share.holders[buyer.id]/share.total*100)}% 확보`,`${companyNameFor(buyer.id,1)}・持分${Math.round(share.holders[buyer.id]/share.total*100)}%を取得`,'group');return true;}
const refOldIssueEquity=refIssueEquity;refIssueEquity=function(f,qty,buyer='market'){if(f.id!=='player')return false;return refOldIssueEquity(f,qty,buyer);};
const refOldAIVoting=refAI;refAI=function(f){refOldAIVoting(f);if(f.policy.defeated||state.day%14!==0||f.account.cash<500000)return;const share=refFirm(playerFirm()).share;if(share.total>share.owner*2&&share.holders.market)refTradeVoting(f,'player',Math.min(100,share.holders.market));};
const refCheckBeforeControl=checkEnding;checkEnding=function(timeCheck=false){if(refEnabled()&&!state.ended){const share=refFirm(playerFirm()).share,controller=Object.entries(share.holders).find(([id,n])=>id!=='market'&&n>share.total/2);if(controller){state.ending={type:'control',day:state.day,assets:assets(),controller:controller[0]};state.ended=true;state.live=null;livePaused=true;save();render();openModal('end');return true;}}return refCheckBeforeControl(timeCheck);};
const refModalBeforeControl=drawModal;drawModal=function(){const control=modalView==='end'&&state.ending?.type==='control';if(control)state.ending.type='bank';try{refModalBeforeControl();}finally{if(control)state.ending.type='control';}if(control)$('modal-body').innerHTML=`<h2>${T('경영권 상실','経営権喪失')}</h2><p>${esc(companyName(state.ending.controller))} · ${T('과반 의결권 확보','過半数の議決権を取得')}</p>`+buttons(`<button id="menu-new">${T('새 회사 설립','新会社を設立')}</button>`);};
