/* Rival decisions, shared competitive pressure and directly accessible language controls. */
const rivalryFresh=()=>({version:1,mode:'steady',plan:null,target:0,until:0,turnDay:0,lastProfit:0,pendingProfit:null,losses:0,insolvency:0,defeated:false,campaigns:[null,null,null,null],history:[]});
function ensureRivalry(){if(!state.enterprise.rivalry)state.enterprise.rivalry=rivalryFresh();return state.enterprise.rivalry;}
const freshBeforeRivalry=fresh;fresh=()=>{const s=freshBeforeRivalry();s.enterprise.rivalry=rivalryFresh();return s;};
ensureRivalry();
const RIVAL_MODES={steady:B('수익 확보','利益確保'),price:B('가격 공세','価格攻勢'),advertise:B('광고 공세','広告攻勢'),retreat:B('현금 방어','資金防衛'),closed:B('사업 철수','事業撤退')};
const CAMPAIGNS={discount:{name:B('맞불 할인','対抗値下げ'),cost:15000,days:3,desc:B('3일간 실제 판매가 −15% (최저 $0.80). 판매량과 점유율을 노리지만 개당 마진이 줄어듭니다.','3日間、実際の販売価格−15%（最低$0.80）。販売量とシェアを狙う代わりに単価利益が減少。')},loyalty:{name:B('단골 확보','常連客獲得'),cost:25000,days:5,desc:B('5일간 자사 선택 매력 +35%. 경쟁사의 예상 판매를 줄이고 자사 구매 이탈을 완화합니다.','5日間、自社の選択魅力+35%。競合の予想販売を減らし、自社の購入離脱を緩和。')},defend:{name:B('방어 광고','防衛広告'),cost:12000,days:3,desc:B('3일간 경쟁사 공세로 증가한 고객 유출 압력 70% 상쇄. 정상적인 경쟁은 남습니다.','3日間、競合攻勢による流出圧力の増加分を70%軽減。通常の競争は残ります。')}};
function activeCampaign(map){const c=ensureRivalry().campaigns[map];return c&&c.until>=state.day?c:null;}
function campaignPrice(slot,map){return Math.max(800,Math.round(slot.price*(activeCampaign(map)?.kind==='discount'?.85:1)));}
function competitionStrength(map){
 const e=state.enterprise,r=ensureRivalry(),ours=state.machines.filter(m=>LOCATIONS[m.loc].map===map),theirs=state.npc.owned.filter(id=>LOCATIONS[id].map===map);
 let player=ours.reduce((n,m)=>{ensureSlots(m);const slots=m.slots.filter(s=>s.stock>0);return n+slots.reduce((a,s)=>a+(PRODUCTS[s.product].price/campaignPrice(s,map))**1.5*(1+e.tech.quality*.09+(s.label?e.brand[map]/140:0)),0)/4*(.5+m.condition/200)*(.65+state.reputation/200);},0);
 if(activeCampaign(map)?.kind==='loyalty')player*=1.35;
 let rival=theirs.length*rivalSkillFactor()*(1500/e.rivalPrices[map])**1.5*(state.npc.cash<0?.55:1);
 if(!r.defeated&&r.target===map&&r.until>=state.day){let boost=r.mode==='advertise'?.65:r.mode==='price'?.3:0;rival*=1+boost;if(activeCampaign(map)?.kind==='defend'){const baseline=theirs.length*rivalSkillFactor()*(state.npc.cash<0?.55:1);rival=baseline+(rival-baseline)*.3;}}
 const total=player+rival+.45;return {player,rival,share:player/total,rivalShare:rival/total};
}
function rivalCompetition(map){const x=competitionStrength(map);return x.rival/(1+x.player)*.55;}
function rivalryLog(ko,ja){const r=ensureRivalry();r.history.unshift({day:state.day,text:B(ko,ja)});r.history=r.history.slice(0,20);log(B(ko,ja));}
function startCampaign(map,kind){const r=ensureRivalry(),c=CAMPAIGNS[kind];if(!state.started||state.ended||!int(map,0,MAPS.length-1)||!c||activeCampaign(map)||state.cash<c.cost||!state.machines.some(m=>LOCATIONS[m.loc].map===map))return false;enterpriseExpense(c.cost,'advertising');r.campaigns[map]={kind,until:state.day+c.days-1};rivalryLog(`${MAPS[map].name[0]}: ${c.name[0]} 시작 · ${money(c.cost)} · DAY ${r.campaigns[map].until}까지`,`${MAPS[map].name[1]}：${c.name[1]}開始・${money(c.cost)}・DAY ${r.campaigns[map].until}まで`);save();render();return true;}
// Prices, availability and company campaigns used by real purchases also determine rival profits.
rivalOpportunity=function(l){const e=state.enterprise,share=competitionStrength(l.map).rivalShare,visits=demand({loc:l.id,level:1}),price=e.rivalPrices[l.map];return (visits*.85*share*(price-PRODUCTS[0].cost*e.index*inflationFactor()*rivalCostFactor())-l.rent)/l.cost;};
rivalDailyProfit=function(){const r=ensureRivalry();if(r.defeated)return 0;const campaign=r.until>=state.day?(r.mode==='price'?7000:r.mode==='advertise'?8000:0):0;return Math.round(state.npc.owned.reduce((n,id)=>n+rivalOpportunity(LOCATIONS[id])*LOCATIONS[id].cost-2500,0)-15000*(1+state.difficulty*.15)-campaign);};
function rivalTurn(){
 const r=ensureRivalry(),e=state.enterprise;if(r.turnDay>=state.day||r.defeated)return;r.turnDay=state.day;
 r.lastProfit=r.pendingProfit??0;r.pendingProfit=null;r.losses=r.lastProfit<0?r.losses+1:0;r.insolvency=state.npc.cash<0?r.insolvency+1:0;
 if(state.npc.cash<30000&&state.npc.owned.length>1){const id=[...state.npc.owned].sort((a,b)=>rivalOpportunity(LOCATIONS[a])-rivalOpportunity(LOCATIONS[b]))[0];state.npc.owned=state.npc.owned.filter(x=>x!==id);state.npc.cash+=Math.round(LOCATIONS[id].cost*.5);if(state.npc.cash>=0)r.insolvency=0;rivalryLog(`경쟁사 자금난: ${LOCATIONS[id].name[0]} 기기를 처분했습니다. 빈 입지에 출점할 수 있습니다.`,`競合の資金難：${LOCATIONS[id].name[1]}の機械を処分。空いた立地に出店できます。`);}
 if(r.insolvency>=5){r.defeated=true;r.plan=null;r.mode='closed';state.npc.owned=[];state.npc.cash=0;state.offer=null;rivalryLog('경쟁사가 사업 철수를 발표했습니다. 회사 운영은 계속됩니다.','競合が事業撤退を発表しました。会社経営は続きます。');return;}
 if(state.npc.cash<80000){r.plan=null;r.mode='retreat';r.until=state.day+1;e.rivalPrices=e.rivalPrices.map(()=>1750);if(r.insolvency===1)rivalryLog('경쟁사가 신규 투자를 중단하고 보유 입지 처분을 검토합니다.','競合が新規投資を中断し、保有立地の処分を検討しています。');return;}
 if(r.plan&&r.plan.start<=state.day){r.mode=r.plan.mode;r.target=r.plan.target;r.until=r.plan.until;r.plan=null;e.rivalPrices=e.rivalPrices.map(()=>1500);e.rivalPrices[r.target]=r.mode==='price'?1050:1500;}
 if(r.until+scenarioAttackRest()<state.day&&!r.plan){
  const maps=[0,1,2,3].filter(map=>state.machines.some(m=>LOCATIONS[m.loc].map===map)&&state.npc.owned.some(id=>LOCATIONS[id].map===map));
  maps.sort((a,b)=>{const weak=map=>state.machines.filter(m=>LOCATIONS[m.loc].map===map).reduce((n,m)=>n+1+(1-m.stock/capacity(m))+(100-m.condition)/100,0);return weak(b)-weak(a);});
  if(maps.length){const mode=state.cash<80000||r.losses===0?'price':'advertise';r.target=maps[0];r.plan={mode,target:r.target,start:state.day+1,until:state.day+scenarioAttackDays()};r.mode='steady';r.until=state.day;e.rivalPrices=e.rivalPrices.map(()=>1500);rivalryLog(`경쟁사 예고: DAY ${r.plan.start}부터 ${MAPS[r.target].name[0]}에 ${RIVAL_MODES[mode][0]} · DAY ${r.plan.until}까지. 재고·마진·현금을 점검하세요.`,`競合予告：DAY ${r.plan.start}から${MAPS[r.target].name[1]}で${RIVAL_MODES[mode][1]}・DAY ${r.plan.until}まで。在庫・利益率・現金を確認しましょう。`);}else{r.mode='steady';r.until=state.day+2;e.rivalPrices=e.rivalPrices.map(()=>1500);}
 }
 if(state.day%scenarioExpansionInterval()===0){const empty=LOCATIONS.filter(l=>!machine(l.id)&&!state.npc.owned.includes(l.id)).sort((a,b)=>rivalOpportunityForExpansion(b)-rivalOpportunityForExpansion(a));const l=empty[0];if(l&&state.npc.cash>l.cost+80000){state.npc.cash-=l.cost;state.npc.owned.push(l.id);rivalryLog(`경쟁사가 ${l.name[0]}에 출점하며 시장을 넓힙니다.`,`競合が${l.name[1]}へ出店し市場を拡大。`);}}
 if(!state.offer&&state.day%6===0&&state.cash<80000&&state.machines.length>1){const m=[...state.machines].sort((a,b)=>b.total-a.total)[0],price=Math.round(equipment(m)*.9+stockValue(m)+m.vault);if(state.npc.cash>=price+30000){state.offer={loc:m.loc,price,deadline:state.day+3};rivalryLog('경쟁사가 자금난을 노려 인수 제안을 보냈습니다. 매각은 직접 수락할 때만 진행됩니다.','競合が資金難を狙って買収を提案。売却は自分で承諾した場合のみ実行されます。');}}
}
function rivalOpportunityForExpansion(l){const x=competitionStrength(l.map);return demand({loc:l.id,level:1})*(.5+1/(1+x.player)) / l.cost;}
function competitionBody(){
 const r=ensureRivalry(),locked=!state.started||state.ended;
 return `<div class="enterprise-metrics"><div><span>${T('경쟁사 운영 기기','競合の稼働機械')}</span><strong>${state.npc.owned.length}</strong></div><div><span>${T('관찰된 전략','観測された戦略')}</span><strong>${tr(RIVAL_MODES[r.mode])}</strong></div><div><span>${T('사업 상태','事業状態')}</span><strong>${r.defeated?T('철수','撤退'):T('영업 중','営業中')}</strong></div></div><p><strong>${T('상대 전략','相手の戦略')}: ${tr(RIVAL_MODES[r.mode])}</strong> · ${tr(MAPS[r.target].name)} · ${T('유효 기한','有効期限')} DAY ${r.until}</p>${r.plan?`<p class="permit-warning">${T('예고','予告')}: DAY ${r.plan.start}–${r.plan.until} · ${tr(MAPS[r.plan.target].name)} · ${tr(RIVAL_MODES[r.plan.mode])}</p>`:''}<p>${T('저가·품질·재고·브랜드가 양쪽 회사의 선택률과 수익에 연결됩니다. 가격 전쟁은 상대를 압박하지만 내 마진도 줄입니다. 점유율은 구매 매력으로 산출한 예상 선택률이며, 나머지는 구매 포기입니다.','低価格・品質・在庫・ブランドが両社の選択率と利益に連動。価格戦争は相手を圧迫しますが自社利益も減少。シェアは購買魅力から算出した推定選択率で、残りは購入見送りです。')}</p>`+enterpriseTable([T('상권','商圏'),T('자사 / 경쟁 선택률','自社／競合の選択率'),T('경쟁 가격','競合価格'),T('대응 전략','対抗戦略')],MAPS.map((map,i)=>{const x=competitionStrength(i),c=activeCampaign(i);return `<tr><td>${tr(map.name)}</td><td>${Math.round(x.share*100)}% / ${Math.round(x.rivalShare*100)}%</td><td>${money(state.enterprise.rivalPrices[i])}</td><td>${c?`${tr(CAMPAIGNS[c.kind].name)} · DAY ${c.until}`:Object.entries(CAMPAIGNS).map(([k,v])=>`<button class="small" data-campaign="${k}" data-campaign-map="${i}" ${disabled(locked||state.cash<v.cost||!state.machines.some(m=>LOCATIONS[m.loc].map===i))}>${tr(v.name)} ${money(v.cost)}</button>`).join(' ')}</td></tr>`;}))+`<div class="enterprise-columns">${Object.values(CAMPAIGNS).map(c=>`<div><h3>${tr(c.name)}</h3><p>${tr(c.desc)}</p></div>`).join('')}</div><h3>${T('경쟁 전황','競争の推移')}</h3><div class="order-list">${r.history.length?r.history.slice(0,8).map(h=>`<p>DAY ${h.day} · ${tr(h.text)}</p>`).join(''):T('아직 공세가 없습니다. 상권이 겹치면 경쟁이 본격화됩니다.','まだ攻勢はありません。商圏が重なると競争が本格化します。')}</div>`;
}
function renderRivalPanel(){const r=ensureRivalry();patchPanel($('rival-panel'),`<div class="panel-head"><h2>${T('경쟁사 · 모노벤드','競合・モノベンド')}</h2><span class="tag">${state.npc.owned.length}${T('대','台')}</span></div><div class="hq-body"><p>${T('관찰된 전략','観測された戦略')}: ${tr(RIVAL_MODES[r.mode])} · ${tr(MAPS[r.target].name)}</p>${r.plan?`<p class="permit-warning">DAY ${r.plan.start} · ${tr(RIVAL_MODES[r.plan.mode])} ${T('예고','予告')}</p>`:''}<button class="full" data-enterprise-tab="rivalry">${T('경쟁 상황 · 대응 전략','競争状況・対抗戦略')}</button>${state.offer?`<p>${tr(LOCATIONS[state.offer.loc].name)} · ${money(state.offer.price)} · DAY ${state.offer.deadline}</p><button class="small full" id="accept-offer" ${disabled(!saleAvailable())}>${T('매입 제안 검토','買収提案を検討')}</button>`:''}</div>`);}

ENTERPRISE_TABS.splice(3,0,['rivalry',B('경쟁 전략','競争戦略')]);
const modalBeforeLanguages=drawModal;
drawModal=function(){modalBeforeLanguages();if(!modalView)return;const bar=document.createElement('div');bar.className='entry-languages';bar.setAttribute('aria-label','Language / 言語 / 언어');bar.innerHTML=`<span>Language / 言語</span><button type="button" lang="ko" data-entry-language="ko" aria-pressed="${lang==='ko'}">한국어</button><button type="button" lang="ja" data-entry-language="ja" aria-pressed="${lang==='ja'}">日本語</button>`;$('modal-body').prepend(bar);};
document.addEventListener('click',event=>{const language=event.target.closest('[data-entry-language]');if(language){changeLanguage(language.dataset.entryLanguage);return;}const campaign=event.target.closest('[data-campaign]');if(campaign)startCampaign(Number(campaign.dataset.campaignMap),campaign.dataset.campaign);});
function validRivalry(r){return r&&r.version===1&&['steady','price','advertise','retreat','closed'].includes(r.mode)&&(!r.plan||(['price','advertise'].includes(r.plan.mode)&&int(r.plan.target,0,MAPS.length-1)&&int(r.plan.start,1,1000000)&&int(r.plan.until,r.plan.start,1000000)))&&int(r.target,0,MAPS.length-1)&&int(r.until,0,1000000)&&int(r.turnDay,0,1000000)&&finite(r.lastProfit)&&(r.pendingProfit==null||finite(r.pendingProfit))&&int(r.losses,0,1000000)&&int(r.insolvency,0,1000000)&&typeof r.defeated==='boolean'&&Array.isArray(r.campaigns)&&r.campaigns.length===MAPS.length&&r.campaigns.every(c=>!c||(['discount','loyalty','defend'].includes(c.kind)&&int(c.until,1,1000000)))&&Array.isArray(r.history)&&r.history.length<=20&&r.history.every(h=>int(h.day,1,1000000)&&Array.isArray(h.text)&&h.text.length===2&&h.text.every(t=>typeof t==='string'&&t.length<2000));}
